(function(){'use strict';
var theme=localStorage.getItem('consica-theme')||'dark';
document.documentElement.setAttribute('data-theme',theme);
var app,container,skeleton,errorBoundary,errorMsg,svgContainer,infoTitle,infoDesc,stepsList,playBtn,resetBtn,speedSlider,speedVal,themeBtn,challengeOverlay,challengeBody,challengeClose,completionOverlay,completionScore,completionClose,challengeBtn,rafId,animating=false,t=0,activeNode=null,nodes=[],flowDots=[],speed=1,challengeState={questions:[],current:0,answers:{},submitted:false};
var components=[
{id:'pixels',name:'Pixel Layer',sublabel:'Raw pixel values',desc:'At the lowest level, images are grids of pixel values representing color or intensity at each point.',purpose:'Capture raw visual information',how:'Each pixel stores RGB (red, green, blue) values from 0-255 per channel',why:'This is how cameras and screens represent images',analogy:'Individual grains of sand forming a beach',funFact:'A 1080p image has about 2 million pixels',takeaway:'All vision starts with raw pixels',mistake:'Pixel values alone do not convey meaning'},
{id:'edges',name:'Edge Detection',sublabel:'Finding boundaries',desc:'Edge detection identifies boundaries where pixel values change sharply, revealing outlines of objects.',purpose:'Detect transitions between regions',how:'Convolutional filters like Sobel or Canny detect gradients in pixel intensity',why:'Edges define object boundaries',analogy:'Tracing the outline of a shape in a coloring book',funFact:'The human visual system also detects edges first',takeaway:'Edges are the building blocks of shape recognition',mistake:'Too much noise can create false edges'},
{id:'shapes',name:'Shape Recognition',sublabel:'Identifying forms',desc:'The model combines edges into geometric shapes and textures - corners, curves, patterns that form recognizable parts.',purpose:'Assemble edges into meaningful forms',how:'Higher-level convolutional layers respond to combinations of edges like circles, squares',why:'Shapes are the next level of visual abstraction',analogy:'Connecting dots to reveal a picture',funFact:'Some neurons in the brain fire specifically for certain shapes',takeaway:'Shapes bridge edges and objects',mistake:'Occluded (partially hidden) shapes are harder to recognize'},
{id:'features',name:'Feature Maps',sublabel:'Learned patterns',desc:'Feature maps are the output of convolutional filters - they highlight where specific patterns exist in the image.',purpose:'Encode learned visual patterns spatially',how:'Each filter slides across the image producing an activation map',why:'Multiple filters detect different patterns in parallel',analogy:'A set of stencils checking different patterns',funFact:'Early layers detect edges, later layers detect complex objects',takeaway:'Feature maps reveal what the model focuses on',mistake:'Feature maps can fire on irrelevant background patterns'},
{id:'objects',name:'Object Detection',sublabel:'Identifying instances',desc:'Object detection locates and classifies specific objects within an image, drawing bounding boxes around them.',purpose:'Find and label specific objects',how:'Architectures like YOLO or Faster R-CNN scan for regions containing objects',why:'Real-world vision requires locating specific things',analogy:'Finding Waldo in a crowded picture',funFact:'YOLO (You Only Look Once) can detect objects in real-time video',takeaway:'Detection powers autonomous driving and surveillance',mistake:'Small or overlapping objects are still challenging'},
{id:'segmentation',name:'Segmentation',sublabel:'Pixel-level classification',desc:'Segmentation assigns a class label to every single pixel in an image, providing a complete understanding of the scene.',purpose:'Understand every part of the image',how:'U-Net or Mask R-CNN classify each pixel into categories like road, car, sky, person',why:'Complete scene understanding requires knowing what everything is',analogy:'Coloring in a paint-by-numbers picture',funFact:'Medical image segmentation can detect tumors pixel by pixel',takeaway:'Segmentation is the most detailed form of image understanding',mistake:'Segmentation requires large amounts of pixel-level labeled data'}
];
var connectionsData=[{from:'pixels',to:'edges'},{from:'edges',to:'shapes'},{from:'shapes',to:'features'},{from:'features',to:'objects'},{from:'features',to:'segmentation'}];
var stepsData=[
{id:'pixels',label:'Pixel Layer - raw RGB pixel values from the image'},
{id:'edges',label:'Edge Detection - find boundaries between regions'},
{id:'shapes',label:'Shape Recognition - combine edges into geometric forms'},
{id:'features',label:'Feature Maps - learned pattern activation maps'},
{id:'objects',label:'Object Detection - locate and classify specific objects'},
{id:'segmentation',label:'Segmentation - classify every pixel in the image'}
];
var challenges=[
{q:'What do convolutional filters in early vision layers detect?',o:['Complete objects','Edges and simple patterns','Text','Colors only'],a:1},
{q:'How many pixels does a 1080p image contain approximately?',o:['200,000','2 million','20 million','200 million'],a:1},
{q:'What does object detection produce beyond classification?',o:['Text labels','Bounding boxes around objects','Color histograms','File sizes'],a:1},
{q:'What is the most detailed form of image understanding?',o:['Edge detection','Segmentation - classifying every pixel','Object detection','Feature extraction'],a:1},
{q:'Why are small or overlapping objects challenging for vision models?',o:['They use different colors','They can merge into one detection or be missed','They are too bright','They move too fast'],a:1},
{q:'What are feature maps in a convolutional neural network?',o:['Maps of the world','Activation maps showing where patterns exist','Color histograms','Pixel value arrays'],a:1}
];
function init(){app=document.getElementById('app');container=document.getElementById('diagram-container');skeleton=document.getElementById('loading-skeleton');errorBoundary=document.getElementById('error-boundary');errorMsg=document.getElementById('error-message');svgContainer=document.getElementById('svg-container');infoTitle=document.getElementById('info-title');infoDesc=document.getElementById('info-desc');stepsList=document.getElementById('steps-list');playBtn=document.getElementById('play-btn');resetBtn=document.getElementById('reset-btn');speedSlider=document.getElementById('speed-slider');speedVal=document.getElementById('speed-value');themeBtn=document.getElementById('theme-toggle');challengeOverlay=document.getElementById('challenge-overlay');challengeBody=document.getElementById('challenge-body');challengeClose=document.getElementById('challenge-close');completionOverlay=document.getElementById('completion-overlay');completionScore=document.getElementById('completion-score');completionClose=document.getElementById('completion-close');challengeBtn=document.getElementById('challenge-btn');
try{buildDiagram();setupControls();setupChallenge();showContainer();}catch(e){showError(e.message||'Failed to build diagram');}}
function showContainer(){skeleton.classList.add('hidden');container.classList.remove('hidden');}
function showError(msg){skeleton.classList.add('hidden');errorBoundary.classList.remove('hidden');errorMsg.textContent=msg;}
function buildDiagram(){var W=860,H=300;var svg=svgCreate('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':'Computer vision pipeline from raw pixels through edge detection, shapes, features, to object detection and segmentation'});svgContainer.appendChild(svg);
var defs=svgCreate('defs');svg.appendChild(defs);
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="var(--conn-stroke)"/></marker><marker id="arrowLight" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#94a3b8"/></marker>';
var positions={pixels:{x:70,y:80},edges:{x:210,y:80},shapes:{x:350,y:80},features:{x:490,y:80},objects:{x:350,y:220},segmentation:{x:630,y:220}};
connectionsData.forEach(function(c){var f=positions[c.from],t=positions[c.to];var line;if(c.from==='features'&&c.to==='objects'){var d='M'+f.x+','+(f.y+26)+' Q'+((f.x+t.x)/2)+','+((f.y+t.y)/2)+' '+t.x+','+(t.y-26);line=svgCreate('path',{d:d,class:'connection-line',fill:'none','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}else if(c.from==='features'&&c.to==='segmentation'){line=svgCreate('line',{x1:f.x+70,y1:f.y,x2:t.x-70,y2:t.y,class:'connection-line','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}else{line=svgCreate('line',{x1:f.x+70,y1:f.y,x2:t.x-70,y2:t.y,class:'connection-line','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}svg.appendChild(line);var fd=svgCreate('circle',{class:'flow-dot',cx:0,cy:0,r:0,fill:'var(--accent)'});svg.appendChild(fd);flowDots.push({el:fd,sx:f.x+70,sy:f.y,ex:t.x-70,ey:t.y});});
components.forEach(function(cp){var p=positions[cp.id];var g=svgCreate('g',{class:'node-g',tabIndex:0,role:'button','aria-label':cp.name+': '+cp.sublabel});g.dataset.id=cp.id;var rx=svgCreate('rect',{x:p.x-70,y:p.y-26,width:140,height:52,rx:10,class:'node-rect'});g.appendChild(rx);var lbl=svgCreate('text',{x:p.x,y:p.y-4,class:'node-label'});lbl.textContent=cp.name;g.appendChild(lbl);var slbl=svgCreate('text',{x:p.x,y:p.y+14,class:'node-sublabel'});slbl.textContent=cp.sublabel;g.appendChild(slbl);g.addEventListener('click',function(){selectNode(cp.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(cp.id);}});svg.appendChild(g);nodes.push({el:g,data:cp,pos:p});});
var selected=false;components.forEach(function(c){if(!selected){selectNode(c.id);selected=true;}});renderSteps();}
function svgCreate(tag,attrs){var el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(var k in attrs)el.setAttribute(k,attrs[k]);return el;}
function selectNode(id){activeNode=id;var cp=getComp(id);if(!cp)return;nodes.forEach(function(n){var r=n.el.querySelector('.node-rect');if(r)r.classList.toggle('active',n.data.id===id);});infoTitle.textContent=cp.name+' - '+cp.sublabel;infoDesc.innerHTML='<strong>Purpose:</strong> '+cp.purpose+'<br><br><strong>How it works:</strong> '+cp.how+'<br><br><strong>Why it matters:</strong> '+cp.why+'<br><br><strong>Analogy:</strong> '+cp.analogy+(cp.funFact?'<br><br><strong>Fun fact:</strong> '+cp.funFact:'')+'<br><br><strong>Key takeaway:</strong> '+cp.takeaway+'<br><br><strong>Common mistake:</strong> '+cp.mistake;var items=stepsList.querySelectorAll('li');items.forEach(function(li){li.classList.toggle('active',li.dataset.id===id);});}
function getComp(id){for(var i=0;i<components.length;i++){if(components[i].id===id)return components[i];}return null;}
function renderSteps(){stepsList.innerHTML='';components.forEach(function(c){var li=document.createElement('li');li.dataset.id=c.id;li.textContent=c.name+' - '+c.sublabel;li.tabIndex=0;li.addEventListener('click',function(){selectNode(c.id);});li.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(c.id);}});stepsList.appendChild(li);});}
function animateDiagram(){var start=performance.now();function frame(now){if(!animating){rafId=null;return;}var dt=(now-start)/1000*speed;t=(t+dt)%1;flowDots.forEach(function(d){d.el.setAttribute('cx',d.sx+(d.ex-d.sx)*t);d.el.setAttribute('cy',d.sy+(d.ey-d.sy)*t);d.el.setAttribute('r',4);});rafId=requestAnimationFrame(frame);}rafId=requestAnimationFrame(frame);}
function setupControls(){themeBtn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem('consica-theme',theme);});playBtn.addEventListener('click',function(){animating=!animating;if(animating){playBtn.innerHTML='&#9646;&#9646;';animateDiagram();}else{playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});resetBtn.addEventListener('click',function(){t=0;flowDots.forEach(function(d){d.el.setAttribute('r',0);});if(animating){animating=false;playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});speedSlider.addEventListener('input',function(){speed=parseFloat(this.value);speedVal.textContent=speed+'x';});document.addEventListener('keydown',function(e){if(e.key==='Escape'){challengeOverlay.classList.add('hidden');completionOverlay.classList.add('hidden');}});}
function setupChallenge(){challengeBtn.addEventListener('click',function(){openChallenge();});challengeClose.addEventListener('click',function(){challengeOverlay.classList.add('hidden');});completionClose.addEventListener('click',function(){completionOverlay.classList.add('hidden');challengeOverlay.classList.add('hidden');});}
function openChallenge(){challengeState.questions=challenges.slice().sort(function(){return Math.random()-0.5;}).slice(0,5);challengeState.current=0;challengeState.answers={};challengeState.submitted=false;challengeOverlay.classList.remove('hidden');renderQuestion();}
function renderQuestion(){var q=challengeState.questions[challengeState.current];if(!q){finishChallenge();return;}var html='<div class="question"><div class="question-text">'+(challengeState.current+1)+'. '+q.q+'</div><div class="options">';q.o.forEach(function(opt,i){var sel=challengeState.answers[challengeState.current]===i?' selected':'';var cls=challengeState.submitted?(i===q.a?' correct':(challengeState.answers[challengeState.current]===i?' wrong':'')):'';html+='<label class="option-label'+sel+cls+'"><input type="radio" name="q'+challengeState.current+'" value="'+i+'"'+(challengeState.submitted?' disabled':'')+(sel?' checked':'')+' onchange="('+selectOption.toString()+')('+challengeState.current+','+i+')">'+opt+'</label>';});html+='</div></div>';html+='<div class="challenge-actions">';if(!challengeState.submitted){html+='<button class="btn-primary" onclick="('+submitChallenge.toString()+')()">Submit Answer</button>';}else{if(challengeState.current<challengeState.questions.length-1){html+='<button class="btn-primary" onclick="('+nextQuestion.toString()+')()">Next Question</button>';}else{html+='<button class="btn-primary" onclick="('+finishChallenge.toString()+')()">See Results</button>';}}html+='</div>';challengeBody.innerHTML=html;}
function selectOption(qIdx,optIdx){if(challengeState.submitted)return;challengeState.answers[qIdx]=optIdx;renderQuestion();}
function submitChallenge(){challengeState.submitted=true;renderQuestion();}
function nextQuestion(){challengeState.current++;challengeState.submitted=false;renderQuestion();}
function finishChallenge(){var correct=0,total=challengeState.questions.length;challengeState.questions.forEach(function(q,i){if(challengeState.answers[i]===q.a)correct++;});completionScore.textContent='You scored '+correct+'/'+total;completionOverlay.classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',init);
if(document.readyState==='complete'||document.readyState==='interactive')init();
})();
