(function(){'use strict';
const STORE='consica-theme';
const nodes=[{id:'client',name:'WebSocket Client',desc:'The client initiates a WebSocket connection via an HTTP Upgrade request. Browsers implement the WebSocket API natively.',details:'Protocol: wss:// (secure) or ws://\nAPI: WebSocket JavaScript API\nReadyState: CONNECTING → OPEN → CLOSING → CLOSED\nBinary Type: ArrayBuffer or Blob'},{id:'server',name:'WebSocket Server',desc:'The server accepts the upgrade and maintains persistent connections. Libraries: ws (Node), Socket.IO, Django Channels.',details:'Protocol: RFC 6455\nHandshake: 101 Switching Protocols\nKeepalive: Ping/Pong frames\nLibraries: ws, Socket.IO, SockJS'},{id:'chat',name:'Live Chat',desc:'WebSockets enable instant two-way messaging. Messages are pushed immediately without polling.',details:'Latency: <100ms\nDirection: Bidirectional\nExample: Slack, Discord, WhatsApp Web\nScale: Millions of concurrent connections'},{id:'gaming',name:'Real-Time Gaming',desc:'Multiplayer games use WebSockets for state synchronization, player actions, and real-time updates.',details:'Latency: Critical (<50ms)\nUpdate rate: 20-60 ticks/sec\nState: Server-authoritative\nExample: .io games'}];
const questions=[{q:'What initiates a WebSocket connection?',opts:['POST request','GET with Upgrade header','TCP handshake','UDP packet'],ans:1},{q:'What HTTP status code indicates a successful WebSocket upgrade?',opts:['200','301','101','404'],ans:2},{q:'Which WebSocket frame is used for connection health checks?',opts:['Text','Binary','Ping/Pong','Close'],ans:2},{q:'What is the WebSocket URL scheme for secure connections?',opts:['ws://','wss://','https://','tcp://'],ans:1},{q:'Which is NOT a typical WebSocket use case?',opts:['Live chat','Stock ticker','Static file serving','Multiplayer gaming'],ans:2},{q:'What API do browsers provide for WebSockets?',opts:['Socket API','WebSocket API','Stream API','Push API'],ans:1}];
let speed=1,playing=false,theme='dark',rAF=null,t=0;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupNodes();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}
function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}
function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}
function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';});}}
function setupNodes(){var all=nodes.slice();all.push({id:'finance',name:'Live Finance',desc:'Stock prices, crypto rates, and financial data stream via WebSockets in real-time.',details:'Data: Real-time ticks\nUpdate rate: Millisecond precision\nExample: Binance WebSocket API\nProtocol: JSON over WebSocket'});all.push({id:'iot',name:'IoT Monitoring',desc:'IoT sensors push telemetry data over WebSockets for real-time dashboard updates.',details:'Data: Temperature, humidity\nProtocol: MQTT over WebSocket\nDashboard: Real-time charts\nScale: Thousands of devices'});all.push({id:'text',name:'Text Frame',desc:'UTF-8 text payloads. The most common WebSocket frame type, used for JSON messages.',details:'Opcode: 0x1\nPayload: UTF-8 text\nMax size: Configurable\nUse: JSON/XML data'});all.push({id:'binary',name:'Binary Frame',desc:'Arbitrary binary data. Used for efficient transmission of protobuf, images, or game state.',details:'Opcode: 0x2\nPayload: Raw binary\nEfficiency: Higher than text\nUse: Game state, protobuf'});all.push({id:'close',name:'Close Frame',desc:'Initiates the WebSocket closing handshake. Either party can send a close frame with a status code.',details:'Opcode: 0x8\nStatus Codes: 1000 (normal), 1001 (going away)\nDirection: Bidirectional\nFollowed by: TCP FIN'});all.forEach(function(n){var sel='[data-phase="'+n.id+'"], [data-use="'+n.id+'"], [data-frame="'+n.id+'"]';var els=document.querySelectorAll(sel);els.forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo(n);});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showInfo(n);}});});});document.addEventListener('click',function(e){if(!e.target.closest('[data-phase]')&&!e.target.closest('[data-use]')&&!e.target.closest('[data-frame]')&&!e.target.closest('.duplex-bg')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}
function showInfo(node){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel)return;title.textContent=node.name;desc.textContent=node.desc;details.innerHTML='<p>'+node.details.split('\n').join('<br>')+'</p>';panel.hidden=false;}
function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}
function startRAF(){function frame(){if(playing){t+=0.02*speed;var p1=document.getElementById('ws-dot1');var p2=document.getElementById('ws-dot2');if(p1){p1.setAttribute('cx',270+(620-270)*((Math.sin(t)+1)/2));p1.setAttribute('cy',280);p1.setAttribute('visibility','visible');}if(p2){p2.setAttribute('cx',620+(270-620)*((Math.sin(t+1.5)+1)/2));p2.setAttribute('cy',310);p2.setAttribute('visibility','visible');}}rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}
function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';t=0;document.getElementById('ws-dot1').setAttribute('visibility','hidden');document.getElementById('ws-dot2').setAttribute('visibility','hidden');const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}}
function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}
let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}
function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
