(function(){'use strict';
const STORE='consica-theme';
const layers=[{id:7,name:'Application',desc:'The layer closest to the end user. Provides network services like email, file transfer, and web browsing.',details:'Protocols: HTTP, FTP, SMTP, DNS\nUnit: Data\nFunction: User interface & application support',pdu:'Data'},{id:6,name:'Presentation',desc:'Translates data between the application layer and the network. Handles encryption, compression, and data format conversion.',details:'Protocols: SSL/TLS, JPEG, ASCII\nUnit: Data\nFunction: Translation, encryption, compression',pdu:'Data'},{id:5,name:'Session',desc:'Manages sessions between applications. Controls dialogue — when to start, stop, or pause communication.',details:'Protocols: NetBIOS, RPC, PPTP\nUnit: Data\nFunction: Session management & synchronization',pdu:'Data'},{id:4,name:'Transport',desc:'Ensures complete, reliable data transfer. Provides error checking, flow control, and segmentation.',details:'Protocols: TCP, UDP\nUnit: Segment\nFunction: End-to-end delivery & reliability',pdu:'Segment'},{id:3,name:'Network',desc:'Routes data packets across networks. Handles logical addressing (IP) and path determination.',details:'Protocols: IP, ICMP, ARP\nUnit: Packet\nFunction: Routing & logical addressing',pdu:'Packet'},{id:2,name:'Data Link',desc:'Transfers frames between directly connected nodes. Handles MAC addressing and error detection.',details:'Protocols: Ethernet, PPP, Switch\nUnit: Frame\nFunction: MAC addressing & framing',pdu:'Frame'},{id:1,name:'Physical',desc:'Transmits raw bit streams over physical media. Defines electrical, mechanical, and procedural specs.',details:'Protocols: Ethernet, USB, Bluetooth\nUnit: Bits\nFunction: Raw bit transmission',pdu:'Bits'}];
const questions=[{q:'Which OSI layer handles routing and logical addressing?',opts:['Transport','Network','Data Link','Session'],ans:1},{q:'What protocol operates at the Transport layer?',opts:['IP','Ethernet','TCP','HTTP'],ans:2},{q:'Which layer is closest to the end user?',opts:['Presentation','Session','Application','Physical'],ans:2},{q:'What unit of data is used at the Data Link layer?',opts:['Packet','Segment','Frame','Bits'],ans:2},{q:'Which layer handles encryption and data format conversion?',opts:['Session','Application','Presentation','Transport'],ans:2},{q:'How many layers are in the OSI model?',opts:['4','5','6','7'],ans:3}];
let speed=1,playing=false,theme='dark',rAF=null,packetY=95,packetDir=1,selectedLayer=null;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupLayers();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}

function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}

function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}

function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';animatePacket();});}}

function setupLayers(){layers.forEach(function(l){const rect=document.querySelector('.layer-box[data-layer="'+l.id+'"]');if(rect){rect.addEventListener('click',function(e){e.stopPropagation();showLayerInfo(l);});rect.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showLayerInfo(l);}});}});document.addEventListener('click',function(e){if(!e.target.closest('.layer-box')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}

function showLayerInfo(layer){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel||!title||!desc||!details)return;title.textContent='Layer '+layer.id+': '+layer.name;desc.textContent=layer.desc;details.innerHTML='<p><strong>PDU:</strong> '+layer.pdu+'</p><p><strong>Function:</strong> '+layer.details.split('\n').slice(2).join('<br>')+'</p><p><strong>Protocols:</strong> '+layer.details.split('\n')[0].replace('Protocols: ','')+'</p>';panel.hidden=false;document.querySelectorAll('.layer-box').forEach(function(r){r.classList.toggle('active',parseInt(r.getAttribute('data-layer'))===layer.id);});selectedLayer=layer.id;}

function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';animatePacket();});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}

function animatePacket(){const dot=document.getElementById('packet-dot');const anim=document.getElementById('packet-anim-down');if(!dot||!anim)return;if(playing){const dur=Math.max(0.5,3/speed);anim.setAttribute('dur',dur+'s');anim.beginElement();dot.style.visibility='visible';}else{dot.style.visibility='hidden';anim.endElement();}}

function startRAF(){function frame(){rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}

function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';const dot=document.getElementById('packet-dot');if(dot)dot.style.visibility='hidden';const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;document.querySelectorAll('.layer-box').forEach(function(r){r.classList.remove('active');});const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}selectedLayer=null;}

function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}

let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}

function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}

if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
