(function(){'use strict';
var theme=localStorage.getItem('consica-theme')||'dark';
document.documentElement.setAttribute('data-theme',theme);
var app,container,skeleton,errorBoundary,errorMsg,svgContainer,infoTitle,infoDesc,stepsList,playBtn,resetBtn,speedSlider,speedVal,themeBtn,challengeOverlay,challengeBody,challengeClose,completionOverlay,completionScore,completionClose,challengeBtn,rafId,animating=false,t=0,activeNode=null,nodes=[],flowDots=[],speed=1,challengeState={questions:[],current:0,answers:{},submitted:false};
var components=[
{id:'input',name:'Input Layer',sublabel:'Raw data',desc:'The input layer receives raw data and passes it to the first hidden layer for processing.',purpose:'Initial data entry point',how:'Each neuron passes the raw feature value forward without transformation',why:'The data must enter the network somewhere',analogy:'Raw ingredients entering a factory',funFact:'Deep networks can have 100+ layers',takeaway:'Deep learning means many hidden layers',mistake:'Input dimensions must match the data'},
{id:'hidden1',name:'Hidden Layer 1',sublabel:'Low-level features',desc:'Early hidden layers detect simple patterns like edges in images or phonemes in audio.',purpose:'Detect simple, low-level patterns',how:'Small local receptive fields scan for basic features like lines or dots',why:'Complex patterns are built from simple ones',analogy:'Recognizing straight lines in a drawing',funFact:'First-layer filters in vision models often look like Gabor filters',takeaway:'Shallow layers see simple features',mistake:'Too few neurons in early layers can bottleneck information'},
{id:'hidden2',name:'Hidden Layer 2',sublabel:'Mid-level features',desc:'Middle layers combine low-level features to recognize more complex structures like shapes or words.',purpose:'Build patterns from simpler pieces',how:'Combine outputs from layer 1 to detect curves, corners, or syllable sounds',why:'Hierarchy enables increasingly abstract representations',analogy:'Assembling lines into shapes like circles and squares',funFact:'Middle layers often learn interpretable features automatically',takeaway:'Mid layers detect object parts and patterns',mistake:'Middle layers can memorize if the network is too wide'},
{id:'hidden3',name:'Hidden Layer 3',sublabel:'High-level features',desc:'Deep layers recognize complete concepts like faces, objects, or full phrases by combining mid-level features.',purpose:'Recognize complete, abstract concepts',how:'Full connectivity integrates all mid-level features into holistic patterns',why:'Deep abstraction enables human-level recognition',analogy:'Identifying a face from eyes, nose, and mouth',funFact:'DeepDream amplifies features in middle layers to create surreal images',takeaway:'Deep layers see the big picture',mistake:'Very deep networks need skip connections to train'},
{id:'dropout',name:'Dropout Layer',sublabel:'Prevents overfitting',desc:'Dropout randomly deactivates neurons during training, forcing the network to learn redundant representations.',purpose:'Regularize the network to generalize better',how:'Randomly set a fraction of neuron outputs to zero during each training pass',why:'Prevents neurons from co-adapting too much',analogy:'A team practicing with random members absent',funFact:'Dropout was invented by Geoffrey Hinton in 2012',takeaway:'Dropout improves generalization significantly',mistake:'Dropout is only used during training, not inference'},
{id:'output',name:'Output Layer',sublabel:'Final result',desc:'The final layer produces the network output, using specialized activation functions for the task.',purpose:'Generate the final prediction',how:'Softmax for multi-class, sigmoid for binary, linear for regression',why:'Must match the target format',analogy:'The assembly line finished product',funFact:'Output layer size equals number of classes or prediction dimensions',takeaway:'Output shape depends on the problem',mistake:'Wrong loss function for the task invalidates learning'}
];
var connectionsData=[{from:'input',to:'hidden1'},{from:'hidden1',to:'hidden2'},{from:'hidden2',to:'hidden3'},{from:'hidden3',to:'dropout'},{from:'dropout',to:'output'}];
var stepsData=[
{id:'input',label:'Input Layer - raw data enters the deep network'},
{id:'hidden1',label:'Hidden Layer 1 - detects low-level features like edges'},
{id:'hidden2',label:'Hidden Layer 2 - combines into mid-level patterns'},
{id:'hidden3',label:'Hidden Layer 3 - recognizes high-level concepts'},
{id:'dropout',label:'Dropout Layer - randomly deactivates neurons to prevent overfitting'},
{id:'output',label:'Output Layer - final classification or prediction'}
];
var challenges=[
{q:'What distinguishes deep learning from shallow neural networks?',o:['Deep learning uses more data','Deep learning has many hidden layers','Deep learning is faster','Deep learning uses different math'],a:1},
{q:'What do early hidden layers in a vision network detect?',o:['Complete objects','Low-level features like edges and lines','Abstract concepts','Output probabilities'],a:1},
{q:'What is the purpose of dropout during training?',o:['Make training faster','Prevent overfitting by forcing redundant representations','Reduce model size','Improve accuracy on training data'],a:1},
{q:'Why can very deep networks be hard to train?',o:['They need too much data','Gradients can vanish through many layers','They are too fast','They cannot use GPUs'],a:1},
{q:'What would a network with all linear (no activation) layers be equivalent to?',o:['A deep network','A single linear layer','A recurrent network','A convolutional network'],a:1},
{q:'How does the depth of a network relate to feature abstraction?',o:['Shallow equals abstract, deep equals simple','Deeper layers detect more abstract, complex features','Depth does not affect abstraction','All layers detect the same level'],a:1}
];
function init(){app=document.getElementById('app');container=document.getElementById('diagram-container');skeleton=document.getElementById('loading-skeleton');errorBoundary=document.getElementById('error-boundary');errorMsg=document.getElementById('error-message');svgContainer=document.getElementById('svg-container');infoTitle=document.getElementById('info-title');infoDesc=document.getElementById('info-desc');stepsList=document.getElementById('steps-list');playBtn=document.getElementById('play-btn');resetBtn=document.getElementById('reset-btn');speedSlider=document.getElementById('speed-slider');speedVal=document.getElementById('speed-value');themeBtn=document.getElementById('theme-toggle');challengeOverlay=document.getElementById('challenge-overlay');challengeBody=document.getElementById('challenge-body');challengeClose=document.getElementById('challenge-close');completionOverlay=document.getElementById('completion-overlay');completionScore=document.getElementById('completion-score');completionClose=document.getElementById('completion-close');challengeBtn=document.getElementById('challenge-btn');
try{buildDiagram();setupControls();setupChallenge();showContainer();}catch(e){showError(e.message||'Failed to build diagram');}}
function showContainer(){skeleton.classList.add('hidden');container.classList.remove('hidden');}
function showError(msg){skeleton.classList.add('hidden');errorBoundary.classList.remove('hidden');errorMsg.textContent=msg;}
function buildDiagram(){var W=860,H=380;var svg=svgCreate('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':'Deep learning network showing input through multiple hidden layers to output'});svgContainer.appendChild(svg);
var defs=svgCreate('defs');svg.appendChild(defs);
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="var(--conn-stroke)"/></marker><marker id="arrowLight" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#94a3b8"/></marker>';
var positions={input:{x:70,y:180},hidden1:{x:220,y:100},hidden2:{x:370,y:180},hidden3:{x:520,y:260},dropout:{x:670,y:180},output:{x:800,y:180}};
connectionsData.forEach(function(c){var f=positions[c.from],t=positions[c.to];var d='M'+(f.x+70)+','+f.y+' Q'+((f.x+t.x)/2)+','+((f.y+t.y)/2)+' '+(t.x-70)+','+t.y;var line=svgCreate('path',{d:d,class:'connection-line',fill:'none','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});svg.appendChild(line);var fd=svgCreate('circle',{class:'flow-dot',cx:0,cy:0,r:0,fill:'var(--accent)'});svg.appendChild(fd);flowDots.push({el:fd,sx:f.x+70,sy:f.y,ex:t.x-70,ey:t.y});});
components.forEach(function(cp){var p=positions[cp.id];var g=svgCreate('g',{class:'node-g',tabIndex:0,role:'button','aria-label':cp.name+': '+cp.sublabel});g.dataset.id=cp.id;var rx=svgCreate('rect',{x:p.x-70,y:p.y-26,width:140,height:52,rx:10,class:'node-rect'});g.appendChild(rx);var lbl=svgCreate('text',{x:p.x,y:p.y-4,class:'node-label'});lbl.textContent=cp.name;g.appendChild(lbl);var slbl=svgCreate('text',{x:p.x,y:p.y+14,class:'node-sublabel'});slbl.textContent=cp.sublabel;g.appendChild(slbl);g.addEventListener('click',function(){selectNode(cp.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(cp.id);}});svg.appendChild(g);nodes.push({el:g,data:cp,pos:p});});
var selected=false;components.forEach(function(c){if(!selected){selectNode(c.id);selected=true;}});renderSteps();}
function svgCreate(tag,attrs){var el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(var k in attrs)el.setAttribute(k,attrs[k]);return el;}
function selectNode(id){activeNode=id;var cp=getComp(id);if(!cp)return;nodes.forEach(function(n){var r=n.el.querySelector('.node-rect');if(r)r.classList.toggle('active',n.data.id===id);});infoTitle.textContent=cp.name+' - '+cp.sublabel;infoDesc.innerHTML='<strong>Purpose:</strong> '+cp.purpose+'<br><br><strong>How it works:</strong> '+cp.how+'<br><br><strong>Why it matters:</strong> '+cp.why+'<br><br><strong>Analogy:</strong> '+cp.analogy+(cp.funFact?'<br><br><strong>Fun fact:</strong> '+cp.funFact:'')+'<br><br><strong>Key takeaway:</strong> '+cp.takeaway+'<br><br><strong>Common mistake:</strong> '+cp.mistake;var items=stepsList.querySelectorAll('li');items.forEach(function(li){li.classList.toggle('active',li.dataset.id===id);});}
function getComp(id){for(var i=0;i<components.length;i++){if(components[i].id===id)return components[i];}return null;}
function renderSteps(){stepsList.innerHTML='';components.forEach(function(c){var li=document.createElement('li');li.dataset.id=c.id;li.textContent=c.name+' - '+c.sublabel;li.tabIndex=0;li.addEventListener('click',function(){selectNode(c.id);});li.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(c.id);}});stepsList.appendChild(li);});}
function animateDiagram(){var start=performance.now();function frame(now){if(!animating){rafId=null;return;}var dt=(now-start)/1000*speed;t=(t+dt)%1;flowDots.forEach(function(d){d.el.setAttribute('cx',d.sx+(d.ex-d.sx)*t);d.el.setAttribute('cy',d.sy+(d.ey-d.sy)*t);d.el.setAttribute('r',4);});rafId=requestAnimationFrame(frame);}rafId=requestAnimationFrame(frame);}
function setupControls(){themeBtn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem('consica-theme',theme);});playBtn.addEventListener('click',function(){animating=!animating;if(animating){playBtn.innerHTML='&#9646;&#9646;';animateDiagram();}else{playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});resetBtn.addEventListener('click',function(){t=0;flowDots.forEach(function(d){d.el.setAttribute('r',0);});if(animating){animating=false;playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});speedSlider.addEventListener('input',function(){speed=parseFloat(this.value);speedVal.textContent=speed+'x';});document.addEventListener('keydown',function(e){if(e.key==='Escape'){challengeOverlay.classList.add('hidden');completionOverlay.classList.add('hidden');}});}
function setupChallenge(){challengeBtn.addEventListener('click',function(){openChallenge();});challengeClose.addEventListener('click',function(){challengeOverlay.classList.add('hidden');});completionClose.addEventListener('click',function(){completionOverlay.classList.add('hidden');challengeOverlay.classList.add('hidden');});}
function openChallenge(){challengeState.questions=challenges.slice().sort(function(){return Math.random()-0.5;}).slice(0,5);challengeState.current=0;challengeState.answers={};challengeState.submitted=false;challengeOverlay.classList.remove('hidden');renderQuestion();}
function renderQuestion(){var q=challengeState.questions[challengeState.current];if(!q){finishChallenge();return;}var html='<div class="question"><div class="question-text">'+(challengeState.current+1)+'. '+q.q+'</div><div class="options">';q.o.forEach(function(opt,i){var sel=challengeState.answers[challengeState.current]===i?' selected':'';var cls=challengeState.submitted?(i===q.a?' correct':(challengeState.answers[challengeState.current]===i?' wrong':'')):'';html+='<label class="option-label'+sel+cls+'"><input type="radio" name="q'+challengeState.current+'" value="'+i+'"'+(challengeState.submitted?' disabled':'')+(sel?' checked':'')+' onchange="('+selectOption.toString()+')('+challengeState.current+','+i+')">'+opt+'</label>';});html+='</div></div>';html+='<div class="challenge-actions">';if(!challengeState.submitted){html+='<button class="btn-primary" onclick="('+submitChallenge.toString()+')()">Submit Answer</button>';}else{if(challengeState.current<challengeState.questions.length-1){html+='<button class="btn-primary" onclick="('+nextQuestion.toString()+')()">Next Question</button>';}else{html+='<button class="btn-primary" onclick="('+finishChallenge.toString()+')()">See Results</button>';}}html+='</div>';challengeBody.innerHTML=html;}
function selectOption(qIdx,optIdx){if(challengeState.submitted)return;challengeState.answers[qIdx]=optIdx;renderQuestion();}
function submitChallenge(){challengeState.submitted=true;renderQuestion();}
function nextQuestion(){challengeState.current++;challengeState.submitted=false;renderQuestion();}
function finishChallenge(){var correct=0,total=challengeState.questions.length;challengeState.questions.forEach(function(q,i){if(challengeState.answers[i]===q.a)correct++;});completionScore.textContent='You scored '+correct+'/'+total;completionOverlay.classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',init);
if(document.readyState==='complete'||document.readyState==='interactive')init();
})();
