(function(){'use strict';
try{
var components=[
{id:"client",name:"Client/Browser",purpose:"The user's device that runs frontend code and renders the interface",desc:"The client is the device and software that displays the app — a browser or mobile runtime. It handles rendering UI, capturing input, and communicating with servers.",how:"Clients run frontend code (HTML/CSS/JS for web, Swift/Kotlin for mobile). They handle rendering via DOM or native APIs, manage local state, cache data, and make HTTP requests to backend servers.",why:"The client is where users experience the app — performance and responsiveness here directly impact user satisfaction.",analogy:"Like a television that displays the broadcast for you to watch",fun:"There are over 4,000 different browser versions in use worldwide",takeaway:"The client runs frontend code and provides the user-facing interface for the application.",mistake:"A client isn't just a browser — mobile apps, desktop apps, and IoT devices are all clients too."},
{id:"frontend",name:"Frontend Code",purpose:"The code that runs in the browser to create the UI and handle interactions",desc:"Frontend code includes HTML for structure, CSS for styling, and JavaScript for behavior. It creates everything the user sees and interacts with.",how:"Frontend code is organized into components that encapsulate markup, style, and logic. Frameworks like React manage the virtual DOM for efficient updates. JavaScript handles events, API calls, and state management.",why:"Frontend code creates the direct user experience — it's what users think of when they use an app.",analogy:"Like the interior design and controls of a building that occupants directly use",fun:"Frontend development is the fastest-growing area of software engineering",takeaway:"Frontend code runs on the client and creates the complete user experience.",mistake:"Frontend isn't just visual design — it includes complex state management, routing, and API integration."},
{id:"network",name:"Network/Internet",purpose:"The communication channel that transmits data between client and server",desc:"The network is the infrastructure that carries HTTP requests and responses between the client and backend server across the internet.",how:"Data is broken into packets, routed through ISPs and network infrastructure using TCP/IP, reassembled at the destination. TLS encryption secures the channel. DNS resolves domain names to IP addresses.",why:"Without the network, clients and servers would be isolated — the network connects the frontend to the backend.",analogy:"Like a postal service that delivers letters between different locations",fun:"Internet traffic reaches speeds of over 400 Tbps on major backbone routes",takeaway:"The network enables communication between client and server, making web applications possible.",mistake:"Network latency is often underestimated — optimize API calls, use caching, and minimize payload sizes."},
{id:"backend",name:"Backend Server",purpose:"The server-side code that processes requests, runs business logic, and manages data",desc:"The backend server receives requests from the frontend, applies business logic, interacts with databases, and returns responses to the client.",how:"Backend servers use languages like Node.js, Python, or Java with frameworks like Express, Django, or Spring. They handle routing, middleware, authentication, and database operations through well-defined APIs.",why:"The backend provides the intelligence and data persistence that frontends depend on to function meaningfully.",analogy:"Like a restaurant kitchen where food is prepared based on orders from the front of house",fun:"A single backend server can handle millions of concurrent connections with proper architecture",takeaway:"Backend servers process requests, run business logic, and manage data — the powerhouse behind the UI.",mistake:"Backend code must handle errors gracefully — unhandled exceptions can crash the entire server."},
{id:"database",name:"Database",purpose:"Stores and retrieves structured data persistently for the application",desc:"Databases persistently store all application data — user accounts, content, transactions, and settings — across multiple sessions and users.",how:"The backend queries databases using SQL or through ORM abstractions. Data is organized in tables (SQL) or documents (NoSQL). Indexes speed up lookups, and transactions ensure data consistency.",why:"Databases provide the durable memory that makes applications useful across sessions and for multiple users simultaneously.",analogy:"Like a library that catalogs and stores books for easy retrieval",fun:"The largest databases contain over 100 petabytes of data",takeaway:"Databases provide persistent storage that outlives individual application sessions.",mistake:"Database queries should be optimized with indexes — unoptimized queries are a leading cause of app slowdowns."},
{id:"fullstack",name:"Full Stack",purpose:"The combination of frontend and backend working together as a complete application",desc:"Full stack development encompasses both frontend and backend — understanding how all layers from UI to database work together to deliver a complete application.",how:"Full stack developers work across the entire tech stack: designing APIs, building UI components, writing server logic, managing databases, and deploying infrastructure. They understand how data flows through every layer.",why:"Full stack understanding enables developers to make better architectural decisions and build more cohesive applications.",analogy:"Like an architect who understands both the visible design and the structural engineering of a building",fun:"Full stack developers are among the most sought-after professionals in tech",takeaway:"Full stack development means understanding and working across both frontend and backend systems.",mistake:"Being full stack doesn't mean mastering everything — it means understanding enough to make good system-wide decisions."}
];
var nodes=[{id:"client",x:60,y:80,w:130,h:50,color:"#0891b2",icon:"🖥"},{id:"frontend",x:240,y:80,w:130,h:50,color:"#0959C8",icon:"🎨"},{id:"network",x:150,y:200,w:130,h:50,color:"#d97706",icon:"🌐"},{id:"backend",x:320,y:310,w:130,h:50,color:"#7c3aed",icon:"⚙"},{id:"database",x:150,y:310,w:130,h:50,color:"#059669",icon:"💾"},{id:"fullstack",x:420,y:200,w:130,h:50,color:"#dc2626",icon:"🔗"}];
var connections=[{from:"client",to:"frontend"},{from:"frontend",to:"network"},{from:"network",to:"backend"},{from:"backend",to:"database"},{from:"database",to:"backend"},{from:"backend",to:"network"},{from:"network",to:"frontend"},{from:"frontend",to:"client"},{from:"frontend",to:"fullstack"},{from:"backend",to:"fullstack"}];
var quiz=[
{q:"What runs on the client side of a web application?",opts:["Only the database","Only the server code","HTML, CSS, and JavaScript","Only network configuration"],ans:2},
{q:"What is the primary role of the backend server?",opts:["Display web pages","Style HTML elements","Process requests, run business logic, and manage data","Handle DNS lookups"],ans:2},
{q:"How does the frontend communicate with the backend?",opts:["Through direct database connections","Via the network using HTTP requests","Through file sharing","Using Bluetooth"],ans:1},
{q:"What does a full stack developer work with?",opts:["Only frontend technologies","Only backend technologies","Both frontend and backend systems","Only databases"],ans:2},
{q:"What is a common mistake about frontend development?",opts:["It's easy to learn","It only involves visual design","It doesn't use frameworks","It doesn't require testing"],ans:1},
{q:"Why is network latency important in frontend/backend architecture?",opts:["It doesn't affect performance","It directly impacts user experience and response times","It only matters for the database","It only matters for mobile apps"],ans:1}
];
var app=document.getElementById('app'),skeleton=document.getElementById('skeleton'),errorBoundary=document.getElementById('error-boundary'),errorMsg=document.getElementById('error-message'),container=document.getElementById('diagram-container'),infoPanel=document.getElementById('info-panel'),infoContent=document.getElementById('info-content'),speedSlider=document.getElementById('speed-slider'),speedVal=document.getElementById('speed-val'),playBtn=document.getElementById('play-btn'),challengeSection=document.getElementById('challenge-section'),challengeQuestions=document.getElementById('challenge-questions'),challengeResult=document.getElementById('challenge-result'),completionOverlay=document.getElementById('completion-overlay'),completionScore=document.getElementById('completion-score'),completionMsg=document.getElementById('completion-msg'),challengeBtn=document.getElementById('challenge-btn'),themeToggle=document.getElementById('theme-toggle');
var t=0,playing=true,selectedId=null,theme=localStorage.getItem('consica-theme')||'dark',speed=1;
var animId=null,svg=null,flowDots=[];

function setTheme(t){document.documentElement.setAttribute('data-theme',t==='light'?'light':'');localStorage.setItem('consica-theme',t);theme=t}
function toggleTheme(){setTheme(theme==='dark'?'light':'dark')}
setTheme(theme);

function buildSVG(){
var W=620,H=420,ns='http://www.w3.org/2000/svg';
svg=document.createElementNS(ns,'svg');
svg.setAttribute('viewBox','0 0 '+W+' '+H);svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.setAttribute('role','img');svg.setAttribute('aria-label','Frontend vs Backend diagram');
var defs=document.createElementNS(ns,'defs');
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10" fill="var(--accent2, #3b82f6)"/></marker><linearGradient id="bg-grad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="var(--surface, #131b2e)"/><stop offset="100%" stop-color="var(--surface2, #1a2338)"/></linearGradient>';
svg.appendChild(defs);
var bg=document.createElementNS(ns,'rect');bg.setAttribute('width',W);bg.setAttribute('height',H);bg.setAttribute('fill','url(#bg-grad)');bg.setAttribute('rx','12');svg.appendChild(bg);
var zones=[
{label:"Frontend (Client Side)",x:50,y:60,w:240,h:100,color:"rgba(9,89,200,.08)"},
{label:"Network",x:140,y:185,w:200,h:75,color:"rgba(217,119,6,.08)"},
{label:"Backend (Server Side)",x:140,y:285,w:240,h:100,color:"rgba(124,58,237,.08)"}
];
zones.forEach(function(z){
var r=document.createElementNS(ns,'rect');r.setAttribute('x',z.x);r.setAttribute('y',z.y);r.setAttribute('width',z.w);r.setAttribute('height',z.h);r.setAttribute('fill',z.color);r.setAttribute('rx','8');r.setAttribute('stroke','var(--border)');r.setAttribute('stroke-width','1');svg.appendChild(r);
var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',z.x+10);lbl.setAttribute('y',z.y+18);lbl.setAttribute('fill','var(--text2)');lbl.setAttribute('font-size','10');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.textContent=z.label;svg.appendChild(lbl);
});
connections.forEach(function(c){
var from=nodes.find(function(n){return n.id===c.from});var to=nodes.find(function(n){return n.id===c.to});if(!from||!to)return;
var x1=from.x+from.w/2,y1=from.y+from.h/2,x2=to.x+to.w/2,y2=to.y+to.h/2;
var dx=x2-x1,dy=y2-y1,dist=Math.sqrt(dx*dx+dy*dy);
var mx=from.w/2+4,my=from.h/2+4,sx=x1+(dx/dist)*mx,sy=y1+(dy/dist)*my,ex=x2-(dx/dist)*mx,ey=y2-(dy/dist)*my;
var line=document.createElementNS(ns,'line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',ex);line.setAttribute('y2',ey);line.setAttribute('stroke','var(--accent2)');line.setAttribute('stroke-width','2');line.setAttribute('opacity','0.4');line.setAttribute('marker-end','url(#arrow)');svg.appendChild(line);
var dot=document.createElementNS(ns,'circle');dot.setAttribute('r','4');dot.setAttribute('fill','var(--accent2)');dot.setAttribute('opacity','0.8');dot.setAttribute('class','flow-dot');svg.appendChild(dot);
flowDots.push({el:dot,sx:sx,sy:sy,ex:ex,ey:ey,progress:Math.random()});
});
nodes.forEach(function(n){
var g=document.createElementNS(ns,'g');g.setAttribute('class','node-clickable');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',components.find(function(c){return c.id===n.id}).name);g.setAttribute('data-id',n.id);
var rect=document.createElementNS(ns,'rect');rect.setAttribute('x',n.x);rect.setAttribute('y',n.y);rect.setAttribute('width',n.w);rect.setAttribute('height',n.h);rect.setAttribute('rx','8');rect.setAttribute('fill',n.color);rect.setAttribute('opacity','0.9');rect.setAttribute('class','node-bg');g.appendChild(rect);
var icon=document.createElementNS(ns,'text');icon.setAttribute('x',n.x+16);icon.setAttribute('y',n.y+n.h/2+6);icon.setAttribute('font-size','18');icon.setAttribute('text-anchor','middle');icon.textContent=n.icon;g.appendChild(icon);
var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',n.x+30);lbl.setAttribute('y',n.y+n.h/2+5);lbl.setAttribute('fill','#fff');lbl.setAttribute('font-size','11');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.setAttribute('class','node-label');lbl.textContent=components.find(function(c){return c.id===n.id}).name;g.appendChild(lbl);
g.addEventListener('click',function(){selectNode(n.id);});
g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(n.id);}});
svg.appendChild(g);
});
container.innerHTML='';container.appendChild(svg);
}
function selectNode(id){selectedId=id;var comp=components.find(function(c){return c.id===id});if(!comp)return;infoPanel.hidden=false;var html='<h3>'+comp.name+'</h3><div class="info-tags"><span class="info-tag">Purpose</span></div><p><strong>🎯 Purpose:</strong> '+comp.purpose+'</p><h4>📝 Description</h4><p>'+comp.desc+'</p><h4>⚙️ How It Works</h4><p>'+comp.how+'</p><h4>💡 Why It Matters</h4><p>'+comp.why+'</p><h4>🔗 Analogy</h4><p>'+comp.analogy+'</p><h4>🎲 Fun Fact</h4><p>'+comp.fun+'</p><h4>✅ Key Takeaway</h4><p>'+comp.takeaway+'</p><h4>⚠️ Common Mistake</h4><p>'+comp.mistake+'</p>';infoContent.innerHTML=html;infoPanel.scrollIntoView({behavior:'smooth',block:'nearest'});container.querySelectorAll('.node-clickable').forEach(function(g){if(g.getAttribute('data-id')===id)g.classList.add('node-active');else g.classList.remove('node-active');});}
function closeInfo(){infoPanel.hidden=true;selectedId=null;container.querySelectorAll('.node-active').forEach(function(g){g.classList.remove('node-active');});}
function togglePlay(){playing=!playing;playBtn.textContent=playing?'⏸ Pause':'▶ Play';playBtn.setAttribute('aria-label',playing?'Pause':'Play');}
speedSlider.addEventListener('input',function(){var v=parseInt(speedSlider.value);speed=0.25+((v/16)*3.75);speedVal.textContent=speed.toFixed(2)+'×';});
function animate(ts){if(!ts)ts=0;if(playing){t+=0.016*speed;flowDots.forEach(function(dot){dot.progress+=0.008*speed;if(dot.progress>1)dot.progress=0;var p=dot.progress;dot.el.setAttribute('cx',dot.sx+(dot.ex-dot.sx)*p);dot.el.setAttribute('cy',dot.sy+(dot.ey-dot.sy)*p);});}animId=requestAnimationFrame(animate);}
function buildChallenge(){challengeQuestions.innerHTML='';quiz.forEach(function(q,idx){var b=document.createElement('div');b.className='question-block';b.innerHTML='<h3>'+(idx+1)+'. '+q.q+'</h3>';q.opts.forEach(function(o,i){b.innerHTML+='<div class="q-option"><input type="radio" name="q'+idx+'" id="q'+idx+'_'+i+'" value="'+i+'"><label for="q'+idx+'_'+i+'">'+o+'</label></div>';});challengeQuestions.appendChild(b);});challengeBtn.hidden=false;}
function submitChallenge(){var score=0,total=quiz.length;quiz.forEach(function(q,idx){var sel=document.querySelector('input[name="q'+idx+'"]:checked');var blocks=document.querySelectorAll('.question-block');var opts=blocks[idx].querySelectorAll('.q-option');opts.forEach(function(o){o.classList.remove('correct','wrong');});var fb=blocks[idx].querySelector('.q-feedback');if(fb)fb.remove();if(sel){var val=parseInt(sel.value);if(val===q.ans){opts[q.ans].classList.add('correct');score++;}else{opts[q.ans].classList.add('correct');opts[val].classList.add('wrong');}}else{opts[q.ans].classList.add('correct');}var fbDiv=document.createElement('div');fbDiv.className='q-feedback '+(sel&&parseInt(sel.value)===q.ans?'correct':'wrong');fbDiv.textContent=sel&&parseInt(sel.value)===q.ans?'✓ Correct!':'✗ The correct answer was option '+(q.ans+1);blocks[idx].appendChild(fbDiv);});challengeResult.hidden=false;var pct=Math.round(score/total*100);challengeResult.innerHTML='<h3>Score: '+score+'/'+total+' ('+pct+'%)</h3><p>'+(pct>=80?'Great job! You understand the frontend/backend relationship.':pct>=50?'Good start! Review the nodes to learn more.':'Keep exploring — click each node to learn about frontend vs backend.')+'</p>';if(pct>=80){completionOverlay.hidden=false;completionScore.textContent='You scored '+score+'/'+total+' ('+pct+'%)';completionMsg.textContent='You have a solid understanding of how frontend and backend work together to power modern applications!';}}
function closeCompletion(){completionOverlay.hidden=true;}
function showChallenge(){challengeSection.hidden=!challengeSection.hidden;if(!challengeSection.hidden)challengeSection.scrollIntoView({behavior:'smooth'});}
function init(){buildSVG();buildChallenge();animId=requestAnimationFrame(animate);challengeBtn.hidden=false;setTimeout(function(){skeleton.style.opacity='0';skeleton.style.transition='opacity .4s';setTimeout(function(){skeleton.hidden=true;},400);app.hidden=false;},600);}
init();
window.addEventListener('unload',function(){if(animId)cancelAnimationFrame(animId);});
window.selectNode=selectNode;window.closeInfo=closeInfo;window.togglePlay=togglePlay;window.toggleTheme=toggleTheme;window.showChallenge=showChallenge;window.submitChallenge=submitChallenge;window.closeCompletion=closeCompletion;
}catch(e){document.getElementById('skeleton').hidden=true;var eb=document.getElementById('error-boundary');eb.hidden=false;document.getElementById('error-message').textContent=e.message||'Failed to initialize diagram';console.error('Diagram init error:',e);}
})();