(function(){'use strict';
const STORE='consica-theme';
const nodes=[{id:'browser',name:'Browser',desc:'The user types a domain name (e.g., example.com) into the browser. The browser first checks its local DNS cache.',details:'Function: Initiates DNS query\nCache: Browser DNS cache\nProtocol: Stub resolver\nNext: Recursive Resolver'},{id:'resolver',name:'Recursive Resolver',desc:'The resolver checks its cache. If not found, it queries the DNS hierarchy starting from root servers. Typically ISP-managed.',details:'Function: Recursive query\nCache: OS/DNS cache\nAlso known as: Recursive DNS\nProvider: ISP or 8.8.8.8'},{id:'root',name:'Root Server',desc:'Root servers (13 logical clusters globally) respond with referrals to TLD nameservers for the appropriate top-level domain.',details:'Number: 13 clusters (many instances)\nManaged by: ICANN\nResponse: TLD referral\nAnycast: Yes'},{id:'tld',name:'TLD Server (.com)',desc:'Top-Level Domain servers for .com (Verisign) respond with the authoritative nameserver for the domain.',details:'Example: .com, .org, .net\nOperator: Verisign (.com)\nResponse: Auth NS referral\nZone: Top-level domain zone'},{id:'auth',name:'Authoritative Nameserver',desc:'The authoritative server holds the actual DNS records for the domain. It returns the IP address (A/AAAA record).',details:'Function: Authoritative answer\nRecords: A, AAAA, CNAME, MX, NS\nSource: Domain registrar\nTTL: Configurable'},{id:'A',name:'A Record',desc:'An A record maps a domain name to an IPv4 address. The most fundamental DNS record type.',details:'Type: A\nPurpose: IPv4 mapping\nExample: example.com → 93.184.216.34\nFormat: 32-bit address'}];
const questions=[{q:'What is the first step in DNS resolution?',opts:['Check root server','Check browser cache','Query TLD','Contact auth NS'],ans:1},{q:'How many root server clusters exist?',opts:['7','13','21','26'],ans:1},{q:'Which DNS record maps a domain to an IPv4 address?',opts:['AAAA','CNAME','A','MX'],ans:2},{q:'Who manages the .com TLD?',opts:['ICANN','Verisign','Google','Cloudflare'],ans:1},{q:'What is the role of a recursive resolver?',opts:['Store zone files','Cache and forward queries','Register domains','Assign IPs'],ans:1},{q:'What does a CNAME record do?',opts:['Maps to IPv6','Mail server mapping','Creates an alias','Delegates authority'],ans:2}];
let speed=1,playing=false,theme='dark',rAF=null,t=0;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupNodes();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}
function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}
function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}
function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';});}}
function setupNodes(){var all=nodes.slice();all.push({id:'AAAA',name:'AAAA Record',desc:'Maps a domain name to an IPv6 address. Four times more bits than A records.',details:'Type: AAAA\nPurpose: IPv6 mapping\nFormat: 128-bit address\nExample: 2606:2800:220:1:248:1893:25c8:1946'});all.push({id:'CNAME',name:'CNAME Record',desc:'Creates an alias from one domain to another. Used for subdomains like www → root domain.',details:'Type: CNAME\nPurpose: Domain alias\nExample: www.example.com → example.com\nLimitation: Cannot coexist with other record types'});all.push({id:'MX',name:'MX Record',desc:'Specifies mail servers responsible for accepting email on behalf of a domain.',details:'Type: MX\nPurpose: Mail routing\nPriority: Lower number = higher priority\nExample: mail.example.com'});all.push({id:'NS',name:'NS Record',desc:'Delegates a DNS zone to authoritative nameservers. Essential for distributed DNS management.',details:'Type: NS\nPurpose: Zone delegation\nExample: ns1.example.com\nRequired: At least 2 per zone'});all.forEach(function(n){var sel='[data-node="'+n.id+'"], [data-record="'+n.id+'"]';var els=document.querySelectorAll(sel);els.forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo(n);});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showInfo(n);}});});});document.addEventListener('click',function(e){if(!e.target.closest('[data-node]')&&!e.target.closest('[data-record]')&&!e.target.closest('.response-box')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}
function showInfo(node){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel)return;title.textContent=node.name;desc.textContent=node.desc;details.innerHTML='<p>'+node.details.split('\n').join('<br>')+'</p>';panel.hidden=false;}
function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}
function startRAF(){function frame(){if(playing){t+=0.02*speed;var p=document.getElementById('query-dot');if(p){var phases=[{x1:110,x2:830,y:122},{x1:830,x2:830,y1:78,y2:193}];var phase=Math.floor(t)%2;var frac=(t%1);if(phase===0){p.setAttribute('cx',110+(830-110)*frac);p.setAttribute('cy',122);}else{p.setAttribute('cx',830);p.setAttribute('cy',78+(193-78)*frac);}p.setAttribute('visibility','visible');}}rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}
function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';t=0;const p=document.getElementById('query-dot');if(p)p.setAttribute('visibility','hidden');const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}}
function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}
let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}
function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
