(function(){'use strict';
const STORE='consica-theme';
const layers=[{id:4,name:'Application',desc:'Provides network services directly to user applications. This is where protocols like HTTP, DNS, and FTP live.',details:'Protocols: HTTP, HTTPS, DNS, FTP, SMTP, SSH\nUnit: Data\nFunction: User-facing network services',pdu:'Data'},{id:3,name:'Transport',desc:'Manages end-to-end communication between hosts. TCP ensures reliable delivery; UDP provides faster, connectionless transmission.',details:'Protocols: TCP, UDP\nUnit: Segment\nFunction: End-to-end reliability & flow control',pdu:'Segment'},{id:2,name:'Internet',desc:'Handles logical addressing and routing of packets across networks. The IP protocol operates at this layer.',details:'Protocols: IP, ICMP, ARP\nUnit: Packet\nFunction: Addressing & routing',pdu:'Packet'},{id:1,name:'Network Access',desc:'Controls the physical transmission of data over network hardware. Combines OSI layers 1 and 2.',details:'Protocols: Ethernet, Wi-Fi, PPP\nUnit: Frame\nFunction: Physical transmission & MAC',pdu:'Frame'}];
const questions=[{q:'How many layers does the TCP/IP model have?',opts:['3','4','5','7'],ans:1},{q:'Which protocol operates at the Transport layer?',opts:['IP','HTTP','TCP','Ethernet'],ans:2},{q:'What is the PDU at the Internet layer?',opts:['Segment','Data','Frame','Packet'],ans:3},{q:'Which layer combines OSI layers 1 and 2?',opts:['Application','Transport','Internet','Network Access'],ans:3},{q:'What protocol is used at the Application layer for web browsing?',opts:['SMTP','FTP','HTTP','DNS'],ans:2},{q:'Which TCP/IP layer handles logical IP addressing?',opts:['Network Access','Internet','Transport','Application'],ans:1}];
let speed=1,playing=false,theme='dark',rAF=null,dotPos={x:450,y:100},dir=1,selectedLayer=null;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupLayers();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}
function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}
function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}
function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';});}}
function setupLayers(){layers.forEach(function(l){const rect=document.querySelector('.layer-box[data-layer="'+l.id+'"]');if(rect){rect.addEventListener('click',function(e){e.stopPropagation();showLayerInfo(l);});rect.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showLayerInfo(l);}});}});document.addEventListener('click',function(e){if(!e.target.closest('.layer-box')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}
function showLayerInfo(layer){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel)return;title.textContent='Layer: '+layer.name;desc.textContent=layer.desc;details.innerHTML='<p><strong>PDU:</strong> '+layer.pdu+'</p><p><strong>Protocols:</strong> '+layer.details.split('\n')[0].replace('Protocols: ','')+'</p>';panel.hidden=false;document.querySelectorAll('.layer-box').forEach(function(r){r.classList.toggle('active',parseInt(r.getAttribute('data-layer'))===layer.id);});selectedLayer=layer.id;}
function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}
function startRAF(){function frame(){if(playing){dotPos.y+=1.2*speed;if(dotPos.y>580||dotPos.y<100)dir*=-1;dotPos.y+=dir*1.2*speed;const dot=document.getElementById('flow-dot');if(dot){dot.setAttribute('cx',dotPos.x);dot.setAttribute('cy',dotPos.y);dot.setAttribute('visibility','visible');}}rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}
function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';const dot=document.getElementById('flow-dot');if(dot)dot.setAttribute('visibility','hidden');dotPos.y=100;const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;document.querySelectorAll('.layer-box').forEach(function(r){r.classList.remove('active');});const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}selectedLayer=null;}
function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}
let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}
function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
