(function(){'use strict';
var components = [
  {id:"browser",name:"Web Browser",category:"Software",icon:"browser",shape:"circle",x:30,y:24,w:110,h:56,purpose:"Initiates the webpage request and renders the received content into a visual page",description:"The browser types the URL, sends the HTTP request, and then processes the returned HTML, CSS, and JavaScript to display the page.",why:"The browser is the starting point and the final display of every web journey",analogy:"Like a chef who orders ingredients and then prepares the meal",funFact:"Modern browsers run multiple processes for security\u2014one tab crash doesn\\'t take down others",takeaway:"The browser orchestrates the entire process from request to display",mistake:"The browser doesn\\'t receive a complete page instantly\u2014it streams and renders progressively",descriptionDetailed:"The browser parses the URL, checks HSTS preload lists, and initiates a DNS query through the OS. It opens a TCP connection, performs a TLS handshake, and sends the HTTP request with headers. As the response streams in, the browser\\'s parser builds the DOM and CSSOM trees incrementally."},
  {id:"dnsserver",name:"DNS Server",category:"Network",icon:"globe",shape:"rounded-rect",x:235,y:24,w:110,h:56,purpose:"Resolves the domain name to an IP address so the browser knows where to connect",description:"DNS servers translate the human-readable domain into the server\\'s numeric IP address through a hierarchical lookup process.",why:"Without DNS, the browser wouldn\\'t know which server to connect to",analogy:"Like asking a directory service for a company\\'s address before visiting",funFact:"DNS resolution typically takes 20-120 milliseconds depending on caching",takeaway:"DNS is the very first step in every webpage request",mistake:"DNS doesn\\'t just handle forward lookups\u2014it also handles mail server discovery",descriptionDetailed:"The recursive resolver navigates the DNS hierarchy: root, TLD, and authoritative servers. Results are cached at each level according to TTL values. Modern DNS includes DNSSEC for validation and DNS-over-HTTPS for privacy."},
  {id:"cdn",name:"Content Delivery Network",category:"Network",icon:"cdn",shape:"rounded-rect",x:30,y:120,w:110,h:56,purpose:"Serves cached copies of website content from servers geographically close to the user",description:"CDNs store copies of static assets like images, CSS, and JavaScript at edge servers worldwide, delivering them from the nearest location to the user.",why:"CDNs dramatically reduce page load times by minimizing the distance data travels",analogy:"Like having local warehouses stocked with popular products instead of shipping everything from one central factory",funFact:"Cloudflare\\'s CDN serves about 20% of all websites on the Internet",takeaway:"CDNs make the web faster by putting content closer to users",mistake:"CDNs don\\'t replace the origin server\u2014they cache its content and reduce its load",descriptionDetailed:"CDN edge servers are deployed in hundreds of locations worldwide. When a user requests content, the CDN routes the request to the nearest edge server using anycast DNS. The edge server serves cached content or fetches from the origin on a cache miss."},
  {id:"origin",name:"Origin Server",category:"Software",icon:"server",shape:"cylinder",x:235,y:120,w:110,h:56,purpose:"Hosts the original, authoritative version of the website content",description:"The origin server is the primary server where the website\\'s files live and where application logic runs to generate dynamic content.",why:"The origin server is the definitive source of truth for all website content",analogy:"Like the main kitchen in a restaurant chain where all original recipes are developed",funFact:"Origin servers typically run behind load balancers and are never directly exposed to users",takeaway:"CDNs and caches all serve content originally sourced from the origin server",mistake:"The origin server doesn\\'t serve every request\u2014CDNs handle most of the traffic",descriptionDetailed:"The origin server runs web server software like Nginx or Apache, often behind a reverse proxy. Dynamic content is generated by application code. The origin also connects to databases and external APIs to assemble the final page."},
  {id:"tcp",name:"TCP Connection",category:"Network",icon:"cable",shape:"pill",x:30,y:216,w:110,h:56,purpose:"Establishes a reliable, ordered connection between browser and server for data exchange",description:"TCP uses a three-way handshake to establish a connection, then manages data flow, sequencing, and error recovery throughout the session.",why:"TCP ensures all webpage data arrives complete and in the correct order",analogy:"Like a phone call where both parties confirm they hear each other before talking",funFact:"TCP was designed to survive a nuclear war\u2014it was part of ARPANET\\'s survivability research",takeaway:"TCP provides reliable, ordered delivery that HTTP depends on",mistake:"TCP isn\\'t the only protocol\u2014UDP is faster but doesn\\'t guarantee delivery",descriptionDetailed:"The TCP three-way handshake: SYN, SYN-ACK, ACK. TCP uses sequence numbers to order packets and acknowledgment numbers to confirm receipt. The sliding window protocol manages flow control."},
  {id:"render",name:"Page Rendering",category:"Software",icon:"monitor",shape:"rounded-rect",x:235,y:216,w:110,h:56,purpose:"Converts HTML, CSS, and JavaScript into the visual webpage you see",description:"The rendering engine parses HTML to build a DOM tree, applies CSS styles, executes JavaScript, and paints pixels to the screen.",why:"Rendering is what transforms code into an interactive visual experience",analogy:"Like an architect\\'s blueprint being constructed into a physical building",funFact:"The first render can happen in as little as 50ms from receiving the HTML",takeaway:"Rendering is a complex multi-step process that happens progressively",mistake:"Rendering doesn\\'t wait for all resources\u2014it starts as soon as HTML is received",descriptionDetailed:"The browser builds the DOM tree from HTML tokens and the CSSOM from CSS rules. These are combined into the render tree. Layout calculates exact positions and sizes, then painting fills pixels. JavaScript execution blocks parsing but can be deferred."}
];
var connections = [{from:"browser",to:"dnsserver"},{from:"dnsserver",to:"cdn"},{from:"cdn",to:"origin"},{from:"origin",to:"tcp"},{from:"tcp",to:"render"}];
var steps = [{label:"Step 1: Web Browser",status:"Exploring: Web Browser - Initiates the webpage request and renders the received content into a visual page"},{label:"Step 2: DNS Server",status:"Exploring: DNS Server - Resolves the domain name to an IP address so the browser knows where to connect"},{label:"Step 3: Content Delivery Network",status:"Exploring: Content Delivery Network - Serves cached copies of website content from servers geographically close to the user"},{label:"Step 4: Origin Server",status:"Exploring: Origin Server - Hosts the original, authoritative version of the website content"},{label:"Step 5: TCP Connection",status:"Exploring: TCP Connection - Establishes a reliable, ordered connection between browser and server for data exchange"},{label:"Step 6: Page Rendering",status:"Exploring: Page Rendering - Converts HTML, CSS, and JavaScript into the visual webpage you see"}];
var tour = [{title:"Web Browser",description:"Initiates the webpage request and renders the received content into a visual page",componentId:"browser"},{title:"DNS Server",description:"Resolves the domain name to an IP address so the browser knows where to connect",componentId:"dnsserver"},{title:"Content Delivery Network",description:"Serves cached copies of website content from servers geographically close to the user",componentId:"cdn"},{title:"Origin Server",description:"Hosts the original, authoritative version of the website content",componentId:"origin"},{title:"TCP Connection",description:"Establishes a reliable, ordered connection between browser and server for data exchange",componentId:"tcp"},{title:"Page Rendering",description:"Converts HTML, CSS, and JavaScript into the visual webpage you see",componentId:"render"}];

deferInit(function(){
  new DiagramEngine({
    title: 'Webpage Journey',
    subtitle: 'How Internet Works',
    desc: 'Follow a webpage request from browser to CDN, origin server, and back.',
    components: components,
    connections: connections,
    steps: steps,
    tour: tour,
    packetFlow: [
      {label:'HTTP GET',color:'#22c55e'},
      {label:'DNS Resolve',color:'#60a5fa'},
      {label:'CDN Hit',color:'#c084fc'},
      {label:'Origin Fetch',color:'#f59e0b'},
      {label:'TCP Handshake',color:'#22c55e'}
    ],

    render: function(container, engine) {
      engine.buildVisual(container);
      engine._setStatus('Click any component to learn more');
    },

    animate: function(engine) {
      var svg = engine.el.visual.querySelector('svg');
      if (!svg || engine.selectedId || !engine.playing) return;
      var comps = svg.querySelectorAll('.component');
      var idx = Math.floor(engine.t * 0.5) % comps.length;
      comps.forEach(function(el, i) {
        var bg = el.querySelector('.component-bg');
        if (!bg) return;
        var shape = bg.querySelector(':scope > :first-child');
        if(!shape)return;
        shape.setAttribute('fill', i === idx ? '#1e2d50' : '#1a2235');
        shape.setAttribute('stroke', i === idx ? '#0959C8' : '#2a3a55');
      });
    },

    onReplay: function(engine) {
      engine.t = 0;
    }
  });
});
})();
