(function(){'use strict';
try{
var components=[
{id:"app",name:"Application",purpose:"The software that needs to store, retrieve, and manage data to function",desc:"Applications depend on databases to persist user data, state, content, and configuration. Every user action that creates or modifies data flows through a database.",how:"Apps connect to databases via drivers or ORMs using connection pools. They construct queries (SQL or API calls), send them to the database, process results, and handle errors. Transactions ensure data consistency across multiple operations.",why:"Applications need reliable data storage to provide meaningful functionality across sessions and users.",analogy:"Like a store that needs inventory management to track products and sales",fun:"Modern apps often use 3-5 different database technologies simultaneously for different needs",takeaway:"Applications rely on databases as their persistent memory system.",mistake:"Apps should never talk directly to databases in production — always use an API or backend layer."},
{id:"sql",name:"SQL Database",purpose:"Stores structured data in tables with predefined schemas and relationships",desc:"SQL databases use Structured Query Language to define schemas, insert data, and run complex queries across related tables with joins and transactions.",how:"Relational databases store data in tables with rows and columns. Primary keys uniquely identify rows; foreign keys establish relationships. ACID transactions ensure atomicity, consistency, isolation, and durability. Indexes speed up queries.",why:"SQL provides strong data integrity, relationships, and powerful querying for structured data with clear constraints.",analogy:"Like a well-organized spreadsheet with multiple sheets that reference each other through IDs",fun:"SQL was created in 1974 and is still the most widely used database query language",takeaway:"SQL databases excel at structured data with clear relationships and integrity requirements.",mistake:"SQL isn't just for simple lookups — it supports complex joins, subqueries, window functions, and full-text search."},
{id:"nosql",name:"NoSQL Database",purpose:"Stores unstructured or semi-structured data with flexible schemas for horizontal scaling",desc:"NoSQL databases handle data that doesn't fit neatly into tables — documents, graphs, key-value pairs, or wide columns. They scale horizontally across many servers.",how:"NoSQL databases use different data models: Document stores (MongoDB) store JSON-like documents; Key-value stores (Redis) use simple key lookups; Column stores (Cassandra) handle wide columns; Graph databases (Neo4j) model relationships.",why:"NoSQL databases provide flexibility, horizontal scalability, and performance for specific use cases like real-time analytics and content management.",analogy:"Like a flexible storage unit where you can store items of different shapes and sizes",fun:"The term 'NoSQL' was first used in 1998 for a relational database that didn't use SQL",takeaway:"NoSQL databases offer schema flexibility and horizontal scaling for diverse data types.",mistake:"NoSQL doesn't mean 'no relationships' — it means different approaches to handling data relationships."},
{id:"query",name:"Query Engine",purpose:"The mechanism for requesting, filtering, and manipulating data in a database",desc:"The query engine processes requests to retrieve, insert, update, or delete data. It optimizes query execution, uses indexes, and manages concurrent access.",how:"The query engine parses the query, optimizes it (choosing indexes, join orders), executes it by reading/writing data pages, and returns results. Query planners estimate costs and select efficient execution strategies.",why:"The query engine determines how fast your database operations run — it's the performance heart of the database.",analogy:"Like a librarian who knows exactly where every book is and the fastest way to find it",fun:"Modern query optimizers consider hundreds of possible execution plans before choosing one",takeaway:"The query engine optimizes and executes data operations for maximum performance.",mistake:"Poorly written queries are the #1 cause of database performance problems — use EXPLAIN to analyze them."},
{id:"cache",name:"Cache Layer",purpose:"Temporarily stores frequently accessed data in fast memory to reduce database load",desc:"Caching stores copies of frequently accessed data in fast, in-memory storage (like Redis or Memcached) to avoid repeated expensive database queries.",how:"The application checks the cache first (cache-aside pattern). If found (cache hit), data returns instantly. If not (cache miss), the app queries the database, stores the result in cache, and sets a TTL (time-to-live) for automatic expiration.",why:"Caching dramatically reduces database load and latency for frequently accessed data, improving application performance.",analogy:"Like keeping frequently used tools on your workbench instead of going to the tool shed each time",fun:"A well-tuned cache can serve responses in under 1 millisecond — 100x faster than a database query",takeaway:"Caching improves performance by storing frequent data in fast, in-memory storage.",mistake:"Cache invalidation is notoriously difficult — stale data can cause subtle application bugs."},
{id:"backup",name:"Backup & Recovery",purpose:"Creates and stores copies of database data to protect against data loss",desc:"Backups create point-in-time copies of database data that can be restored in case of data corruption, accidental deletion, hardware failure, or disaster.",how:"Backup strategies include full backups (complete copy), incremental backups (changes since last backup), and continuous archiving (WAL). Backups are stored redundantly, often in different geographic regions. Recovery point objectives (RPO) and recovery time objectives (RTO) define goals.",why:"Backups are the last line of defense against data loss — without them, data can be permanently destroyed.",analogy:"Like an insurance policy that lets you rebuild your house if it burns down",fun:"The 3-2-1 backup rule: 3 copies, 2 different media types, 1 off-site copy",takeaway:"Regular backups protect against data loss from corruption, failure, or disaster.",mistake:"A backup is only useful if you've tested restoring it — untested backups are false security."}
];
var nodes=[{id:"app",x:240,y:30,w:140,h:48,color:"#0959C8",icon:"📱"},{id:"sql",x:50,y:120,w:130,h:48,color:"#1565c0",icon:"📊"},{id:"nosql",x:230,y:120,w:130,h:48,color:"#d97706",icon:"📄"},{id:"query",x:410,y:120,w:130,h:48,color:"#7c3aed",icon:"🔍"},{id:"cache",x:140,y:220,w:130,h:48,color:"#059669",icon:"⚡"},{id:"backup",x:330,y:220,w:130,h:48,color:"#c62828",icon:"💿"}];
var connections=[{from:"app",to:"sql"},{from:"app",to:"nosql"},{from:"sql",to:"query"},{from:"nosql",to:"query"},{from:"app",to:"cache"},{from:"app",to:"backup"},{from:"cache",to:"sql"}];
var quiz=[
{q:"What is the main difference between SQL and NoSQL databases?",opts:["SQL is faster than NoSQL","SQL uses structured schemas with tables, NoSQL offers flexible schemas","NoSQL can't handle relationships","SQL doesn't support indexes"],ans:1},
{q:"What does ACID stand for in database transactions?",opts:["Atomicity, Consistency, Isolation, Durability","Automated, Compiled, Integrated, Distributed","Access, Control, Input, Data","Active, Concurrent, Independent, Durable"],ans:0},
{q:"What is the primary benefit of caching in a database architecture?",opts:["Permanently stores all data","Reduces database load by serving frequent data from fast memory","Replaces the need for a database","Increases query complexity"],ans:1},
{q:"Why might an application use both SQL and NoSQL databases?",opts:["It's not possible to use both","Different data types benefit from different storage approaches","SQL is better for all use cases","NoSQL can't store any structured data"],ans:1},
{q:"What is the 3-2-1 backup rule?",opts:["3 databases, 2 servers, 1 network","3 copies, 2 media types, 1 off-site copy","3 backups per day, 2 weeks retention, 1 location","3 users, 2 admins, 1 backup"],ans:1},
{q:"What does a query optimizer do?",opts:["Writes SQL queries automatically","Selects the most efficient execution plan","Creates database schemas","Manages user permissions"],ans:1}
];
var app=document.getElementById('app'),skeleton=document.getElementById('skeleton'),errorBoundary=document.getElementById('error-boundary'),errorMsg=document.getElementById('error-message'),container=document.getElementById('diagram-container'),infoPanel=document.getElementById('info-panel'),infoContent=document.getElementById('info-content'),speedSlider=document.getElementById('speed-slider'),speedVal=document.getElementById('speed-val'),playBtn=document.getElementById('play-btn'),challengeSection=document.getElementById('challenge-section'),challengeQuestions=document.getElementById('challenge-questions'),challengeResult=document.getElementById('challenge-result'),completionOverlay=document.getElementById('completion-overlay'),completionScore=document.getElementById('completion-score'),completionMsg=document.getElementById('completion-msg'),challengeBtn=document.getElementById('challenge-btn'),themeToggle=document.getElementById('theme-toggle');
var t=0,playing=true,selectedId=null,theme=localStorage.getItem('consica-theme')||'dark',speed=1;
var animId=null,svg=null,flowDots=[];
function setTheme(t){document.documentElement.setAttribute('data-theme',t==='light'?'light':'');localStorage.setItem('consica-theme',t);theme=t}
function toggleTheme(){setTheme(theme==='dark'?'light':'dark')}
setTheme(theme);
function buildSVG(){var W=620,H=320,ns='http://www.w3.org/2000/svg';svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 '+W+' '+H);svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.setAttribute('role','img');svg.setAttribute('aria-label','Databases diagram');
var defs=document.createElementNS(ns,'defs');defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10" fill="var(--accent2, #3b82f6)"/></marker><linearGradient id="bg-grad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="var(--surface, #131b2e)"/><stop offset="100%" stop-color="var(--surface2, #1a2338)"/></linearGradient>';svg.appendChild(defs);
var bg=document.createElementNS(ns,'rect');bg.setAttribute('width',W);bg.setAttribute('height',H);bg.setAttribute('fill','url(#bg-grad)');bg.setAttribute('rx','12');svg.appendChild(bg);
var zones=[{label:"Application Layer",x:30,y:15,w:560,h:75,color:"rgba(9,89,200,.08)"},{label:"Database Systems",x:30,y:100,w:560,h:82,color:"rgba(21,101,192,.06)"},{label:"Infrastructure",x:30,y:195,w:560,h:100,color:"rgba(5,150,105,.06)"}];
zones.forEach(function(z){var r=document.createElementNS(ns,'rect');r.setAttribute('x',z.x);r.setAttribute('y',z.y);r.setAttribute('width',z.w);r.setAttribute('height',z.h);r.setAttribute('fill',z.color);r.setAttribute('rx','8');r.setAttribute('stroke','var(--border)');r.setAttribute('stroke-width','1');svg.appendChild(r);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',z.x+10);lbl.setAttribute('y',z.y+18);lbl.setAttribute('fill','var(--text2)');lbl.setAttribute('font-size','10');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.textContent=z.label;svg.appendChild(lbl);});
connections.forEach(function(c){var from=nodes.find(function(n){return n.id===c.from});var to=nodes.find(function(n){return n.id===c.to});if(!from||!to)return;var x1=from.x+from.w/2,y1=from.y+from.h/2,x2=to.x+to.w/2,y2=to.y+to.h/2;var dx=x2-x1,dy=y2-y1,dist=Math.sqrt(dx*dx+dy*dy);var mx=from.w/2+4,my=from.h/2+4,sx=x1+(dx/dist)*mx,sy=y1+(dy/dist)*my,ex=x2-(dx/dist)*mx,ey=y2-(dy/dist)*my;var line=document.createElementNS(ns,'line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',ex);line.setAttribute('y2',ey);line.setAttribute('stroke','var(--accent2)');line.setAttribute('stroke-width','2');line.setAttribute('opacity','0.4');line.setAttribute('marker-end','url(#arrow)');svg.appendChild(line);var dot=document.createElementNS(ns,'circle');dot.setAttribute('r','4');dot.setAttribute('fill','var(--accent2)');dot.setAttribute('opacity','0.8');dot.setAttribute('class','flow-dot');svg.appendChild(dot);flowDots.push({el:dot,sx:sx,sy:sy,ex:ex,ey:ey,progress:Math.random()});});
nodes.forEach(function(n){var g=document.createElementNS(ns,'g');g.setAttribute('class','node-clickable');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',components.find(function(c){return c.id===n.id}).name);g.setAttribute('data-id',n.id);var rect=document.createElementNS(ns,'rect');rect.setAttribute('x',n.x);rect.setAttribute('y',n.y);rect.setAttribute('width',n.w);rect.setAttribute('height',n.h);rect.setAttribute('rx','8');rect.setAttribute('fill',n.color);rect.setAttribute('opacity','0.9');rect.setAttribute('class','node-bg');g.appendChild(rect);var icon=document.createElementNS(ns,'text');icon.setAttribute('x',n.x+16);icon.setAttribute('y',n.y+n.h/2+6);icon.setAttribute('font-size','18');icon.setAttribute('text-anchor','middle');icon.textContent=n.icon;g.appendChild(icon);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',n.x+30);lbl.setAttribute('y',n.y+n.h/2+5);lbl.setAttribute('fill','#fff');lbl.setAttribute('font-size','11');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.setAttribute('class','node-label');lbl.textContent=components.find(function(c){return c.id===n.id}).name;g.appendChild(lbl);g.addEventListener('click',function(){selectNode(n.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(n.id);}});svg.appendChild(g);});
container.innerHTML='';container.appendChild(svg);}
function selectNode(id){selectedId=id;var comp=components.find(function(c){return c.id===id});if(!comp)return;infoPanel.hidden=false;var html='<h3>'+comp.name+'</h3><div class="info-tags"><span class="info-tag">Purpose</span></div><p><strong>🎯 Purpose:</strong> '+comp.purpose+'</p><h4>📝 Description</h4><p>'+comp.desc+'</p><h4>⚙️ How It Works</h4><p>'+comp.how+'</p><h4>💡 Why It Matters</h4><p>'+comp.why+'</p><h4>🔗 Analogy</h4><p>'+comp.analogy+'</p><h4>🎲 Fun Fact</h4><p>'+comp.fun+'</p><h4>✅ Key Takeaway</h4><p>'+comp.takeaway+'</p><h4>⚠️ Common Mistake</h4><p>'+comp.mistake+'</p>';infoContent.innerHTML=html;infoPanel.scrollIntoView({behavior:'smooth',block:'nearest'});container.querySelectorAll('.node-clickable').forEach(function(g){if(g.getAttribute('data-id')===id)g.classList.add('node-active');else g.classList.remove('node-active');});}
function closeInfo(){infoPanel.hidden=true;selectedId=null;container.querySelectorAll('.node-active').forEach(function(g){g.classList.remove('node-active');});}
function togglePlay(){playing=!playing;playBtn.textContent=playing?'⏸ Pause':'▶ Play';playBtn.setAttribute('aria-label',playing?'Pause':'Play');}
speedSlider.addEventListener('input',function(){var v=parseInt(speedSlider.value);speed=0.25+((v/16)*3.75);speedVal.textContent=speed.toFixed(2)+'×';});
function animate(ts){if(!ts)ts=0;if(playing){t+=0.016*speed;flowDots.forEach(function(dot){dot.progress+=0.008*speed;if(dot.progress>1)dot.progress=0;var p=dot.progress;dot.el.setAttribute('cx',dot.sx+(dot.ex-dot.sx)*p);dot.el.setAttribute('cy',dot.sy+(dot.ey-dot.sy)*p);});}animId=requestAnimationFrame(animate);}
function buildChallenge(){challengeQuestions.innerHTML='';quiz.forEach(function(q,idx){var b=document.createElement('div');b.className='question-block';b.innerHTML='<h3>'+(idx+1)+'. '+q.q+'</h3>';q.opts.forEach(function(o,i){b.innerHTML+='<div class="q-option"><input type="radio" name="q'+idx+'" id="q'+idx+'_'+i+'" value="'+i+'"><label for="q'+idx+'_'+i+'">'+o+'</label></div>';});challengeQuestions.appendChild(b);});challengeBtn.hidden=false;}
function submitChallenge(){var score=0,total=quiz.length;quiz.forEach(function(q,idx){var sel=document.querySelector('input[name="q'+idx+'"]:checked');var blocks=document.querySelectorAll('.question-block');var opts=blocks[idx].querySelectorAll('.q-option');opts.forEach(function(o){o.classList.remove('correct','wrong');});var fb=blocks[idx].querySelector('.q-feedback');if(fb)fb.remove();if(sel){var val=parseInt(sel.value);if(val===q.ans){opts[q.ans].classList.add('correct');score++;}else{opts[q.ans].classList.add('correct');opts[val].classList.add('wrong');}}else{opts[q.ans].classList.add('correct');}var fbDiv=document.createElement('div');fbDiv.className='q-feedback '+(sel&&parseInt(sel.value)===q.ans?'correct':'wrong');fbDiv.textContent=sel&&parseInt(sel.value)===q.ans?'✓ Correct!':'✗ The correct answer was option '+(q.ans+1);blocks[idx].appendChild(fbDiv);});challengeResult.hidden=false;var pct=Math.round(score/total*100);challengeResult.innerHTML='<h3>Score: '+score+'/'+total+' ('+pct+'%)</h3><p>'+(pct>=80?'Excellent database knowledge!':pct>=50?'Good understanding! Review the database types.':'Keep exploring each database component to learn more.')+'</p>';if(pct>=80){completionOverlay.hidden=false;completionScore.textContent='You scored '+score+'/'+total+' ('+pct+'%)';completionMsg.textContent='You understand how databases work — from SQL and NoSQL to caching and backup strategies!';}}
function closeCompletion(){completionOverlay.hidden=true;}
function showChallenge(){challengeSection.hidden=!challengeSection.hidden;if(!challengeSection.hidden)challengeSection.scrollIntoView({behavior:'smooth'});}
function init(){buildSVG();buildChallenge();animId=requestAnimationFrame(animate);challengeBtn.hidden=false;setTimeout(function(){skeleton.style.opacity='0';skeleton.style.transition='opacity .4s';setTimeout(function(){skeleton.hidden=true;},400);app.hidden=false;},600);}
init();
window.addEventListener('unload',function(){if(animId)cancelAnimationFrame(animId);});
window.selectNode=selectNode;window.closeInfo=closeInfo;window.togglePlay=togglePlay;window.toggleTheme=toggleTheme;window.showChallenge=showChallenge;window.submitChallenge=submitChallenge;window.closeCompletion=closeCompletion;
}catch(e){document.getElementById('skeleton').hidden=true;var eb=document.getElementById('error-boundary');eb.hidden=false;document.getElementById('error-message').textContent=e.message||'Failed to initialize diagram';console.error('Diagram init error:',e);}
})();