(function(){'use strict';
const STORE='consica-theme';
const nodes=[{id:'192',name:'Network Octet (192)',desc:'The first octet (192) identifies the network portion. In classful addressing, 192.x.x.x is a Class C network.',details:'Range: 192.0.0.0 - 223.255.255.255\nDefault Mask: 255.255.255.0\nClass: C\nHosts per network: 254'},{id:'168',name:'Network Octet (168)',desc:'The second octet extends the network address. Together 192.168.x.x is a private IP range reserved for LANs.',details:'RFC 1918 Private Range\nRange: 192.168.0.0 - 192.168.255.255\nPurpose: Local networks\nNot routable on internet'},{id:'1',name:'Subnet Octet (1)',desc:'The third octet divides the network into smaller subnets. With /24, the third octet defines the subnet ID.',details:'Subnet Bits: 8\nSubnets Available: 256\nCIDR: /24\nSubnet Mask: 255.255.255.0'},{id:'0',name:'Host Octet (0)',desc:'The fourth octet identifies individual devices on the subnet. .0 is reserved as the network address.',details:'Usable Range: 1 - 254\nBroadcast: 255\nNetwork: 0\nMax Devices: 254'}];
const questions=[{q:'What does /24 in CIDR notation indicate?',opts:['24 subnets','24 bits for network','24 hosts','24 octets'],ans:1},{q:'Which IP range is reserved for private networks?',opts:['10.0.0.0/8','172.16.0.0/12','192.168.0.0/16','All of the above'],ans:3},{q:'How many usable host addresses in a /24 subnet?',opts:['254','256','255','252'],ans:0},{q:'What is the broadcast address for 192.168.1.0/24?',opts:['192.168.1.0','192.168.1.255','192.168.0.255','192.168.255.255'],ans:1},{q:'Which octet in 192.168.1.0/24 represents the host?',opts:['First','Second','Third','Fourth'],ans:3},{q:'What protocol manages IP address assignment?',opts:['DNS','DHCP','ARP','ICMP'],ans:1}];
let speed=1,playing=false,theme='dark',rAF=null,t=0;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupNodes();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}
function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}
function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}
function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';});}}
function setupNodes(){nodes.forEach(function(n){const el=document.querySelector('[data-octet="'+n.id+'"]');if(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo(n);});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showInfo(n);}});}});document.querySelectorAll('.router-box,.host-box,.info-card,.bit-box').forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();var label=this.querySelector('.card-label, .node-label, .bit-label');if(label){showSimple(label.textContent,this.getAttribute('aria-label')||label.textContent);}});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();var label=this.querySelector('.card-label, .node-label, .bit-label');if(label)showSimple(label.textContent,this.getAttribute('aria-label')||label.textContent);}});});document.addEventListener('click',function(e){if(!e.target.closest('[data-octet]')&&!e.target.closest('.router-box')&&!e.target.closest('.host-box')&&!e.target.closest('.info-card')&&!e.target.closest('.bit-box')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}
function showInfo(node){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel)return;title.textContent=node.name;desc.textContent=node.desc;details.innerHTML='<p>'+node.details.split('\n').join('<br>')+'</p>';panel.hidden=false;}
function showSimple(title,desc){const panel=document.getElementById('info-panel');const t=document.getElementById('info-title');const d=document.getElementById('info-desc');const dt=document.getElementById('info-details');if(!panel)return;t.textContent=title;d.textContent=desc;if(dt)dt.innerHTML='';panel.hidden=false;}
function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}
function startRAF(){function frame(){if(playing){t+=0.02*speed;var y1=340+Math.sin(t)*20;var y2=340+Math.cos(t+1)*20;var p1=document.getElementById('packet1');var p2=document.getElementById('packet2');if(p1){p1.setAttribute('cx',200+Math.sin(t*1.3)*30);p1.setAttribute('cy',y1);p1.setAttribute('visibility','visible');}if(p2){p2.setAttribute('cx',600+Math.cos(t*1.1)*30);p2.setAttribute('cy',y2);p2.setAttribute('visibility','visible');}}rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}
function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';t=0;document.getElementById('packet1').setAttribute('visibility','hidden');document.getElementById('packet2').setAttribute('visibility','hidden');const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}}
function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}
let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}
function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
