(function(){'use strict';
var theme=localStorage.getItem('consica-theme')||'dark';
document.documentElement.setAttribute('data-theme',theme);
var app,container,skeleton,errorBoundary,errorMsg,svgContainer,infoTitle,infoDesc,stepsList,playBtn,resetBtn,speedSlider,speedVal,themeBtn,challengeOverlay,challengeBody,challengeClose,completionOverlay,completionScore,completionClose,challengeBtn,rafId,animating=false,t=0,activeNode=null,nodes=[],flowDots=[],speed=1,challengeState={questions:[],current:0,answers:{},submitted:false};
var components=[
{id:'input',name:'Input Layer',sublabel:'Raw data enters',desc:'The input layer receives raw data - each neuron represents one feature or pixel value.',purpose:'Accept initial data into the network',how:'Each input neuron corresponds to one feature; no computation happens here',why:'The starting point for all neural computation',analogy:'Retina receiving light before the brain processes it',funFact:'An image of 28x28 pixels equals 784 input neurons',takeaway:'Input size equals number of features',mistake:'Unnormalized inputs slow down training dramatically'},
{id:'weights',name:'Weights & Biases',sublabel:'Connection strength',desc:'Each connection between neurons has a weight (importance) and each neuron has a bias (threshold).',purpose:'Determine the influence of each input on the output',how:'Weights multiply inputs; bias shifts the activation function',why:'Learning equals adjusting weights to minimize error',analogy:'Volume knobs controlling how much each input is heard',funFact:'GPT-4 has over 1 trillion weights',takeaway:'Weights store the network knowledge',mistake:'Random initial weights are required - zero weights prevent learning'},
{id:'sum',name:'Summation',sublabel:'Weighted sum',desc:'Neurons compute the weighted sum of all inputs plus bias - a single number representing the total input signal.',purpose:'Combine all input signals into one value',how:'z = w1*x1 + w2*x2 + ... + wn*xn + b',why:'Linear combination is the foundation before non-linear activation',analogy:'Adding up scores on a test with different point values',funFact:'Matrix multiplication (used here) is why GPUs excel at neural nets',takeaway:'The summation is pure linear algebra',mistake:'Without activation, stacked linear layers equal one linear layer'},
{id:'activation',name:'Activation Function',sublabel:'Non-linear decision',desc:'An activation function introduces non-linearity, allowing the network to learn complex patterns.',purpose:'Add non-linearity to the computation',how:'ReLU, sigmoid, or tanh transform the weighted sum into an output',why:'Non-linearity enables learning complex patterns',analogy:'A decision: Am I excited enough to react?',funFact:'ReLU (Rectified Linear Unit) is the most popular activation function',takeaway:'Activation functions make neural nets powerful',mistake:'Sigmoid activations can saturate and block gradient flow'},
{id:'hidden',name:'Hidden Layers',sublabel:'Deep computation',desc:'Hidden layers sit between input and output, progressively extracting higher-level features.',purpose:'Learn hierarchical features through depth',how:'Each layer transforms its input, passing the result to the next layer',why:'Deeper networks can represent more complex functions',analogy:'Assembly line where each station adds more refinement',funFact:'Deep learning refers to networks with many hidden layers',takeaway:'More layers equals more abstract representations',mistake:'Too many layers can cause vanishing gradients'},
{id:'output',name:'Output Layer',sublabel:'Final prediction',desc:'The output layer produces the network final prediction - a classification, regression value, or generated sequence.',purpose:'Produce the final result',how:'Softmax for classification, linear for regression, specialized for other tasks',why:'The output is what the network thinks',analogy:'The final answer written on an exam',funFact:'Softmax outputs sum to 1 - interpretable as probabilities',takeaway:'Output format depends on the task type',mistake:'Wrong output activation equals broken predictions'}
];
var connectionsData=[{from:'input',to:'weights'},{from:'weights',to:'sum'},{from:'sum',to:'activation'},{from:'activation',to:'hidden'},{from:'hidden',to:'output'}];
var stepsData=[
{id:'input',label:'Input Layer - raw features enter the network'},
{id:'weights',label:'Weights & Biases - connection strengths between neurons'},
{id:'sum',label:'Summation - weighted sum of all inputs plus bias'},
{id:'activation',label:'Activation Function - introduces non-linearity'},
{id:'hidden',label:'Hidden Layers - hierarchical feature extraction'},
{id:'output',label:'Output Layer - final prediction or classification'}
];
var challenges=[
{q:'What enables neural networks to learn complex, non-linear patterns?',o:['Having more inputs','Activation functions','Faster hardware','Larger datasets'],a:1},
{q:'Why are GPUs well-suited for neural networks?',o:['They consume less power','They excel at matrix multiplication','They have more memory','They run at higher clock speeds'],a:1},
{q:'What does the ReLU activation function do?',o:['Converts to binary output','Outputs input if positive, zero otherwise','Squashes output between -1 and 1','Makes output sum to 1'],a:1},
{q:'What problem can occur with very deep networks?',o:['They become too fast','Vanishing gradients - gradients become too small to learn','They use too little memory','They only work with images'],a:1},
{q:'What stores the learned knowledge in a neural network?',o:['The input data','The weights between neurons','The activation functions','The output layer'],a:1},
{q:'What does softmax do in the output layer?',o:['Makes outputs binary','Converts outputs to probabilities that sum to 1','Speeds up training','Adds non-linearity'],a:1}
];
function init(){app=document.getElementById('app');container=document.getElementById('diagram-container');skeleton=document.getElementById('loading-skeleton');errorBoundary=document.getElementById('error-boundary');errorMsg=document.getElementById('error-message');svgContainer=document.getElementById('svg-container');infoTitle=document.getElementById('info-title');infoDesc=document.getElementById('info-desc');stepsList=document.getElementById('steps-list');playBtn=document.getElementById('play-btn');resetBtn=document.getElementById('reset-btn');speedSlider=document.getElementById('speed-slider');speedVal=document.getElementById('speed-value');themeBtn=document.getElementById('theme-toggle');challengeOverlay=document.getElementById('challenge-overlay');challengeBody=document.getElementById('challenge-body');challengeClose=document.getElementById('challenge-close');completionOverlay=document.getElementById('completion-overlay');completionScore=document.getElementById('completion-score');completionClose=document.getElementById('completion-close');challengeBtn=document.getElementById('challenge-btn');
try{buildDiagram();setupControls();setupChallenge();showContainer();}catch(e){showError(e.message||'Failed to build diagram');}}
function showContainer(){skeleton.classList.add('hidden');container.classList.remove('hidden');}
function showError(msg){skeleton.classList.add('hidden');errorBoundary.classList.remove('hidden');errorMsg.textContent=msg;}
function buildDiagram(){var W=840,H=300;var svg=svgCreate('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':'Neural network flow: Input Layer through Output Layer'});svgContainer.appendChild(svg);
var defs=svgCreate('defs');svg.appendChild(defs);
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="var(--conn-stroke)"/></marker><marker id="arrowLight" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#94a3b8"/></marker>';
var positions={input:{x:70,y:150},weights:{x:210,y:150},sum:{x:350,y:150},activation:{x:490,y:150},hidden:{x:630,y:150},output:{x:770,y:150}};
connectionsData.forEach(function(c){var f=positions[c.from],t=positions[c.to];var line=svgCreate('line',{x1:f.x+70,y1:f.y,x2:t.x-70,y2:t.y,class:'connection-line','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});svg.appendChild(line);var fd=svgCreate('circle',{class:'flow-dot',cx:0,cy:0,r:0,fill:'var(--accent)'});svg.appendChild(fd);flowDots.push({el:fd,sx:f.x+70,sy:f.y,ex:t.x-70,ey:t.y});});
components.forEach(function(cp){var p=positions[cp.id];var g=svgCreate('g',{class:'node-g',tabIndex:0,role:'button','aria-label':cp.name+': '+cp.sublabel});g.dataset.id=cp.id;var rx=svgCreate('rect',{x:p.x-70,y:p.y-26,width:140,height:52,rx:26,class:'node-rect'});g.appendChild(rx);var lbl=svgCreate('text',{x:p.x,y:p.y-4,class:'node-label'});lbl.textContent=cp.name;g.appendChild(lbl);var slbl=svgCreate('text',{x:p.x,y:p.y+14,class:'node-sublabel'});slbl.textContent=cp.sublabel;g.appendChild(slbl);g.addEventListener('click',function(){selectNode(cp.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(cp.id);}});svg.appendChild(g);nodes.push({el:g,data:cp,pos:p});});
var selected=false;components.forEach(function(c){if(!selected){selectNode(c.id);selected=true;}});renderSteps();}
function svgCreate(tag,attrs){var el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(var k in attrs)el.setAttribute(k,attrs[k]);return el;}
function selectNode(id){activeNode=id;var cp=getComp(id);if(!cp)return;nodes.forEach(function(n){var r=n.el.querySelector('.node-rect');if(r)r.classList.toggle('active',n.data.id===id);});infoTitle.textContent=cp.name+' - '+cp.sublabel;infoDesc.innerHTML='<strong>Purpose:</strong> '+cp.purpose+'<br><br><strong>How it works:</strong> '+cp.how+'<br><br><strong>Why it matters:</strong> '+cp.why+'<br><br><strong>Analogy:</strong> '+cp.analogy+(cp.funFact?'<br><br><strong>Fun fact:</strong> '+cp.funFact:'')+'<br><br><strong>Key takeaway:</strong> '+cp.takeaway+'<br><br><strong>Common mistake:</strong> '+cp.mistake;var items=stepsList.querySelectorAll('li');items.forEach(function(li){li.classList.toggle('active',li.dataset.id===id);});}
function getComp(id){for(var i=0;i<components.length;i++){if(components[i].id===id)return components[i];}return null;}
function renderSteps(){stepsList.innerHTML='';components.forEach(function(c){var li=document.createElement('li');li.dataset.id=c.id;li.textContent=c.name+' - '+c.sublabel;li.tabIndex=0;li.addEventListener('click',function(){selectNode(c.id);});li.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(c.id);}});stepsList.appendChild(li);});}
function animateDiagram(){var start=performance.now();function frame(now){if(!animating){rafId=null;return;}var dt=(now-start)/1000*speed;t=(t+dt)%1;flowDots.forEach(function(d){d.el.setAttribute('cx',d.sx+(d.ex-d.sx)*t);d.el.setAttribute('cy',d.sy+(d.ey-d.sy)*t);d.el.setAttribute('r',4);});rafId=requestAnimationFrame(frame);}rafId=requestAnimationFrame(frame);}
function setupControls(){themeBtn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem('consica-theme',theme);});playBtn.addEventListener('click',function(){animating=!animating;if(animating){playBtn.innerHTML='&#9646;&#9646;';animateDiagram();}else{playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});resetBtn.addEventListener('click',function(){t=0;flowDots.forEach(function(d){d.el.setAttribute('r',0);});if(animating){animating=false;playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});speedSlider.addEventListener('input',function(){speed=parseFloat(this.value);speedVal.textContent=speed+'x';});document.addEventListener('keydown',function(e){if(e.key==='Escape'){challengeOverlay.classList.add('hidden');completionOverlay.classList.add('hidden');}});}
function setupChallenge(){challengeBtn.addEventListener('click',function(){openChallenge();});challengeClose.addEventListener('click',function(){challengeOverlay.classList.add('hidden');});completionClose.addEventListener('click',function(){completionOverlay.classList.add('hidden');challengeOverlay.classList.add('hidden');});}
function openChallenge(){challengeState.questions=challenges.slice().sort(function(){return Math.random()-0.5;}).slice(0,5);challengeState.current=0;challengeState.answers={};challengeState.submitted=false;challengeOverlay.classList.remove('hidden');renderQuestion();}
function renderQuestion(){var q=challengeState.questions[challengeState.current];if(!q){finishChallenge();return;}var html='<div class="question"><div class="question-text">'+(challengeState.current+1)+'. '+q.q+'</div><div class="options">';q.o.forEach(function(opt,i){var sel=challengeState.answers[challengeState.current]===i?' selected':'';var cls=challengeState.submitted?(i===q.a?' correct':(challengeState.answers[challengeState.current]===i?' wrong':'')):'';html+='<label class="option-label'+sel+cls+'"><input type="radio" name="q'+challengeState.current+'" value="'+i+'"'+(challengeState.submitted?' disabled':'')+(sel?' checked':'')+' onchange="('+selectOption.toString()+')('+challengeState.current+','+i+')">'+opt+'</label>';});html+='</div></div>';html+='<div class="challenge-actions">';if(!challengeState.submitted){html+='<button class="btn-primary" onclick="('+submitChallenge.toString()+')()">Submit Answer</button>';}else{if(challengeState.current<challengeState.questions.length-1){html+='<button class="btn-primary" onclick="('+nextQuestion.toString()+')()">Next Question</button>';}else{html+='<button class="btn-primary" onclick="('+finishChallenge.toString()+')()">See Results</button>';}}html+='</div>';challengeBody.innerHTML=html;}
function selectOption(qIdx,optIdx){if(challengeState.submitted)return;challengeState.answers[qIdx]=optIdx;renderQuestion();}
function submitChallenge(){challengeState.submitted=true;renderQuestion();}
function nextQuestion(){challengeState.current++;challengeState.submitted=false;renderQuestion();}
function finishChallenge(){var correct=0,total=challengeState.questions.length;challengeState.questions.forEach(function(q,i){if(challengeState.answers[i]===q.a)correct++;});completionScore.textContent='You scored '+correct+'/'+total;completionOverlay.classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',init);
if(document.readyState==='complete'||document.readyState==='interactive')init();
})();
