(function(){'use strict';
try{
var components=[
{id:"server",name:"Web Server",purpose:"Listens for incoming HTTP requests and routes them to appropriate handlers",desc:"A web server accepts HTTP requests from clients, processes them, and returns responses. It serves as the entry point for all backend communication.",how:"Servers like Nginx, Apache, or Node.js http module listen on ports 80/443. They parse requests, handle TLS termination, route to application code, manage load balancing, and return responses. Middleware chains process requests sequentially.",why:"The web server is the gatekeeper that receives and directs all client requests to the right backend services.",analogy:"Like a receptionist who greets visitors and directs them to the right department",fun:"The first web server, CERN httpd, was developed by Tim Berners-Lee in 1990",takeaway:"Web servers handle incoming requests, routing, and coordinate the backend response.",mistake:"Modern servers don't just serve files — they run application code, middleware, and manage complex routing."},
{id:"nodejs",name:"Node.js",purpose:"JavaScript runtime for server-side development with event-driven, non-blocking I/O",desc:"Node.js allows developers to use JavaScript on the server. Its event-driven architecture handles thousands of concurrent connections efficiently with a single thread.",how:"Node uses an event loop and callback queue for async operations. Express.js provides routing, middleware, and request handling. npm offers millions of packages. The V8 engine compiles JS to machine code for high performance.",why:"Node.js enables full-stack JavaScript development and excels at real-time applications and microservices.",analogy:"Like a highly efficient waiter who can take orders from many tables without getting confused",fun:"Node.js was created in 2009 by Ryan Dahl in just 6 months",takeaway:"Node.js brings JavaScript to the server with excellent performance for I/O-heavy applications.",mistake:"Node.js is single-threaded — CPU-intensive operations block the event loop and require worker threads."},
{id:"python",name:"Python",purpose:"A versatile backend language popular for web APIs, data processing, and automation",desc:"Python is a high-level, readable language widely used for backend development with frameworks like Django, Flask, and FastAPI.",how:"Python backends use WSGI/ASGI servers like Gunicorn and Uvicorn. Django provides ORM, admin panel, and auth. Flask offers lightweight flexibility. FastAPI provides async endpoints with automatic OpenAPI docs.",why:"Python's simplicity and massive ecosystem make it ideal for rapid backend development and data-heavy applications.",analogy:"Like a Swiss Army knife — versatile and useful for many different tasks",fun:"Python was named after Monty Python's Flying Circus, not the snake",takeaway:"Python is one of the most popular backend languages thanks to its readability and rich framework ecosystem.",mistake:"Python isn't slow by default — with async code and proper optimization it handles high traffic well."},
{id:"java",name:"Java",purpose:"Enterprise-grade backend language known for stability, performance, and scalability",desc:"Java is a compiled, object-oriented language widely used in enterprise applications for its performance, type safety, and mature ecosystem.",how:"Java backends run on the JVM with frameworks like Spring Boot (microservices) and Jakarta EE. Spring provides DI, AOP, security, and data access. Hibernate handles ORM. Build tools like Maven/Gradle manage dependencies.",why:"Java's stability, threading model, and tooling make it ideal for large-scale, high-throughput enterprise systems.",analogy:"Like a heavy-duty industrial machine built for continuous, reliable operation",fun:"Java runs on over 3 billion devices worldwide",takeaway:"Java is a battle-tested enterprise language with unparalleled stability and performance at scale.",mistake:"Java requires more boilerplate than modern languages — tools like Lombok and Kotlin help reduce verbosity."},
{id:"database",name:"Database",purpose:"Persistently stores and retrieves application data for backend services",desc:"Databases store all persistent data — user accounts, content, transactions. Backend code queries them to serve client requests and maintain application state.",how:"Backend code connects to databases using drivers or ORMs. SQL databases (PostgreSQL, MySQL) use structured queries with transactions. NoSQL databases (MongoDB, Redis) use document/key-value models. Connection pooling manages concurrent access.",why:"Databases provide the durable storage that backs every request and persists data across user sessions.",analogy:"Like a warehouse that stores inventory and tracks every item's location",fun:"PostgreSQL has been in active development for over 35 years",takeaway:"Databases are the persistent memory of backend systems, storing and retrieving data on demand.",mistake:"Always sanitize database inputs — SQL injection remains one of the most common security vulnerabilities."},
{id:"api",name:"API Gateway",purpose:"Central entry point that routes requests to the appropriate backend services",desc:"An API gateway sits between clients and backend services, handling routing, authentication, rate limiting, load balancing, and request/response transformation.",how:"The gateway receives all API calls, authenticates via API keys/JWT, checks rate limits, routes to appropriate microservices, aggregates responses, and handles cross-cutting concerns like logging and caching.",why:"API gateways simplify client code by providing a single endpoint and centralize security, monitoring, and traffic management.",analogy:"Like an airport control tower that directs all incoming and outgoing flights",fun:"Enterprise API gateways can process over 1 million requests per second",takeaway:"API gateways centralize routing, security, and traffic management for backend services.",mistake:"An API gateway isn't just a reverse proxy — it handles auth, throttling, logging, and transformation."}
];
var nodes=[{id:"server",x:240,y:40,w:140,h:48,color:"#0959C8",icon:"🖥"},{id:"nodejs",x:60,y:130,w:140,h:48,color:"#2e7d32",icon:"🟢"},{id:"python",x:240,y:130,w:140,h:48,color:"#1565c0",icon:"🐍"},{id:"java",x:420,y:130,w:140,h:48,color:"#c62828",icon:"☕"},{id:"database",x:240,y:220,w:140,h:48,color:"#059669",icon:"💾"},{id:"api",x:240,y:310,w:140,h:48,color:"#d97706",icon:"🔗"}];
var connections=[{from:"server",to:"nodejs"},{from:"server",to:"python"},{from:"server",to:"java"},{from:"server",to:"database"},{from:"nodejs",to:"api"},{from:"python",to:"api"},{from:"java",to:"api"},{from:"database",to:"api"}];
var quiz=[
{q:"What is the primary role of a web server?",opts:["Display web pages to users","Listen for HTTP requests and route them to handlers","Compile backend code","Manage database schemas"],ans:1},
{q:"What makes Node.js particularly good at handling many concurrent connections?",opts:["Multi-threading","Event-driven, non-blocking architecture","Built-in database","C++ compilation"],ans:1},
{q:"Which Python framework is known for providing a full-featured backend with built-in ORM and admin panel?",opts:["Flask","FastAPI","Django","Pyramid"],ans:2},
{q:"Why is Java commonly used in enterprise backend systems?",opts:["It's the newest language","Its stability, performance, and mature ecosystem","It has no boilerplate","It's only for mobile apps"],ans:1},
{q:"What does an API gateway handle besides routing?",opts:["HTML rendering","CSS styling","Authentication, rate limiting, and logging","DOM manipulation"],ans:2},
{q:"What is a common mistake when working with Node.js?",opts:["Using async/await","Putting CPU-intensive operations on the main thread","Installing npm packages","Using Express.js"],ans:1}
];
var app=document.getElementById('app'),skeleton=document.getElementById('skeleton'),errorBoundary=document.getElementById('error-boundary'),errorMsg=document.getElementById('error-message'),container=document.getElementById('diagram-container'),infoPanel=document.getElementById('info-panel'),infoContent=document.getElementById('info-content'),speedSlider=document.getElementById('speed-slider'),speedVal=document.getElementById('speed-val'),playBtn=document.getElementById('play-btn'),challengeSection=document.getElementById('challenge-section'),challengeQuestions=document.getElementById('challenge-questions'),challengeResult=document.getElementById('challenge-result'),completionOverlay=document.getElementById('completion-overlay'),completionScore=document.getElementById('completion-score'),completionMsg=document.getElementById('completion-msg'),challengeBtn=document.getElementById('challenge-btn'),themeToggle=document.getElementById('theme-toggle');
var t=0,playing=true,selectedId=null,theme=localStorage.getItem('consica-theme')||'dark',speed=1;
var animId=null,svg=null,flowDots=[];
function setTheme(t){document.documentElement.setAttribute('data-theme',t==='light'?'light':'');localStorage.setItem('consica-theme',t);theme=t}
function toggleTheme(){setTheme(theme==='dark'?'light':'dark')}
setTheme(theme);
function buildSVG(){var W=620,H=400,ns='http://www.w3.org/2000/svg';svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 '+W+' '+H);svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.setAttribute('role','img');svg.setAttribute('aria-label','Backend technologies diagram');
var defs=document.createElementNS(ns,'defs');defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10" fill="var(--accent2, #3b82f6)"/></marker><linearGradient id="bg-grad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="var(--surface, #131b2e)"/><stop offset="100%" stop-color="var(--surface2, #1a2338)"/></linearGradient>';svg.appendChild(defs);
var bg=document.createElementNS(ns,'rect');bg.setAttribute('width',W);bg.setAttribute('height',H);bg.setAttribute('fill','url(#bg-grad)');bg.setAttribute('rx','12');svg.appendChild(bg);
var zones=[{label:"Server Layer",x:30,y:25,w:560,h:78,color:"rgba(9,89,200,.08)"},{label:"Languages & Runtimes",x:30,y:110,w:560,h:80,color:"rgba(21,101,192,.06)"},{label:"Data Layer",x:30,y:200,w:560,h:75,color:"rgba(5,150,105,.06)"},{label:"API Layer",x:30,y:290,w:560,h:80,color:"rgba(217,119,6,.06)"}];
zones.forEach(function(z){var r=document.createElementNS(ns,'rect');r.setAttribute('x',z.x);r.setAttribute('y',z.y);r.setAttribute('width',z.w);r.setAttribute('height',z.h);r.setAttribute('fill',z.color);r.setAttribute('rx','8');r.setAttribute('stroke','var(--border)');r.setAttribute('stroke-width','1');svg.appendChild(r);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',z.x+10);lbl.setAttribute('y',z.y+18);lbl.setAttribute('fill','var(--text2)');lbl.setAttribute('font-size','10');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.textContent=z.label;svg.appendChild(lbl);});
connections.forEach(function(c){var from=nodes.find(function(n){return n.id===c.from});var to=nodes.find(function(n){return n.id===c.to});if(!from||!to)return;var x1=from.x+from.w/2,y1=from.y+from.h/2,x2=to.x+to.w/2,y2=to.y+to.h/2;var dx=x2-x1,dy=y2-y1,dist=Math.sqrt(dx*dx+dy*dy);var mx=from.w/2+4,my=from.h/2+4,sx=x1+(dx/dist)*mx,sy=y1+(dy/dist)*my,ex=x2-(dx/dist)*mx,ey=y2-(dy/dist)*my;var line=document.createElementNS(ns,'line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',ex);line.setAttribute('y2',ey);line.setAttribute('stroke','var(--accent2)');line.setAttribute('stroke-width','2');line.setAttribute('opacity','0.4');line.setAttribute('marker-end','url(#arrow)');svg.appendChild(line);var dot=document.createElementNS(ns,'circle');dot.setAttribute('r','4');dot.setAttribute('fill','var(--accent2)');dot.setAttribute('opacity','0.8');dot.setAttribute('class','flow-dot');svg.appendChild(dot);flowDots.push({el:dot,sx:sx,sy:sy,ex:ex,ey:ey,progress:Math.random()});});
nodes.forEach(function(n){var g=document.createElementNS(ns,'g');g.setAttribute('class','node-clickable');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',components.find(function(c){return c.id===n.id}).name);g.setAttribute('data-id',n.id);var rect=document.createElementNS(ns,'rect');rect.setAttribute('x',n.x);rect.setAttribute('y',n.y);rect.setAttribute('width',n.w);rect.setAttribute('height',n.h);rect.setAttribute('rx','8');rect.setAttribute('fill',n.color);rect.setAttribute('opacity','0.9');rect.setAttribute('class','node-bg');g.appendChild(rect);var icon=document.createElementNS(ns,'text');icon.setAttribute('x',n.x+16);icon.setAttribute('y',n.y+n.h/2+6);icon.setAttribute('font-size','18');icon.setAttribute('text-anchor','middle');icon.textContent=n.icon;g.appendChild(icon);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',n.x+30);lbl.setAttribute('y',n.y+n.h/2+5);lbl.setAttribute('fill','#fff');lbl.setAttribute('font-size','11');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.setAttribute('class','node-label');lbl.textContent=components.find(function(c){return c.id===n.id}).name;g.appendChild(lbl);g.addEventListener('click',function(){selectNode(n.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(n.id);}});svg.appendChild(g);});
container.innerHTML='';container.appendChild(svg);}
function selectNode(id){selectedId=id;var comp=components.find(function(c){return c.id===id});if(!comp)return;infoPanel.hidden=false;var html='<h3>'+comp.name+'</h3><div class="info-tags"><span class="info-tag">Purpose</span></div><p><strong>🎯 Purpose:</strong> '+comp.purpose+'</p><h4>📝 Description</h4><p>'+comp.desc+'</p><h4>⚙️ How It Works</h4><p>'+comp.how+'</p><h4>💡 Why It Matters</h4><p>'+comp.why+'</p><h4>🔗 Analogy</h4><p>'+comp.analogy+'</p><h4>🎲 Fun Fact</h4><p>'+comp.fun+'</p><h4>✅ Key Takeaway</h4><p>'+comp.takeaway+'</p><h4>⚠️ Common Mistake</h4><p>'+comp.mistake+'</p>';infoContent.innerHTML=html;infoPanel.scrollIntoView({behavior:'smooth',block:'nearest'});container.querySelectorAll('.node-clickable').forEach(function(g){if(g.getAttribute('data-id')===id)g.classList.add('node-active');else g.classList.remove('node-active');});}
function closeInfo(){infoPanel.hidden=true;selectedId=null;container.querySelectorAll('.node-active').forEach(function(g){g.classList.remove('node-active');});}
function togglePlay(){playing=!playing;playBtn.textContent=playing?'⏸ Pause':'▶ Play';playBtn.setAttribute('aria-label',playing?'Pause':'Play');}
speedSlider.addEventListener('input',function(){var v=parseInt(speedSlider.value);speed=0.25+((v/16)*3.75);speedVal.textContent=speed.toFixed(2)+'×';});
function animate(ts){if(!ts)ts=0;if(playing){t+=0.016*speed;flowDots.forEach(function(dot){dot.progress+=0.008*speed;if(dot.progress>1)dot.progress=0;var p=dot.progress;dot.el.setAttribute('cx',dot.sx+(dot.ex-dot.sx)*p);dot.el.setAttribute('cy',dot.sy+(dot.ey-dot.sy)*p);});}animId=requestAnimationFrame(animate);}
function buildChallenge(){challengeQuestions.innerHTML='';quiz.forEach(function(q,idx){var b=document.createElement('div');b.className='question-block';b.innerHTML='<h3>'+(idx+1)+'. '+q.q+'</h3>';q.opts.forEach(function(o,i){b.innerHTML+='<div class="q-option"><input type="radio" name="q'+idx+'" id="q'+idx+'_'+i+'" value="'+i+'"><label for="q'+idx+'_'+i+'">'+o+'</label></div>';});challengeQuestions.appendChild(b);});challengeBtn.hidden=false;}
function submitChallenge(){var score=0,total=quiz.length;quiz.forEach(function(q,idx){var sel=document.querySelector('input[name="q'+idx+'"]:checked');var blocks=document.querySelectorAll('.question-block');var opts=blocks[idx].querySelectorAll('.q-option');opts.forEach(function(o){o.classList.remove('correct','wrong');});var fb=blocks[idx].querySelector('.q-feedback');if(fb)fb.remove();if(sel){var val=parseInt(sel.value);if(val===q.ans){opts[q.ans].classList.add('correct');score++;}else{opts[q.ans].classList.add('correct');opts[val].classList.add('wrong');}}else{opts[q.ans].classList.add('correct');}var fbDiv=document.createElement('div');fbDiv.className='q-feedback '+(sel&&parseInt(sel.value)===q.ans?'correct':'wrong');fbDiv.textContent=sel&&parseInt(sel.value)===q.ans?'✓ Correct!':'✗ The correct answer was option '+(q.ans+1);blocks[idx].appendChild(fbDiv);});challengeResult.hidden=false;var pct=Math.round(score/total*100);challengeResult.innerHTML='<h3>Score: '+score+'/'+total+' ('+pct+'%)</h3><p>'+(pct>=80?'Outstanding! You have strong backend technology knowledge.':pct>=50?'Good foundation! Review the server and language nodes.':'Keep exploring backend technologies by clicking each node.')+'</p>';if(pct>=80){completionOverlay.hidden=false;completionScore.textContent='You scored '+score+'/'+total+' ('+pct+'%)';completionMsg.textContent='You understand the key backend technologies — from web servers and languages to databases and API gateways!';}}
function closeCompletion(){completionOverlay.hidden=true;}
function showChallenge(){challengeSection.hidden=!challengeSection.hidden;if(!challengeSection.hidden)challengeSection.scrollIntoView({behavior:'smooth'});}
function init(){buildSVG();buildChallenge();animId=requestAnimationFrame(animate);challengeBtn.hidden=false;setTimeout(function(){skeleton.style.opacity='0';skeleton.style.transition='opacity .4s';setTimeout(function(){skeleton.hidden=true;},400);app.hidden=false;},600);}
init();
window.addEventListener('unload',function(){if(animId)cancelAnimationFrame(animId);});
window.selectNode=selectNode;window.closeInfo=closeInfo;window.togglePlay=togglePlay;window.toggleTheme=toggleTheme;window.showChallenge=showChallenge;window.submitChallenge=submitChallenge;window.closeCompletion=closeCompletion;
}catch(e){document.getElementById('skeleton').hidden=true;var eb=document.getElementById('error-boundary');eb.hidden=false;document.getElementById('error-message').textContent=e.message||'Failed to initialize diagram';console.error('Diagram init error:',e);}
})();