(function(){'use strict';
const STORE='consica-theme';
const nodes=[{id:'switch',name:'Ethernet Switch',desc:'A network switch forwards frames based on destination MAC addresses. Operates at Layer 2 (Data Link layer).',details:'Layer: 2 (Data Link)\nForwarding: MAC address table\nPorts: 5 shown\nSpeed: 10/100/1000 Mbps'},{id:'A',name:'Device A - AA:AA:AA:AA:AA:01',desc:'Device connected to Port 1. When it sends a frame, the switch learns its MAC address and associates it with Port 1.',details:'MAC: AA:AA:AA:AA:AA:01\nPort: 1\nType: Client device\nStatus: Active'},{id:'B',name:'Device B - BB:BB:BB:BB:BB:02',desc:'Device connected to Port 2. MAC addresses are learned dynamically when devices first communicate.',details:'MAC: BB:BB:BB:BB:BB:02\nPort: 2\nType: Client device\nStatus: Active'},{id:'C',name:'Device C - CC:CC:CC:CC:CC:03',desc:'Device connected to Port 3. The switch uses its MAC table to forward frames only to the correct port.',details:'MAC: CC:CC:CC:CC:CC:03\nPort: 3\nType: Client device\nStatus: Active'},{id:'store',name:'Store-and-Forward',desc:'The switch receives the entire frame, checks the CRC for errors, then forwards it. Most reliable but highest latency.',details:'Latency: Higher (full frame)\nError checking: Full CRC\nUse case: Enterprise networks\nAdvantage: Drops corrupted frames'},{id:'cut',name:'Cut-Through',desc:'The switch forwards the frame as soon as it reads the destination MAC address (first 6 bytes after preamble).',details:'Latency: Very low\nError checking: None\nUse case: High-speed trading\nAdvantage: Minimal delay'}];
const questions=[{q:'What address does a switch use to forward frames?',opts:['IP address','MAC address','Port number','DNS name'],ans:1},{q:'At which OSI layer does a switch operate?',opts:['Layer 1','Layer 2','Layer 3','Layer 4'],ans:1},{q:'How does a switch learn MAC addresses?',opts:['Static config','DHCP','Dynamic learning from source MAC','ARP broadcast'],ans:2},{q:'Which forwarding method checks the entire frame for errors?',opts:['Cut-Through','Fragment-Free','Store-and-Forward','Fast Forward'],ans:2},{q:'What happens when a switch receives a frame for an unknown MAC?',opts:['Drops it','Broadcasts to all ports','Returns to sender','Queues it'],ans:1},{q:'What is a MAC address table also called?',opts:['Routing table','ARP table','CAM table','NAT table'],ans:2}];
let speed=1,playing=false,theme='dark',rAF=null,t=0;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupNodes();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}
function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}
function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}
function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';});}}
function setupNodes(){var all=nodes.slice();all.push({id:'frag',name:'Fragment-Free',desc:'Reads the first 64 bytes of a frame before forwarding. Catches most runt frames while keeping latency low.',details:'Latency: Low\nError checking: First 64 bytes\nUse case: Balanced performance\nCollision fragments: Filtered'});all.forEach(function(n){var sel='[data-device="'+n.id+'"], [data-fwd="'+n.id+'"], [data-port="'+n.id+'"]';var els=document.querySelectorAll(sel);els.forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo(n);});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showInfo(n);}});});});document.querySelectorAll('.mac-entry').forEach(function(el){var mac=el.getAttribute('data-mac');if(mac){el.addEventListener('click',function(e){e.stopPropagation();showInfo({name:'MAC: '+mac,desc:'A MAC address is a unique hardware identifier assigned to network interfaces.',details:'Format: 6 octets in hex\nOUI: First 3 octets (vendor)\nNIC: Last 3 octets (device)\nLayer: 2 (Data Link)'});});}});document.addEventListener('click',function(e){if(!e.target.closest('[data-device]')&&!e.target.closest('[data-fwd]')&&!e.target.closest('[data-port]')&&!e.target.closest('.switch-body')&&!e.target.closest('.mac-bg')&&!e.target.closest('.mac-entry')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}
function showInfo(node){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel)return;title.textContent=node.name;desc.textContent=node.desc;details.innerHTML='<p>'+node.details.split('\n').join('<br>')+'</p>';panel.hidden=false;}
function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}
function startRAF(){function frame(){if(playing){t+=0.03*speed;var x=125+(415-125)*((Math.sin(t)+1)/2);var f=document.getElementById('frame1');if(f){f.setAttribute('x',x);f.setAttribute('y',245+Math.sin(t*2)*3);f.setAttribute('visibility','visible');}}rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}
function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';t=0;const f=document.getElementById('frame1');if(f)f.setAttribute('visibility','hidden');const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}}
function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}
let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}
function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
