(function(){'use strict';
try{
var components=[
{id:"html",name:"HTML — Structure",purpose:"Defines the structure and content of web pages using elements and tags",desc:"HTML (HyperText Markup Language) provides the structural foundation using elements like headings, paragraphs, images, links, and forms.",how:"HTML uses nested elements with opening/closing tags to define content hierarchy. Semantic tags (header, nav, main, article) improve accessibility. The browser parses HTML into the DOM tree for rendering and JavaScript access.",why:"HTML gives web content meaning and structure that browsers, search engines, and assistive technologies can understand.",analogy:"Like the skeleton of a building that defines its rooms and layout",fun:"The first HTML spec had just 18 elements — today there are over 140",takeaway:"HTML is the structural foundation of every web page on the internet.",mistake:"HTML is not a programming language — it's a markup language that describes content structure."},
{id:"css",name:"CSS — Style",purpose:"Controls the visual presentation and layout of HTML elements on the page",desc:"CSS (Cascading Style Sheets) defines how elements look — colors, fonts, spacing, animations, and responsive layouts for different screen sizes.",how:"CSS uses selectors to target elements and apply styles via properties. The cascade determines priority. Flexbox and Grid provide powerful layouts. Media queries enable responsive design. Custom properties (variables) enable theming.",why:"CSS transforms raw HTML into visually appealing, usable interfaces that adapt to any device.",analogy:"Like the paint, wallpaper, and furniture that make a building's interior beautiful",fun:"CSS can create complex 3D animations and interactive effects without JavaScript",takeaway:"CSS handles all visual styling and layout, making applications look professional and work responsively.",mistake:"CSS is not optional — even basic styling dramatically improves usability and accessibility."},
{id:"js",name:"JavaScript — Behavior",purpose:"Adds interactivity, dynamic behavior, and programmatic control to web pages",desc:"JavaScript is the programming language of the web, enabling dynamic content updates, user interaction handling, API calls, animations, and complex application logic.",how:"JavaScript runs in the browser's JS engine (V8, SpiderMonkey). It uses the DOM API to manipulate page content, the Fetch API for network requests, and event listeners for interactivity. Modern JS includes modules, async/await, and closures.",why:"JavaScript transforms static pages into dynamic applications that respond to users in real time.",analogy:"Like a building's electrical system that powers lights, appliances, and automation",fun:"JavaScript is the most widely used programming language in the world",takeaway:"JavaScript brings web pages to life with interactivity, data processing, and dynamic content.",mistake:"JavaScript runs on the client — never put sensitive logic or secrets in frontend JS code."},
{id:"dom",name:"DOM — Document Object Model",purpose:"The programming interface that represents the page structure as a tree of objects",desc:"The DOM is an API that represents HTML/XML documents as a tree structure of objects. JavaScript uses the DOM to read, modify, and delete page elements dynamically.",how:"When the browser parses HTML, it creates the DOM tree. Each element becomes a node. JS can query nodes (getElementById, querySelector), modify attributes/content, add/remove elements, and listen for events. Virtual DOM frameworks optimize updates.",why:"The DOM is the bridge between JavaScript code and what users see on the screen.",analogy:"Like a building's floor plan that shows every room and how they connect",fun:"The DOM specification is maintained by the W3C and has been in development since 1998",takeaway:"The DOM is the API JavaScript uses to interact with and modify web page content.",mistake:"Direct DOM manipulation is slow — modern frameworks use virtual DOM or reactive updates for performance."},
{id:"browser",name:"Browser Engine",purpose:"Renders web pages by interpreting HTML, CSS, and JavaScript into visual interfaces",desc:"The browser engine (Blink, WebKit, Gecko) parses code, constructs the render tree, calculates layouts, and paints pixels to the screen.",how:"The browser pipeline: HTML parsing → DOM construction → CSSOM construction → Render tree → Layout (reflow) → Paint (rasterization) → Compositing. JavaScript can modify the DOM/CSSOM at any point, triggering reflows and repaints.",why:"The browser engine is the runtime environment that makes web technologies work together seamlessly.",analogy:"Like a movie projector that takes film frames and displays them as moving images on screen",fun:"Chrome's Blink engine contains over 25 million lines of code",takeaway:"The browser engine is the runtime that renders web pages from HTML, CSS, and JavaScript.",mistake:"Different browser engines render slightly differently — always test across browsers."},
{id:"framework",name:"Frontend Frameworks",purpose:"Provide structured patterns and tools for building complex user interfaces efficiently",desc:"Frontend frameworks like React, Vue, and Angular provide component-based architectures, reactive data binding, routing, and state management to build scalable UIs.",how:"Frameworks introduce concepts like components (reusable UI pieces), props/state (data management), virtual DOM (efficient updates), and hooks/lifecycle methods. They handle DOM updates, event delegation, and cross-browser compatibility.",why:"Frameworks solve common frontend challenges — managing state, updating the DOM efficiently, and organizing code at scale.",analogy:"Like a pre-built workshop with tools and jigs that make construction faster and more consistent",fun:"React was originally developed for Facebook's news feed and open-sourced in 2013",takeaway:"Frontend frameworks provide structure and tools for building complex, maintainable user interfaces.",mistake:"You don't need a framework for every project — sometimes vanilla JS or a small library is sufficient."}
];
var nodes=[{id:"html",x:240,y:50,w:140,h:50,color:"#e65100",icon:"📄"},{id:"css",x:240,y:130,w:140,h:50,color:"#1565c0",icon:"🎨"},{id:"js",x:240,y:210,w:140,h:50,color:"#f9a825",icon:"⚡"},{id:"dom",x:240,y:290,w:140,h:50,color:"#2e7d32",icon:"🌳"},{id:"browser",x:60,y:340,w:140,h:50,color:"#6a1b9a",icon:"🌐"},{id:"framework",x:400,y:340,w:140,h:50,color:"#c62828",icon:"⚛"}];
var connections=[{from:"html",to:"dom"},{from:"css",to:"dom"},{from:"js",to:"dom"},{from:"dom",to:"browser"},{from:"dom",to:"framework"},{from:"browser",to:"framework"},{from:"framework",to:"js"}];
var quiz=[
{q:"What does HTML provide for web pages?",opts:["Visual styling","Structure and content","Interactivity","Database storage"],ans:1},
{q:"What is the primary role of CSS?",opts:["Define page structure","Add interactivity","Control visual presentation and layout","Manage server data"],ans:2},
{q:"How does JavaScript interact with web pages?",opts:["Through the DOM API","Directly modifying HTML files","By compiling to CSS","Through database queries"],ans:0},
{q:"What happens when the browser parses HTML?",opts:["It creates a CSS file","It generates the DOM tree","It compiles JavaScript","It connects to a database"],ans:1},
{q:"What is a common misconception about frontend development?",opts:["It requires a server","It only involves visual design","It doesn't use JavaScript","It can't be tested"],ans:1},
{q:"Why were frontend frameworks like React created?",opts:["To replace HTML","To eliminate CSS","To solve state management and efficient DOM updates","To remove the need for browsers"],ans:2}
];
var app=document.getElementById('app'),skeleton=document.getElementById('skeleton'),errorBoundary=document.getElementById('error-boundary'),errorMsg=document.getElementById('error-message'),container=document.getElementById('diagram-container'),infoPanel=document.getElementById('info-panel'),infoContent=document.getElementById('info-content'),speedSlider=document.getElementById('speed-slider'),speedVal=document.getElementById('speed-val'),playBtn=document.getElementById('play-btn'),challengeSection=document.getElementById('challenge-section'),challengeQuestions=document.getElementById('challenge-questions'),challengeResult=document.getElementById('challenge-result'),completionOverlay=document.getElementById('completion-overlay'),completionScore=document.getElementById('completion-score'),completionMsg=document.getElementById('completion-msg'),challengeBtn=document.getElementById('challenge-btn'),themeToggle=document.getElementById('theme-toggle');
var t=0,playing=true,selectedId=null,theme=localStorage.getItem('consica-theme')||'dark',speed=1;
var animId=null,svg=null,flowDots=[];

function setTheme(t){document.documentElement.setAttribute('data-theme',t==='light'?'light':'');localStorage.setItem('consica-theme',t);theme=t}
function toggleTheme(){setTheme(theme==='dark'?'light':'dark')}
setTheme(theme);
function buildSVG(){var W=620,H=420,ns='http://www.w3.org/2000/svg';svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 '+W+' '+H);svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.setAttribute('role','img');svg.setAttribute('aria-label','Frontend technologies pyramid');
var defs=document.createElementNS(ns,'defs');defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10" fill="var(--accent2, #3b82f6)"/></marker><linearGradient id="bg-grad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="var(--surface, #131b2e)"/><stop offset="100%" stop-color="var(--surface2, #1a2338)"/></linearGradient>';svg.appendChild(defs);
var bg=document.createElementNS(ns,'rect');bg.setAttribute('width',W);bg.setAttribute('height',H);bg.setAttribute('fill','url(#bg-grad)');bg.setAttribute('rx','12');svg.appendChild(bg);
var zones=[{label:"Core Technologies",x:30,y:35,w:560,h:90,color:"rgba(230,81,0,.08)"},{label:"Browser Runtime",x:30,y:130,w:560,h:85,color:"rgba(21,101,192,.08)"},{label:"DOM Interface",x:30,y:220,w:560,h:70,color:"rgba(249,168,37,.08)"},{label:"Rendering & Frameworks",x:30,y:295,w:560,h:105,color:"rgba(106,27,154,.05)"}];
zones.forEach(function(z){var r=document.createElementNS(ns,'rect');r.setAttribute('x',z.x);r.setAttribute('y',z.y);r.setAttribute('width',z.w);r.setAttribute('height',z.h);r.setAttribute('fill',z.color);r.setAttribute('rx','8');r.setAttribute('stroke','var(--border)');r.setAttribute('stroke-width','1');svg.appendChild(r);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',z.x+10);lbl.setAttribute('y',z.y+18);lbl.setAttribute('fill','var(--text2)');lbl.setAttribute('font-size','10');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.textContent=z.label;svg.appendChild(lbl);});
connections.forEach(function(c){var from=nodes.find(function(n){return n.id===c.from});var to=nodes.find(function(n){return n.id===c.to});if(!from||!to)return;var x1=from.x+from.w/2,y1=from.y+from.h/2,x2=to.x+to.w/2,y2=to.y+to.h/2;var dx=x2-x1,dy=y2-y1,dist=Math.sqrt(dx*dx+dy*dy);var mx=from.w/2+4,my=from.h/2+4,sx=x1+(dx/dist)*mx,sy=y1+(dy/dist)*my,ex=x2-(dx/dist)*mx,ey=y2-(dy/dist)*my;var line=document.createElementNS(ns,'line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',ex);line.setAttribute('y2',ey);line.setAttribute('stroke','var(--accent2)');line.setAttribute('stroke-width','2');line.setAttribute('opacity','0.4');line.setAttribute('marker-end','url(#arrow)');svg.appendChild(line);var dot=document.createElementNS(ns,'circle');dot.setAttribute('r','4');dot.setAttribute('fill','var(--accent2)');dot.setAttribute('opacity','0.8');dot.setAttribute('class','flow-dot');svg.appendChild(dot);flowDots.push({el:dot,sx:sx,sy:sy,ex:ex,ey:ey,progress:Math.random()});});
nodes.forEach(function(n){var g=document.createElementNS(ns,'g');g.setAttribute('class','node-clickable');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',components.find(function(c){return c.id===n.id}).name);g.setAttribute('data-id',n.id);var rect=document.createElementNS(ns,'rect');rect.setAttribute('x',n.x);rect.setAttribute('y',n.y);rect.setAttribute('width',n.w);rect.setAttribute('height',n.h);rect.setAttribute('rx','8');rect.setAttribute('fill',n.color);rect.setAttribute('opacity','0.9');rect.setAttribute('class','node-bg');g.appendChild(rect);var icon=document.createElementNS(ns,'text');icon.setAttribute('x',n.x+16);icon.setAttribute('y',n.y+n.h/2+6);icon.setAttribute('font-size','18');icon.setAttribute('text-anchor','middle');icon.textContent=n.icon;g.appendChild(icon);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',n.x+30);lbl.setAttribute('y',n.y+n.h/2+5);lbl.setAttribute('fill','#fff');lbl.setAttribute('font-size','11');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.setAttribute('class','node-label');lbl.textContent=components.find(function(c){return c.id===n.id}).name;g.appendChild(lbl);g.addEventListener('click',function(){selectNode(n.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(n.id);}});svg.appendChild(g);});
container.innerHTML='';container.appendChild(svg);}
function selectNode(id){selectedId=id;var comp=components.find(function(c){return c.id===id});if(!comp)return;infoPanel.hidden=false;var html='<h3>'+comp.name+'</h3><div class="info-tags"><span class="info-tag">Purpose</span></div><p><strong>🎯 Purpose:</strong> '+comp.purpose+'</p><h4>📝 Description</h4><p>'+comp.desc+'</p><h4>⚙️ How It Works</h4><p>'+comp.how+'</p><h4>💡 Why It Matters</h4><p>'+comp.why+'</p><h4>🔗 Analogy</h4><p>'+comp.analogy+'</p><h4>🎲 Fun Fact</h4><p>'+comp.fun+'</p><h4>✅ Key Takeaway</h4><p>'+comp.takeaway+'</p><h4>⚠️ Common Mistake</h4><p>'+comp.mistake+'</p>';infoContent.innerHTML=html;infoPanel.scrollIntoView({behavior:'smooth',block:'nearest'});container.querySelectorAll('.node-clickable').forEach(function(g){if(g.getAttribute('data-id')===id)g.classList.add('node-active');else g.classList.remove('node-active');});}
function closeInfo(){infoPanel.hidden=true;selectedId=null;container.querySelectorAll('.node-active').forEach(function(g){g.classList.remove('node-active');});}
function togglePlay(){playing=!playing;playBtn.textContent=playing?'⏸ Pause':'▶ Play';playBtn.setAttribute('aria-label',playing?'Pause':'Play');}
speedSlider.addEventListener('input',function(){var v=parseInt(speedSlider.value);speed=0.25+((v/16)*3.75);speedVal.textContent=speed.toFixed(2)+'×';});
function animate(ts){if(!ts)ts=0;if(playing){t+=0.016*speed;flowDots.forEach(function(dot){dot.progress+=0.008*speed;if(dot.progress>1)dot.progress=0;var p=dot.progress;dot.el.setAttribute('cx',dot.sx+(dot.ex-dot.sx)*p);dot.el.setAttribute('cy',dot.sy+(dot.ey-dot.sy)*p);});}animId=requestAnimationFrame(animate);}
function buildChallenge(){challengeQuestions.innerHTML='';quiz.forEach(function(q,idx){var b=document.createElement('div');b.className='question-block';b.innerHTML='<h3>'+(idx+1)+'. '+q.q+'</h3>';q.opts.forEach(function(o,i){b.innerHTML+='<div class="q-option"><input type="radio" name="q'+idx+'" id="q'+idx+'_'+i+'" value="'+i+'"><label for="q'+idx+'_'+i+'">'+o+'</label></div>';});challengeQuestions.appendChild(b);});challengeBtn.hidden=false;}
function submitChallenge(){var score=0,total=quiz.length;quiz.forEach(function(q,idx){var sel=document.querySelector('input[name="q'+idx+'"]:checked');var blocks=document.querySelectorAll('.question-block');var opts=blocks[idx].querySelectorAll('.q-option');opts.forEach(function(o){o.classList.remove('correct','wrong');});var fb=blocks[idx].querySelector('.q-feedback');if(fb)fb.remove();if(sel){var val=parseInt(sel.value);if(val===q.ans){opts[q.ans].classList.add('correct');score++;}else{opts[q.ans].classList.add('correct');opts[val].classList.add('wrong');}}else{opts[q.ans].classList.add('correct');}var fbDiv=document.createElement('div');fbDiv.className='q-feedback '+(sel&&parseInt(sel.value)===q.ans?'correct':'wrong');fbDiv.textContent=sel&&parseInt(sel.value)===q.ans?'✓ Correct!':'✗ The correct answer was option '+(q.ans+1);blocks[idx].appendChild(fbDiv);});challengeResult.hidden=false;var pct=Math.round(score/total*100);challengeResult.innerHTML='<h3>Score: '+score+'/'+total+' ('+pct+'%)</h3><p>'+(pct>=80?'Excellent! You know the frontend tech stack well.':pct>=50?'Good progress! Review the components above to strengthen your knowledge.':'Keep learning — click each node to understand frontend technologies better.')+'</p>';if(pct>=80){completionOverlay.hidden=false;completionScore.textContent='You scored '+score+'/'+total+' ('+pct+'%)';completionMsg.textContent='You now understand the core frontend technologies — HTML, CSS, JavaScript, and how they work together!';}}
function closeCompletion(){completionOverlay.hidden=true;}
function showChallenge(){challengeSection.hidden=!challengeSection.hidden;if(!challengeSection.hidden)challengeSection.scrollIntoView({behavior:'smooth'});}
function init(){buildSVG();buildChallenge();animId=requestAnimationFrame(animate);challengeBtn.hidden=false;setTimeout(function(){skeleton.style.opacity='0';skeleton.style.transition='opacity .4s';setTimeout(function(){skeleton.hidden=true;},400);app.hidden=false;},600);}
init();
window.addEventListener('unload',function(){if(animId)cancelAnimationFrame(animId);});
window.selectNode=selectNode;window.closeInfo=closeInfo;window.togglePlay=togglePlay;window.toggleTheme=toggleTheme;window.showChallenge=showChallenge;window.submitChallenge=submitChallenge;window.closeCompletion=closeCompletion;
}catch(e){document.getElementById('skeleton').hidden=true;var eb=document.getElementById('error-boundary');eb.hidden=false;document.getElementById('error-message').textContent=e.message||'Failed to initialize diagram';console.error('Diagram init error:',e);}
})();