(function(){'use strict';
var theme=localStorage.getItem('consica-theme')||'dark';
document.documentElement.setAttribute('data-theme',theme);
var app,container,skeleton,errorBoundary,errorMsg,svgContainer,infoTitle,infoDesc,stepsList,playBtn,resetBtn,speedSlider,speedVal,themeBtn,challengeOverlay,challengeBody,challengeClose,completionOverlay,completionScore,completionClose,challengeBtn,rafId,animating=false,t=0,activeNode=null,nodes=[],flowDots=[],speed=1,challengeState={questions:[],current:0,answers:{},submitted:false};
var components=[
{id:'tokenize',name:'Tokenization',sublabel:'Breaking text apart',desc:'Tokenization splits raw text into smaller pieces (tokens) like words, subwords, or characters that the model can process.',purpose:'Convert raw text into processable units',how:'Split text on whitespace/punctuation or use subword algorithms like BPE',why:'Models cannot process raw text directly',analogy:'Cutting a paragraph into individual words',funFact:'GPT-4 uses a tokenizer with about 100,000 tokens',takeaway:'Tokenization is the first step for any NLP task',mistake:'Different tokenizers give different results for the same text'},
{id:'parse',name:'Parsing',sublabel:'Grammar structure',desc:'Parsing analyzes the grammatical structure of text, identifying relationships between words like subject, verb, and object.',purpose:'Understand sentence structure and grammar',how:'Dependency parsing or constituency parsing builds syntax trees',why:'Meaning depends on word relationships, not just order',analogy:'Diagramming a sentence in grammar class',funFact:'The Stanford Parser was a breakthrough in accurate dependency parsing',takeaway:'Parsing reveals who did what to whom',mistake:'Ambiguous sentences can have multiple valid parses'},
{id:'embed',name:'Word Embeddings',sublabel:'Vector representation',desc:'Word embeddings convert words into numerical vectors that capture semantic meaning - similar words have similar vectors.',purpose:'Represent words as numbers that preserve meaning',how:'Word2Vec, GloVe, or contextual embeddings from BERT map words to dense vectors',why:'Neural networks need numerical input, not text',analogy:'A map where similar words are located near each other',funFact:'The classic example: king minus man plus woman equals queen',takeaway:'Embeddings capture semantic relationships',mistake:'Static embeddings miss context-dependent word meanings'},
{id:'transformer',name:'Transformer',sublabel:'Attention mechanism',desc:'Transformers process entire sequences at once using self-attention, allowing each word to attend to every other word.',purpose:'Model relationships between all words in a sequence',how:'Self-attention computes relevance weights between every pair of positions',why:'Captures long-range dependencies better than RNNs',analogy:'A meeting where everyone hears everyone else simultaneously',funFact:'The Transformer architecture was introduced in 2017 by Google researchers',takeaway:'Attention is all you need',mistake:'Transformers have quadratic complexity in sequence length'},
{id:'classify',name:'Classification',sublabel:'Text categorization',desc:'NLP classification assigns categories to text - sentiment, topic, intent, or spam detection based on learned patterns.',purpose:'Automatically categorize text content',how:'Fine-tune a pre-trained language model on labeled text data',why:'Enables automated understanding of massive text volumes',analogy:'A librarian sorting books by genre',funFact:'BERT set 11 NLP benchmarks records when released in 2018',takeaway:'Classification powers content moderation and routing',mistake:'Text classification struggles with sarcasm and nuance'},
{id:'generate',name:'Text Generation',sublabel:'Creating language',desc:'Text generation models produce coherent, contextually appropriate text based on a prompt or starting sequence.',purpose:'Generate human-like text automatically',how:'Autoregressive models predict the next token one at a time given previous tokens',why:'Enables chatbots, translation, summarization, and creative writing',analogy:'A writer continuing a story from a prompt',funFact:'GPT-3 has 175 billion parameters and was trained on 570GB of text',takeaway:'Generation is the most visible NLP application',mistake:'Generated text can contain factual errors (hallucination)'}
];
var connectionsData=[{from:'tokenize',to:'parse'},{from:'parse',to:'embed'},{from:'embed',to:'transformer'},{from:'transformer',to:'classify'},{from:'transformer',to:'generate'}];
var stepsData=[
{id:'tokenize',label:'Tokenization - break text into processable tokens'},
{id:'parse',label:'Parsing - analyze grammatical structure'},
{id:'embed',label:'Word Embeddings - convert words to meaning vectors'},
{id:'transformer',label:'Transformer - self-attention processes all words'},
{id:'classify',label:'Classification - categorize text content'},
{id:'generate',label:'Text Generation - create human-like text'}
];
var challenges=[
{q:'What is the first step in NLP text processing?',o:['Classification','Tokenization','Generation','Embedding'],a:1},
{q:'What does a Transformer use to model word relationships?',o:['Recurrence','Self-attention','Convolution','Memory cells'],a:1},
{q:'What does king minus man plus woman equal in word embeddings?',o:['Princess','Queen','Duchess','Empress'],a:1},
{q:'What problem do large language models have regarding facts?',o:['They are too slow','They can hallucinate - generate false information','They cannot translate','They only work in English'],a:1},
{q:'Why are transformers better than RNNs for long texts?',o:['They are smaller','They capture long-range dependencies better through attention','They train faster on CPU','They use less memory'],a:1},
{q:'What does text classification commonly identify?',o:['Grammar errors','Sentiment, topic, or spam','Word definitions','Character count'],a:1}
];
function init(){app=document.getElementById('app');container=document.getElementById('diagram-container');skeleton=document.getElementById('loading-skeleton');errorBoundary=document.getElementById('error-boundary');errorMsg=document.getElementById('error-message');svgContainer=document.getElementById('svg-container');infoTitle=document.getElementById('info-title');infoDesc=document.getElementById('info-desc');stepsList=document.getElementById('steps-list');playBtn=document.getElementById('play-btn');resetBtn=document.getElementById('reset-btn');speedSlider=document.getElementById('speed-slider');speedVal=document.getElementById('speed-value');themeBtn=document.getElementById('theme-toggle');challengeOverlay=document.getElementById('challenge-overlay');challengeBody=document.getElementById('challenge-body');challengeClose=document.getElementById('challenge-close');completionOverlay=document.getElementById('completion-overlay');completionScore=document.getElementById('completion-score');completionClose=document.getElementById('completion-close');challengeBtn=document.getElementById('challenge-btn');
try{buildDiagram();setupControls();setupChallenge();showContainer();}catch(e){showError(e.message||'Failed to build diagram');}}
function showContainer(){skeleton.classList.add('hidden');container.classList.remove('hidden');}
function showError(msg){skeleton.classList.add('hidden');errorBoundary.classList.remove('hidden');errorMsg.textContent=msg;}
function buildDiagram(){var W=860,H=340;var svg=svgCreate('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':'NLP pipeline showing text processing from tokenization through generation'});svgContainer.appendChild(svg);
var defs=svgCreate('defs');svg.appendChild(defs);
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="var(--conn-stroke)"/></marker><marker id="arrowLight" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#94a3b8"/></marker>';
var positions={tokenize:{x:80,y:70},parse:{x:220,y:70},embed:{x:360,y:70},transformer:{x:500,y:70},classify:{x:360,y:210},generate:{x:640,y:210}};
connectionsData.forEach(function(c){var f=positions[c.from],t=positions[c.to];var line;if(c.from==='transformer'&&c.to==='classify'){var d='M'+f.x+','+(f.y+26)+' Q'+((f.x+t.x)/2)+','+((f.y+t.y)/2)+' '+t.x+','+(t.y-26);line=svgCreate('path',{d:d,class:'connection-line',fill:'none','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}else if(c.from==='transformer'&&c.to==='generate'){line=svgCreate('line',{x1:f.x+70,y1:f.y,x2:t.x-70,y2:t.y,class:'connection-line','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}else{line=svgCreate('line',{x1:f.x+70,y1:f.y,x2:t.x-70,y2:t.y,class:'connection-line','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}svg.appendChild(line);var fd=svgCreate('circle',{class:'flow-dot',cx:0,cy:0,r:0,fill:'var(--accent)'});svg.appendChild(fd);flowDots.push({el:fd,sx:f.x+70,sy:f.y,ex:t.x-70,ey:t.y});});
components.forEach(function(cp){var p=positions[cp.id];var g=svgCreate('g',{class:'node-g',tabIndex:0,role:'button','aria-label':cp.name+': '+cp.sublabel});g.dataset.id=cp.id;var rx=svgCreate('rect',{x:p.x-70,y:p.y-26,width:140,height:52,rx:10,class:'node-rect'});g.appendChild(rx);var lbl=svgCreate('text',{x:p.x,y:p.y-4,class:'node-label'});lbl.textContent=cp.name;g.appendChild(lbl);var slbl=svgCreate('text',{x:p.x,y:p.y+14,class:'node-sublabel'});slbl.textContent=cp.sublabel;g.appendChild(slbl);g.addEventListener('click',function(){selectNode(cp.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(cp.id);}});svg.appendChild(g);nodes.push({el:g,data:cp,pos:p});});
var selected=false;components.forEach(function(c){if(!selected){selectNode(c.id);selected=true;}});renderSteps();}
function svgCreate(tag,attrs){var el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(var k in attrs)el.setAttribute(k,attrs[k]);return el;}
function selectNode(id){activeNode=id;var cp=getComp(id);if(!cp)return;nodes.forEach(function(n){var r=n.el.querySelector('.node-rect');if(r)r.classList.toggle('active',n.data.id===id);});infoTitle.textContent=cp.name+' - '+cp.sublabel;infoDesc.innerHTML='<strong>Purpose:</strong> '+cp.purpose+'<br><br><strong>How it works:</strong> '+cp.how+'<br><br><strong>Why it matters:</strong> '+cp.why+'<br><br><strong>Analogy:</strong> '+cp.analogy+(cp.funFact?'<br><br><strong>Fun fact:</strong> '+cp.funFact:'')+'<br><br><strong>Key takeaway:</strong> '+cp.takeaway+'<br><br><strong>Common mistake:</strong> '+cp.mistake;var items=stepsList.querySelectorAll('li');items.forEach(function(li){li.classList.toggle('active',li.dataset.id===id);});}
function getComp(id){for(var i=0;i<components.length;i++){if(components[i].id===id)return components[i];}return null;}
function renderSteps(){stepsList.innerHTML='';components.forEach(function(c){var li=document.createElement('li');li.dataset.id=c.id;li.textContent=c.name+' - '+c.sublabel;li.tabIndex=0;li.addEventListener('click',function(){selectNode(c.id);});li.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(c.id);}});stepsList.appendChild(li);});}
function animateDiagram(){var start=performance.now();function frame(now){if(!animating){rafId=null;return;}var dt=(now-start)/1000*speed;t=(t+dt)%1;flowDots.forEach(function(d){d.el.setAttribute('cx',d.sx+(d.ex-d.sx)*t);d.el.setAttribute('cy',d.sy+(d.ey-d.sy)*t);d.el.setAttribute('r',4);});rafId=requestAnimationFrame(frame);}rafId=requestAnimationFrame(frame);}
function setupControls(){themeBtn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem('consica-theme',theme);});playBtn.addEventListener('click',function(){animating=!animating;if(animating){playBtn.innerHTML='&#9646;&#9646;';animateDiagram();}else{playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});resetBtn.addEventListener('click',function(){t=0;flowDots.forEach(function(d){d.el.setAttribute('r',0);});if(animating){animating=false;playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});speedSlider.addEventListener('input',function(){speed=parseFloat(this.value);speedVal.textContent=speed+'x';});document.addEventListener('keydown',function(e){if(e.key==='Escape'){challengeOverlay.classList.add('hidden');completionOverlay.classList.add('hidden');}});}
function setupChallenge(){challengeBtn.addEventListener('click',function(){openChallenge();});challengeClose.addEventListener('click',function(){challengeOverlay.classList.add('hidden');});completionClose.addEventListener('click',function(){completionOverlay.classList.add('hidden');challengeOverlay.classList.add('hidden');});}
function openChallenge(){challengeState.questions=challenges.slice().sort(function(){return Math.random()-0.5;}).slice(0,5);challengeState.current=0;challengeState.answers={};challengeState.submitted=false;challengeOverlay.classList.remove('hidden');renderQuestion();}
function renderQuestion(){var q=challengeState.questions[challengeState.current];if(!q){finishChallenge();return;}var html='<div class="question"><div class="question-text">'+(challengeState.current+1)+'. '+q.q+'</div><div class="options">';q.o.forEach(function(opt,i){var sel=challengeState.answers[challengeState.current]===i?' selected':'';var cls=challengeState.submitted?(i===q.a?' correct':(challengeState.answers[challengeState.current]===i?' wrong':'')):'';html+='<label class="option-label'+sel+cls+'"><input type="radio" name="q'+challengeState.current+'" value="'+i+'"'+(challengeState.submitted?' disabled':'')+(sel?' checked':'')+' onchange="('+selectOption.toString()+')('+challengeState.current+','+i+')">'+opt+'</label>';});html+='</div></div>';html+='<div class="challenge-actions">';if(!challengeState.submitted){html+='<button class="btn-primary" onclick="('+submitChallenge.toString()+')()">Submit Answer</button>';}else{if(challengeState.current<challengeState.questions.length-1){html+='<button class="btn-primary" onclick="('+nextQuestion.toString()+')()">Next Question</button>';}else{html+='<button class="btn-primary" onclick="('+finishChallenge.toString()+')()">See Results</button>';}}html+='</div>';challengeBody.innerHTML=html;}
function selectOption(qIdx,optIdx){if(challengeState.submitted)return;challengeState.answers[qIdx]=optIdx;renderQuestion();}
function submitChallenge(){challengeState.submitted=true;renderQuestion();}
function nextQuestion(){challengeState.current++;challengeState.submitted=false;renderQuestion();}
function finishChallenge(){var correct=0,total=challengeState.questions.length;challengeState.questions.forEach(function(q,i){if(challengeState.answers[i]===q.a)correct++;});completionScore.textContent='You scored '+correct+'/'+total;completionOverlay.classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',init);
if(document.readyState==='complete'||document.readyState==='interactive')init();
})();
