(function(){'use strict';
const STORE='consica-theme';
const nodes=[{id:'http',name:'HTTP - Hypertext Transfer Protocol',desc:'HTTP is the foundation of web data communication. It is a request-response protocol operating in plaintext on port 80.',details:'Port: 80\nEncryption: None\nVersion: HTTP/1.1, HTTP/2, HTTP/3\nMethod: GET, POST, PUT, DELETE\nStateless: Each request is independent'},{id:'https',name:'HTTPS - HTTP Secure',desc:'HTTPS adds TLS encryption on top of HTTP. Data is encrypted using symmetric session keys established during the TLS handshake.',details:'Port: 443\nEncryption: TLS 1.3\nCertificate: X.509\nKey Exchange: ECDHE\nForward Secrecy: Yes'},{id:'GET',name:'GET Method',desc:'Requests data from a specified resource. Should only retrieve data and have no side effects (idempotent).',details:'Safe: Yes\nIdempotent: Yes\nCacheable: Yes\nBody: No\nExample: Loading a webpage'},{id:'POST',name:'POST Method',desc:'Submits data to be processed by the identified resource. Often causes a change in server state.',details:'Safe: No\nIdempotent: No\nCacheable: Only with freshness\nBody: Yes\nExample: Form submission'},{id:'PUT',name:'PUT Method',desc:'Replaces all current representations of the target resource with the request payload. Idempotent.',details:'Safe: No\nIdempotent: Yes\nCacheable: No\nBody: Yes\nExample: Update user profile'},{id:'DELETE',name:'DELETE Method',desc:'Removes the specified resource. Idempotent — repeated calls have same effect.',details:'Safe: No\nIdempotent: Yes\nCacheable: No\nBody: Optional\nExample: Delete a record'}];
const questions=[{q:'What port does HTTPS use?',opts:['80','443','22','8080'],ans:1},{q:'Which HTTP method is idempotent?',opts:['POST','PATCH','GET','Both A and B'],ans:2},{q:'What does TLS provide?',opts:['Faster speeds','Encryption','Compression','Caching'],ans:1},{q:'Which HTTP status code range indicates client errors?',opts:['2xx','3xx','4xx','5xx'],ans:2},{q:'What is the first step in TLS handshake?',opts:['ServerHello','ClientHello','Certificate','Finished'],ans:1},{q:'How does HTTPS protect data integrity?',opts:['Checksums','MAC (Message Auth Code)','Digital signature','All of the above'],ans:3}];
let speed=1,playing=false,theme='dark',rAF=null,t=0;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupNodes();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}
function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}
function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}
function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';});}}
function setupNodes(){var all=nodes.slice();all.push({id:'PATCH',name:'PATCH Method',desc:'Applies partial modifications to a resource. Less overhead than PUT for partial updates.',details:'Safe: No\nIdempotent: No\nBody: Yes\nUse case: Partial resource update\nStandard: RFC 5789'});all.forEach(function(n){var sel='[data-mode="'+n.id+'"], [data-method="'+n.id+'"], [data-status="'+n.id+'"]';var els=document.querySelectorAll(sel);els.forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo(n);});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showInfo(n);}});});});document.querySelectorAll('.client-node,.server-node').forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();var isClient=el.classList.contains('client-node');showInfo({name:isClient?'Client (Browser)':'Server (Web Server)',desc:isClient?'The client initiates HTTP requests. Browsers, mobile apps, and APIs act as clients.':'The server receives requests and returns responses. Apache, Nginx, and IIS are common servers.',details:isClient?'Role: Initiates requests\nExamples: Chrome, Firefox, cURL\nSends: HTTP request\nReceives: HTTP response':'Role: Responds to requests\nExamples: Apache, Nginx, IIS\nSends: HTTP response\nReceives: HTTP request'});});});document.addEventListener('click',function(e){if(!e.target.closest('[data-mode]')&&!e.target.closest('[data-method]')&&!e.target.closest('[data-status]')&&!e.target.closest('.client-node')&&!e.target.closest('.server-node')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}
function showInfo(node){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel)return;title.textContent=node.name;desc.textContent=node.desc;details.innerHTML='<p>'+node.details.split('\n').join('<br>')+'</p>';panel.hidden=false;}
function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}
function startRAF(){function frame(){if(playing){t+=0.025*speed;var x=250+(650-250)*((Math.sin(t)+1)/2);var f=document.getElementById('http-frame');if(f){f.setAttribute('x',x);f.setAttribute('y',225+Math.sin(t*2)*5);f.setAttribute('visibility','visible');}}rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}
function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';t=0;const f=document.getElementById('http-frame');if(f)f.setAttribute('visibility','hidden');const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}}
function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}
let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}
function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
