(function(){'use strict';
const STORE='consica-theme';
const nodes=[{id:'PC1',name:'PC1 - Internal Host',desc:'A computer on the LAN protected by the firewall. Uses private IP 192.168.1.x and accesses internet via NAT.',details:'IP: 192.168.1.10\nZone: LAN (trusted)\nAccess: Full internal + NAT to internet\nFirewall: Monitored'},{id:'PC2',name:'PC2 - Internal Host',desc:'Another workstation on the trusted LAN. All outbound traffic goes through stateful inspection.',details:'IP: 192.168.1.20\nZone: LAN (trusted)\nApplications: Web browsing, email\nSecurity: Antivirus + firewall'},{id:'Server',name:'Internal Server',desc:'A server hosting internal applications. Only accessible from LAN; blocked from WAN by default.',details:'IP: 192.168.1.50\nServices: Internal web, file share\nAccess: LAN only\nSecurity: Tightly restricted'},{id:'Attacker',name:'Attacker (WAN)',desc:'An external malicious host attempting to breach the network. Blocked by firewall rules.',details:'IP: 198.51.100.99\nZone: WAN (untrusted)\nAttempts: Port scan, SSH brute force\nStatus: Blocked by firewall'},{id:'Remote',name:'Remote Server',desc:'An external service (e.g., GitHub API) that internal hosts access through the firewall.',details:'Type: External service\nProtocol: HTTPS (port 443)\nZone: WAN\nStatus: Allowed outbound'}];
const questions=[{q:'What does NAT primarily do?',opts:['Encrypts data','Translates private IP to public IP','Blocks malware','Routes packets'],ans:1},{q:'Which firewall type tracks connection states?',opts:['Packet Filter','Stateful','Proxy','NGFW'],ans:1},{q:'What port does HTTPS use through a firewall?',opts:['80','443','22','53'],ans:1},{q:'What zone is considered untrusted?',opts:['LAN','DMZ','WAN','VLAN'],ans:2},{q:'Which is a private IP range?',opts:['203.0.113.0','192.168.1.0','93.184.216.0','8.8.8.0'],ans:1},{q:'What is deep packet inspection?',opts:['Header check','Content analysis at L7','Port blocking','MAC filtering'],ans:1}];
let speed=1,playing=false,theme='dark',rAF=null,t=0;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupNodes();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}
function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}
function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}
function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';});}}
function setupNodes(){var all=nodes.slice();all.push({id:'Printer',name:'Network Printer',desc:'A shared printer on the LAN. Accessed by internal hosts but not exposed to the internet.',details:'IP: 192.168.1.30\nProtocol: IPP (port 631)\nZone: LAN\nAccess: Internal only'});all.push({id:'Cloud',name:'Cloud Service',desc:'SaaS application accessed over HTTPS. Example: Google Workspace, Office 365.',details:'Type: SaaS\nProtocol: HTTPS\nAuthentication: OAuth 2.0\nExample: Google Drive'});all.push({id:'DNS',name:'External DNS Server',desc:'A public DNS resolver (8.8.8.8) used for domain name resolution. Allowed through firewall.',details:'IP: 8.8.8.8\nPort: 53 (UDP)\nProvider: Google\nStatus: Allowed'});all.push({id:'packet',name:'Packet Filter Firewall',desc:'The simplest firewall type. Inspects packet headers (source/dest IP, port, protocol) only.',details:'Layer: 3/4\nInspection: Headers only\nSpeed: Very fast\nLimitation: No content inspection'});all.push({id:'stateful',name:'Stateful Firewall',desc:'Tracks connection states using a state table. Can distinguish legitimate responses from unsolicited traffic.',details:'Layer: 3/4 (with tracking)\nFeature: Connection state table\nSecurity: Higher than packet filter\nExample: Windows Firewall'});all.push({id:'proxy',name:'Proxy Firewall',desc:'Acts as an intermediary. Terminates connections and re-establishes them, inspecting application data.',details:'Layer: 7 (Application)\nFeature: Full request inspection\nPrivacy: Hides internal IPs\nPerformance: Lower throughput'});all.push({id:'ngfw',name:'Next-Generation Firewall',desc:'Combines traditional firewall with IPS, application awareness, and deep packet inspection.',details:'Features: DPI, IPS, App control\nThreat Intelligence: Integrated feeds\nPerformance: Hardware accelerated\nExample: Palo Alto, Fortinet'});all.forEach(function(n){var sel='[data-host="'+n.id+'"], [data-fwtype="'+n.id+'"]';var els=document.querySelectorAll(sel);els.forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo(n);});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showInfo(n);}});});});document.querySelectorAll('.zone-lan,.zone-wan,.firewall-box,.nat-bg').forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo({name:el.getAttribute('aria-label')||'Zone',desc:'A security zone or boundary in the network.',details:'Function: Network segmentation\nSecurity: Policy enforcement\nTraffic: Monitored and filtered'});});});document.addEventListener('click',function(e){if(!e.target.closest('[data-host]')&&!e.target.closest('[data-fwtype]')&&!e.target.closest('.zone-lan')&&!e.target.closest('.zone-wan')&&!e.target.closest('.firewall-box')&&!e.target.closest('.nat-bg')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}
function showInfo(node){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel)return;title.textContent=node.name;desc.textContent=node.desc;details.innerHTML='<p>'+node.details.split('\n').join('<br>')+'</p>';panel.hidden=false;}
function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}
function startRAF(){function frame(){if(playing){t+=0.02*speed;var p1=document.getElementById('allowed-packet');var p2=document.getElementById('blocked-packet');if(p1){p1.setAttribute('cx',290+(610-290)*((Math.sin(t)+1)/2));p1.setAttribute('cy',190);p1.setAttribute('visibility','visible');}if(p2){p2.setAttribute('cx',450+80*Math.cos(t*2));p2.setAttribute('cy',190+20*Math.sin(t*2.5));p2.setAttribute('visibility','visible');}}rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}
function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';t=0;document.getElementById('allowed-packet').setAttribute('visibility','hidden');document.getElementById('blocked-packet').setAttribute('visibility','hidden');const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}}
function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}
let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}
function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
