(function(){'use strict';
var theme=localStorage.getItem('consica-theme')||'dark';
document.documentElement.setAttribute('data-theme',theme);
var app,container,skeleton,errorBoundary,errorMsg,svgContainer,infoTitle,infoDesc,stepsList,playBtn,resetBtn,speedSlider,speedVal,themeBtn,challengeOverlay,challengeBody,challengeClose,completionOverlay,completionScore,completionClose,challengeBtn,rafId,animating=false,t=0,activeNode=null,nodes=[],flowDots=[],speed=1,challengeState={questions:[],current:0,answers:{},submitted:false};
var components=[
{id:'data',name:'Labeled Dataset',sublabel:'Input-output pairs',desc:'Supervised learning requires a dataset where each example has a known label or target value.',purpose:'Provide ground truth for training',how:'Humans or processes annotate data with correct answers',why:'The model needs to know what correct looks like',analogy:'A textbook with answers at the back',funFact:'ImageNet has 14 million hand-labeled images',takeaway:'Labels are the answer key for ML',mistake:'Incorrect labels teach the model wrong patterns'},
{id:'features',name:'Feature Extraction',sublabel:'Identifying patterns',desc:'Features are measurable properties of the data that help the model make predictions.',purpose:'Convert raw data into meaningful inputs',how:'Select relevant attributes like pixel values, word frequencies, or sensor readings',why:'Better features lead to better predictions',analogy:'A detective noting key clues at a crime scene',funFact:'Feature engineering was once the most important ML skill',takeaway:'Good features capture the essence of the problem',mistake:'Irrelevant features add noise and reduce accuracy'},
{id:'model',name:'Classification Model',sublabel:'Decision boundary',desc:'A classification model learns to separate data into categories by finding a decision boundary.',purpose:'Predict discrete categories or classes',how:'Algorithms like logistic regression, SVM, or neural nets draw boundaries in feature space',why:'Many problems need yes/no or multi-class answers',analogy:'Drawing a line between apples and oranges',funFact:'A decision boundary can be linear or curved',takeaway:'Classification powers spam filters and medical diagnosis',mistake:'Non-separable data needs more complex boundaries'},
{id:'regression',name:'Regression Model',sublabel:'Continuous prediction',desc:'Regression predicts continuous numerical values rather than discrete categories.',purpose:'Forecast numeric values from inputs',how:'Fit a function mapping features to a continuous output using least squares minimization',why:'Many real problems need numbers, not categories',analogy:'Predicting house price from square footage',funFact:'Linear regression was invented in 1805 by Legendre',takeaway:'Regression is used for forecasting and estimation',mistake:'Regression cannot extrapolate reliably beyond training range'},
{id:'eval',name:'Performance Metrics',sublabel:'Measuring accuracy',desc:'Metrics quantify how well the supervised model performs on unseen test data.',purpose:'Evaluate model quality objectively',how:'Accuracy, precision, recall, F1 score, confusion matrix, MSE, R-squared',why:'Different problems need different success measures',analogy:'A report card with multiple subject grades',funFact:'99% accuracy can be terrible if classes are imbalanced',takeaway:'Choose metrics that match your business goal',mistake:'Accuracy alone can be misleading on imbalanced data'},
{id:'deploy',name:'Prediction Pipeline',sublabel:'Making predictions',desc:'The trained model is deployed to make real-time or batch predictions on new, unlabeled data.',purpose:'Apply learning to new examples',how:'Preprocess input, run through trained model, output prediction',why:'This is where the model creates value',analogy:'A doctor diagnosing new patients using medical training',funFact:'Deployed models can make millions of predictions per second',takeaway:'Deployment connects training to real-world impact',mistake:'Training-serving skew occurs when data distributions change'}
];
var connectionsData=[{from:'data',to:'features'},{from:'features',to:'model'},{from:'features',to:'regression'},{from:'model',to:'eval'},{from:'regression',to:'eval'},{from:'eval',to:'deploy'}];
var stepsData=[
{id:'data',label:'Labeled Dataset - inputs with correct answers'},
{id:'features',label:'Feature Extraction - identify meaningful data attributes'},
{id:'model',label:'Classification Model - learn decision boundaries'},
{id:'regression',label:'Regression Model - predict continuous values'},
{id:'eval',label:'Performance Metrics - measure prediction quality'},
{id:'deploy',label:'Prediction Pipeline - apply model to new data'}
];
var challenges=[
{q:'What makes supervised learning supervised?',o:['A supervisor monitors the computer','The data has known labels or answers','It requires human supervision at all times','It only works with images'],a:1},
{q:'What is the difference between classification and regression?',o:['Classification is faster','Classification predicts categories, regression predicts numbers','Regression is only for images','There is no difference'],a:1},
{q:'What happens if training data has incorrect labels?',o:['The model ignores them','The model learns wrong patterns','Training becomes faster','Labels are not important'],a:1},
{q:'Why can 99% accuracy be misleading?',o:['Because nothing is 99% accurate','When classes are imbalanced, predicting the majority class gives high accuracy','99% is always good','Accuracy is not a real metric'],a:1},
{q:'What is training-serving skew?',o:['The model is tilted','When training and production data distributions differ','Data is stored incorrectly','Servers are overloaded'],a:1},
{q:'What does a decision boundary separate?',o:['Training and test data','Different classes or categories','Features from labels','Good models from bad ones'],a:1}
];
function init(){app=document.getElementById('app');container=document.getElementById('diagram-container');skeleton=document.getElementById('loading-skeleton');errorBoundary=document.getElementById('error-boundary');errorMsg=document.getElementById('error-message');svgContainer=document.getElementById('svg-container');infoTitle=document.getElementById('info-title');infoDesc=document.getElementById('info-desc');stepsList=document.getElementById('steps-list');playBtn=document.getElementById('play-btn');resetBtn=document.getElementById('reset-btn');speedSlider=document.getElementById('speed-slider');speedVal=document.getElementById('speed-value');themeBtn=document.getElementById('theme-toggle');challengeOverlay=document.getElementById('challenge-overlay');challengeBody=document.getElementById('challenge-body');challengeClose=document.getElementById('challenge-close');completionOverlay=document.getElementById('completion-overlay');completionScore=document.getElementById('completion-score');completionClose=document.getElementById('completion-close');challengeBtn=document.getElementById('challenge-btn');
try{buildDiagram();setupControls();setupChallenge();showContainer();}catch(e){showError(e.message||'Failed to build diagram');}}
function showContainer(){skeleton.classList.add('hidden');container.classList.remove('hidden');}
function showError(msg){skeleton.classList.add('hidden');errorBoundary.classList.remove('hidden');errorMsg.textContent=msg;}
function buildDiagram(){
var W=820,H=320;var svg=svgCreate('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':'Supervised learning diagram showing labeled data through prediction pipeline'});svgContainer.appendChild(svg);
var defs=svgCreate('defs');svg.appendChild(defs);
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="var(--conn-stroke)"/></marker><marker id="arrowLight" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#94a3b8"/></marker>';
var positions={data:{x:80,y:140},features:{x:230,y:140},model:{x:400,y:70},regression:{x:400,y:230},eval:{x:560,y:150},deploy:{x:720,y:150}};
connectionsData.forEach(function(c){var f=positions[c.from],t=positions[c.to];var line;if(c.from==='features'&&c.to==='model'){line=svgCreate('line',{x1:f.x+70,y1:f.y,x2:t.x-70,y2:t.y,class:'connection-line','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}else if(c.from==='features'&&c.to==='regression'){line=svgCreate('line',{x1:f.x+70,y1:f.y,x2:t.x-70,y2:t.y,class:'connection-line','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}else if(c.to==='eval'){var d='M'+f.x+','+(f.y-26)+' Q'+((f.x+t.x)/2)+','+(Math.min(f.y,t.y)-40)+' '+t.x+','+t.y;line=svgCreate('path',{d:d,class:'connection-line',fill:'none','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}else{line=svgCreate('line',{x1:f.x+70,y1:f.y,x2:t.x-70,y2:t.y,class:'connection-line','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}svg.appendChild(line);var fd=svgCreate('circle',{class:'flow-dot',cx:0,cy:0,r:0,fill:'var(--accent)'});svg.appendChild(fd);flowDots.push({el:fd,sx:f.x+70,sy:f.y,ex:t.x-70,ey:t.y});});
components.forEach(function(cp){var p=positions[cp.id];var g=svgCreate('g',{class:'node-g',tabIndex:0,role:'button','aria-label':cp.name+': '+cp.sublabel});g.dataset.id=cp.id;var rx=svgCreate('rect',{x:p.x-70,y:p.y-26,width:140,height:52,rx:10,class:'node-rect'});g.appendChild(rx);var lbl=svgCreate('text',{x:p.x,y:p.y-4,class:'node-label'});lbl.textContent=cp.name;g.appendChild(lbl);var slbl=svgCreate('text',{x:p.x,y:p.y+14,class:'node-sublabel'});slbl.textContent=cp.sublabel;g.appendChild(slbl);g.addEventListener('click',function(){selectNode(cp.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(cp.id);}});svg.appendChild(g);nodes.push({el:g,data:cp,pos:p});});
var selected=false;components.forEach(function(c){if(!selected){selectNode(c.id);selected=true;}});renderSteps();}
function svgCreate(tag,attrs){var el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(var k in attrs)el.setAttribute(k,attrs[k]);return el;}
function selectNode(id){activeNode=id;var cp=getComp(id);if(!cp)return;nodes.forEach(function(n){var r=n.el.querySelector('.node-rect');if(r)r.classList.toggle('active',n.data.id===id);});infoTitle.textContent=cp.name+' - '+cp.sublabel;infoDesc.innerHTML='<strong>Purpose:</strong> '+cp.purpose+'<br><br><strong>How it works:</strong> '+cp.how+'<br><br><strong>Why it matters:</strong> '+cp.why+'<br><br><strong>Analogy:</strong> '+cp.analogy+(cp.funFact?'<br><br><strong>Fun fact:</strong> '+cp.funFact:'')+'<br><br><strong>Key takeaway:</strong> '+cp.takeaway+'<br><br><strong>Common mistake:</strong> '+cp.mistake;var items=stepsList.querySelectorAll('li');items.forEach(function(li){li.classList.toggle('active',li.dataset.id===id);});}
function getComp(id){for(var i=0;i<components.length;i++){if(components[i].id===id)return components[i];}return null;}
function renderSteps(){stepsList.innerHTML='';components.forEach(function(c){var li=document.createElement('li');li.dataset.id=c.id;li.textContent=c.name+' - '+c.sublabel;li.tabIndex=0;li.addEventListener('click',function(){selectNode(c.id);});li.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(c.id);}});stepsList.appendChild(li);});}
function animateDiagram(){var start=performance.now();function frame(now){if(!animating){rafId=null;return;}var dt=(now-start)/1000*speed;t=(t+dt)%1;flowDots.forEach(function(d){d.el.setAttribute('cx',d.sx+(d.ex-d.sx)*t);d.el.setAttribute('cy',d.sy+(d.ey-d.sy)*t);d.el.setAttribute('r',4);});rafId=requestAnimationFrame(frame);}rafId=requestAnimationFrame(frame);}
function setupControls(){themeBtn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem('consica-theme',theme);});playBtn.addEventListener('click',function(){animating=!animating;if(animating){playBtn.innerHTML='&#9646;&#9646;';animateDiagram();}else{playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});resetBtn.addEventListener('click',function(){t=0;flowDots.forEach(function(d){d.el.setAttribute('r',0);});if(animating){animating=false;playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});speedSlider.addEventListener('input',function(){speed=parseFloat(this.value);speedVal.textContent=speed+'x';});document.addEventListener('keydown',function(e){if(e.key==='Escape'){challengeOverlay.classList.add('hidden');completionOverlay.classList.add('hidden');}});}
function setupChallenge(){challengeBtn.addEventListener('click',function(){openChallenge();});challengeClose.addEventListener('click',function(){challengeOverlay.classList.add('hidden');});completionClose.addEventListener('click',function(){completionOverlay.classList.add('hidden');challengeOverlay.classList.add('hidden');});}
function openChallenge(){challengeState.questions=challenges.slice().sort(function(){return Math.random()-0.5;}).slice(0,5);challengeState.current=0;challengeState.answers={};challengeState.submitted=false;challengeOverlay.classList.remove('hidden');renderQuestion();}
function renderQuestion(){var q=challengeState.questions[challengeState.current];if(!q){finishChallenge();return;}var html='<div class="question"><div class="question-text">'+(challengeState.current+1)+'. '+q.q+'</div><div class="options">';q.o.forEach(function(opt,i){var sel=challengeState.answers[challengeState.current]===i?' selected':'';var cls=challengeState.submitted?(i===q.a?' correct':(challengeState.answers[challengeState.current]===i?' wrong':'')):'';html+='<label class="option-label'+sel+cls+'"><input type="radio" name="q'+challengeState.current+'" value="'+i+'"'+(challengeState.submitted?' disabled':'')+(sel?' checked':'')+' onchange="('+selectOption.toString()+')('+challengeState.current+','+i+')">'+opt+'</label>';});html+='</div></div>';html+='<div class="challenge-actions">';if(!challengeState.submitted){html+='<button class="btn-primary" onclick="('+submitChallenge.toString()+')()">Submit Answer</button>';}else{if(challengeState.current<challengeState.questions.length-1){html+='<button class="btn-primary" onclick="('+nextQuestion.toString()+')()">Next Question</button>';}else{html+='<button class="btn-primary" onclick="('+finishChallenge.toString()+')()">See Results</button>';}}html+='</div>';challengeBody.innerHTML=html;}
function selectOption(qIdx,optIdx){if(challengeState.submitted)return;challengeState.answers[qIdx]=optIdx;renderQuestion();}
function submitChallenge(){challengeState.submitted=true;renderQuestion();}
function nextQuestion(){challengeState.current++;challengeState.submitted=false;renderQuestion();}
function finishChallenge(){var correct=0,total=challengeState.questions.length;challengeState.questions.forEach(function(q,i){if(challengeState.answers[i]===q.a)correct++;});completionScore.textContent='You scored '+correct+'/'+total;completionOverlay.classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',init);
if(document.readyState==='complete'||document.readyState==='interactive')init();
})();
