(function(){'use strict';
var theme=localStorage.getItem('consica-theme')||'dark';
document.documentElement.setAttribute('data-theme',theme);
var app,container,skeleton,errorBoundary,errorMsg,svgContainer,infoTitle,infoDesc,stepsList,playBtn,resetBtn,speedSlider,speedVal,themeBtn,challengeOverlay,challengeBody,challengeClose,completionOverlay,completionScore,completionClose,challengeBtn,rafId,animating=false,t=0,activeNode=null,nodes=[],flowDots=[],speed=1,challengeState={questions:[],current:0,answers:{},submitted:false};
var components=[
{id:'health',name:'Healthcare',sublabel:'Medical AI',desc:'AI in healthcare transforms diagnosis, drug discovery, personalized treatment, and medical imaging analysis.',purpose:'Improve patient outcomes and reduce costs',how:'Deep learning on medical images, NLP on clinical notes, predictive models for patient risk',why:'Healthcare generates massive data that needs AI to interpret',analogy:'A tireless assistant doctor who never misses a detail',funFact:'AI can detect breast cancer in mammograms with 94% accuracy',takeaway:'AI augments doctors, not replaces them',mistake:'AI diagnostic models can fail on data from different hospitals'},
{id:'finance',name:'Finance',sublabel:'Algorithmic trading',desc:'AI in finance powers algorithmic trading, fraud detection, credit scoring, risk management, and personalized banking.',purpose:'Optimize financial decisions and detect fraud',how:'ML models analyze market data, transaction patterns, and credit history in real-time',why:'Millisecond decisions in markets require machine speed',analogy:'A superhuman accountant monitoring millions of transactions',funFact:'60-70% of stock trades are now executed by algorithms',takeaway:'AI makes finance faster and more secure',mistake:'Flash crashes can be triggered by interacting algorithms'},
{id:'transport',name:'Transportation',sublabel:'Autonomous mobility',desc:'AI powers self-driving cars, route optimization, traffic prediction, and logistics automation for all transportation modes.',purpose:'Make transportation safer, more efficient, and greener',how:'Computer vision perceives surroundings, RL makes driving decisions, predictive models optimize routes',why:'90% of accidents are caused by human error',analogy:'A chauffeur who never gets tired, distracted, or drunk',funFact:'Waymo has driven over 20 million autonomous miles',takeaway:'Autonomous vehicles will transform cities and logistics',mistake:'Edge cases in autonomous driving remain challenging'},
{id:'education',name:'Education',sublabel:'Personalized learning',desc:'AI in education creates personalized learning experiences, adaptive assessments, intelligent tutoring, and administrative automation.',purpose:'Personalize education for every student',how:'Adaptive learning systems adjust difficulty based on student performance, NLP tutors answer questions',why:'One-size-fits-all education fails many students',analogy:'A personal tutor who knows exactly what each student needs',funFact:'Duolingo uses AI to personalize language lessons for 500 million users',takeaway:'AI can close educational gaps at scale',mistake:'AI cannot replace human teachers social and emotional support'},
{id:'climate',name:'Climate & Energy',sublabel:'Green AI',desc:'AI helps fight climate change through energy optimization, carbon capture research, weather prediction, and smart grids.',purpose:'Reduce emissions and optimize energy usage',how:'ML models predict energy demand, optimize grid distribution, accelerate climate research',why:'Climate change is the defining challenge of our time',analogy:'A smart thermostat for the entire planet',funFact:'Google DeepMind AI reduced data center cooling costs by 40%',takeaway:'AI is a powerful tool for environmental sustainability',mistake:'AI itself has a carbon footprint from training large models'},
{id:'creative',name:'Creative Industries',sublabel:'AI-generated content',desc:'AI transforms creative fields - generating art, music, video, design, and writing, often collaborating with human creators.',purpose:'Augment human creativity with AI tools',how:'Generative models create novel content from learned patterns and user prompts',why:'Democratizes creative expression for everyone',analogy:'A creative partner who never runs out of ideas',funFact:'DALL-E 3 can generate photorealistic images from text descriptions',takeaway:'AI is a tool for creators, not a replacement for creativity',mistake:'Copyright and ownership of AI-generated content is legally complex'}
];
var connectionsData=[{from:'health',to:'finance'},{from:'finance',to:'transport'},{from:'transport',to:'education'},{from:'education',to:'climate'},{from:'climate',to:'creative'}];
var stepsData=[
{id:'health',label:'Healthcare - AI for diagnosis, drug discovery, and treatment'},
{id:'finance',label:'Finance - algorithmic trading and fraud detection'},
{id:'transport',label:'Transportation - autonomous vehicles and route optimization'},
{id:'education',label:'Education - personalized adaptive learning'},
{id:'climate',label:'Climate & Energy - sustainability and smart grids'},
{id:'creative',label:'Creative Industries - AI-generated art, music, and writing'}
];
var challenges=[
{q:'In which domain has AI achieved 94% accuracy for cancer detection?',o:['Finance','Healthcare - mammogram analysis','Transportation','Education'],a:1},
{q:'What percentage of stock trades are executed by algorithms?',o:['10-20%','40-50%','60-70%','90-100%'],a:1},
{q:'What causes 90% of traffic accidents?',o:['Weather','Human error','Vehicle malfunction','Road conditions'],a:1},
{q:'Which company uses AI to personalize language lessons for 500 million users?',o:['Google','Duolingo','Netflix','Amazon'],a:1},
{q:'How did Google DeepMind reduce data center cooling costs using AI?',o:['By 10%','By 25%','By 40%','By 60%'],a:1},
{q:'What is a key limitation of AI in education?',o:['It is too expensive','It cannot replace human teachers social support','It does not work','Students dislike it'],a:1}
];
function init(){app=document.getElementById('app');container=document.getElementById('diagram-container');skeleton=document.getElementById('loading-skeleton');errorBoundary=document.getElementById('error-boundary');errorMsg=document.getElementById('error-message');svgContainer=document.getElementById('svg-container');infoTitle=document.getElementById('info-title');infoDesc=document.getElementById('info-desc');stepsList=document.getElementById('steps-list');playBtn=document.getElementById('play-btn');resetBtn=document.getElementById('reset-btn');speedSlider=document.getElementById('speed-slider');speedVal=document.getElementById('speed-value');themeBtn=document.getElementById('theme-toggle');challengeOverlay=document.getElementById('challenge-overlay');challengeBody=document.getElementById('challenge-body');challengeClose=document.getElementById('challenge-close');completionOverlay=document.getElementById('completion-overlay');completionScore=document.getElementById('completion-score');completionClose=document.getElementById('completion-close');challengeBtn=document.getElementById('challenge-btn');
try{buildDiagram();setupControls();setupChallenge();showContainer();}catch(e){showError(e.message||'Failed to build diagram');}}
function showContainer(){skeleton.classList.add('hidden');container.classList.remove('hidden');}
function showError(msg){skeleton.classList.add('hidden');errorBoundary.classList.remove('hidden');errorMsg.textContent=msg;}
function buildDiagram(){var W=860,H=460;var svg=svgCreate('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':'AI applications across industries: Healthcare, Finance, Transportation, Education, Climate, Creative'});svgContainer.appendChild(svg);
var defs=svgCreate('defs');svg.appendChild(defs);
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="var(--conn-stroke)"/></marker><marker id="arrowLight" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#94a3b8"/></marker>';
var positions={health:{x:80,y:80},finance:{x:320,y:80},transport:{x:560,y:80},education:{x:80,y:240},climate:{x:320,y:240},creative:{x:560,y:240}};
components.forEach(function(cp){var p=positions[cp.id];var g=svgCreate('g',{class:'node-g',tabIndex:0,role:'button','aria-label':cp.name+': '+cp.sublabel});g.dataset.id=cp.id;var rx=svgCreate('rect',{x:p.x-65,y:p.y-26,width:130,height:52,rx:10,class:'node-rect'});g.appendChild(rx);var lbl=svgCreate('text',{x:p.x,y:p.y-4,class:'node-label'});lbl.textContent=cp.name;g.appendChild(lbl);var slbl=svgCreate('text',{x:p.x,y:p.y+14,class:'node-sublabel'});slbl.textContent=cp.sublabel;g.appendChild(slbl);g.addEventListener('click',function(){selectNode(cp.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(cp.id);}});svg.appendChild(g);nodes.push({el:g,data:cp,pos:p});});
connectionsData.forEach(function(c){var f=positions[c.from],t=positions[c.to];var d='M'+(f.x+65)+','+f.y+' Q'+((f.x+t.x)/2)+','+((f.y+t.y)/2)+' '+(t.x-65)+','+t.y;var line=svgCreate('path',{d:d,class:'connection-line',fill:'none','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});svg.appendChild(line);var fd=svgCreate('circle',{class:'flow-dot',cx:0,cy:0,r:0,fill:'var(--accent)'});svg.appendChild(fd);flowDots.push({el:fd,sx:f.x+65,sy:f.y,ex:t.x-65,ey:t.y});});
var selected=false;components.forEach(function(c){if(!selected){selectNode(c.id);selected=true;}});renderSteps();}
function svgCreate(tag,attrs){var el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(var k in attrs)el.setAttribute(k,attrs[k]);return el;}
function selectNode(id){activeNode=id;var cp=getComp(id);if(!cp)return;nodes.forEach(function(n){var r=n.el.querySelector('.node-rect');if(r)r.classList.toggle('active',n.data.id===id);});infoTitle.textContent=cp.name+' - '+cp.sublabel;infoDesc.innerHTML='<strong>Purpose:</strong> '+cp.purpose+'<br><br><strong>How it works:</strong> '+cp.how+'<br><br><strong>Why it matters:</strong> '+cp.why+'<br><br><strong>Analogy:</strong> '+cp.analogy+(cp.funFact?'<br><br><strong>Fun fact:</strong> '+cp.funFact:'')+'<br><br><strong>Key takeaway:</strong> '+cp.takeaway+'<br><br><strong>Common mistake:</strong> '+cp.mistake;var items=stepsList.querySelectorAll('li');items.forEach(function(li){li.classList.toggle('active',li.dataset.id===id);});}
function getComp(id){for(var i=0;i<components.length;i++){if(components[i].id===id)return components[i];}return null;}
function renderSteps(){stepsList.innerHTML='';components.forEach(function(c){var li=document.createElement('li');li.dataset.id=c.id;li.textContent=c.name+' - '+c.sublabel;li.tabIndex=0;li.addEventListener('click',function(){selectNode(c.id);});li.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(c.id);}});stepsList.appendChild(li);});}
function animateDiagram(){var start=performance.now();function frame(now){if(!animating){rafId=null;return;}var dt=(now-start)/1000*speed;t=(t+dt)%1;flowDots.forEach(function(d){d.el.setAttribute('cx',d.sx+(d.ex-d.sx)*t);d.el.setAttribute('cy',d.sy+(d.ey-d.sy)*t);d.el.setAttribute('r',4);});rafId=requestAnimationFrame(frame);}rafId=requestAnimationFrame(frame);}
function setupControls(){themeBtn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem('consica-theme',theme);});playBtn.addEventListener('click',function(){animating=!animating;if(animating){playBtn.innerHTML='&#9646;&#9646;';animateDiagram();}else{playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});resetBtn.addEventListener('click',function(){t=0;flowDots.forEach(function(d){d.el.setAttribute('r',0);});if(animating){animating=false;playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});speedSlider.addEventListener('input',function(){speed=parseFloat(this.value);speedVal.textContent=speed+'x';});document.addEventListener('keydown',function(e){if(e.key==='Escape'){challengeOverlay.classList.add('hidden');completionOverlay.classList.add('hidden');}});}
function setupChallenge(){challengeBtn.addEventListener('click',function(){openChallenge();});challengeClose.addEventListener('click',function(){challengeOverlay.classList.add('hidden');});completionClose.addEventListener('click',function(){completionOverlay.classList.add('hidden');challengeOverlay.classList.add('hidden');});}
function openChallenge(){challengeState.questions=challenges.slice().sort(function(){return Math.random()-0.5;}).slice(0,5);challengeState.current=0;challengeState.answers={};challengeState.submitted=false;challengeOverlay.classList.remove('hidden');renderQuestion();}
function renderQuestion(){var q=challengeState.questions[challengeState.current];if(!q){finishChallenge();return;}var html='<div class="question"><div class="question-text">'+(challengeState.current+1)+'. '+q.q+'</div><div class="options">';q.o.forEach(function(opt,i){var sel=challengeState.answers[challengeState.current]===i?' selected':'';var cls=challengeState.submitted?(i===q.a?' correct':(challengeState.answers[challengeState.current]===i?' wrong':'')):'';html+='<label class="option-label'+sel+cls+'"><input type="radio" name="q'+challengeState.current+'" value="'+i+'"'+(challengeState.submitted?' disabled':'')+(sel?' checked':'')+' onchange="('+selectOption.toString()+')('+challengeState.current+','+i+')">'+opt+'</label>';});html+='</div></div>';html+='<div class="challenge-actions">';if(!challengeState.submitted){html+='<button class="btn-primary" onclick="('+submitChallenge.toString()+')()">Submit Answer</button>';}else{if(challengeState.current<challengeState.questions.length-1){html+='<button class="btn-primary" onclick="('+nextQuestion.toString()+')()">Next Question</button>';}else{html+='<button class="btn-primary" onclick="('+finishChallenge.toString()+')()">See Results</button>';}}html+='</div>';challengeBody.innerHTML=html;}
function selectOption(qIdx,optIdx){if(challengeState.submitted)return;challengeState.answers[qIdx]=optIdx;renderQuestion();}
function submitChallenge(){challengeState.submitted=true;renderQuestion();}
function nextQuestion(){challengeState.current++;challengeState.submitted=false;renderQuestion();}
function finishChallenge(){var correct=0,total=challengeState.questions.length;challengeState.questions.forEach(function(q,i){if(challengeState.answers[i]===q.a)correct++;});completionScore.textContent='You scored '+correct+'/'+total;completionOverlay.classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',init);
if(document.readyState==='complete'||document.readyState==='interactive')init();
})();
