(function(){'use strict';
var theme=localStorage.getItem('consica-theme')||'dark';
document.documentElement.setAttribute('data-theme',theme);
var app,container,skeleton,errorBoundary,errorMsg,svgContainer,infoTitle,infoDesc,stepsList,playBtn,resetBtn,speedSlider,speedVal,themeBtn,challengeOverlay,challengeBody,challengeClose,completionOverlay,completionScore,completionClose,challengeBtn,rafId,animating=false,t=0,activeNode=null,nodes=[],flowDots=[],speed=1,challengeState={questions:[],current:0,answers:{},submitted:false};
var components=[
{id:'data',name:'Unlabeled Data',sublabel:'No predefined answers',desc:'Unsupervised learning works with data that has no labels or target values - just raw inputs.',purpose:'Find structure in raw data',how:'Algorithms analyze data patterns without any correct answer guidance',why:'Most real-world data is unlabeled and labeling is expensive',analogy:'Exploring a new city without a map or guide',funFact:'Over 99% of the world data is unlabeled',takeaway:'Unsupervised learning finds hidden patterns',mistake:'Without labels, evaluation is subjective'},
{id:'clustering',name:'Clustering',sublabel:'Grouping similar items',desc:'Clustering algorithms partition data into groups where items within a group are more similar to each other than to items in other groups.',purpose:'Discover natural groupings in data',how:'K-means, DBSCAN, or hierarchical clustering measure distances between data points',why:'Reveals hidden categories in unlabeled data',analogy:'Sorting a mixed pile of Lego bricks by color and shape',funFact:'K-means was developed in 1957 by Stuart Lloyd at Bell Labs',takeaway:'Clustering is used for customer segmentation and anomaly detection',mistake:'Choosing the wrong number of clusters (k) gives misleading results'},
{id:'dimension',name:'Dimensionality Reduction',sublabel:'Simplifying complex data',desc:'Reduces the number of variables in a dataset while preserving its essential structure and relationships.',purpose:'Simplify data without losing meaning',how:'PCA, t-SNE, or UMAP project high-dimensional data into fewer dimensions',why:'Visualizing and processing high-dimensional data is difficult',analogy:'Creating a 2D shadow of a 3D object to understand its shape',funFact:'PCA was invented in 1901 by Karl Pearson - before computers!',takeaway:'Dimensionality reduction helps visualize and compress data',mistake:'Information is always lost during reduction'},
{id:'assoc',name:'Association Rules',sublabel:'Finding relationships',desc:'Association rule mining discovers interesting relationships between variables in large datasets.',purpose:'Identify co-occurring patterns',how:'Apriori or FP-growth algorithms find items frequently appearing together',why:'Reveals hidden correlations in transaction data',analogy:'Noticing that people who buy diapers also buy baby wipes',funFact:'The beer and diapers association is a famous myth, not real',takeaway:'Association powers recommendation engines',mistake:'Correlation does not imply causation'},
{id:'anomaly',name:'Anomaly Detection',sublabel:'Spotting outliers',desc:'Identifies rare items, events, or observations that differ significantly from the majority of data.',purpose:'Detect unusual patterns indicating problems',how:'Isolation Forest, One-Class SVM, or autoencoders flag outliers',why:'Anomalies often signal fraud, defects, or system failures',analogy:'A security guard noticing someone running in a library',funFact:'Credit card companies use anomaly detection to flag fraud in milliseconds',takeaway:'Anomaly detection prevents fraud and equipment failure',mistake:'Normal variations can be mistaken for anomalies'},
{id:'eval',name:'Evaluation Metrics',sublabel:'Assessing clusters',desc:'Without labels, special metrics assess clustering quality - how well-separated and cohesive the groups are.',purpose:'Measure clustering quality objectively',how:'Silhouette score, Davies-Bouldin index, elbow method, inertia',why:'Good clustering is subjective without ground truth',analogy:'Judging a sorting job by how neat the piles look',funFact:'The elbow method got its name from the elbow-like bend in the inertia plot',takeaway:'Use multiple metrics to evaluate clustering',mistake:'Relying on a single metric can be misleading'}
];
var connectionsData=[{from:'data',to:'clustering'},{from:'data',to:'dimension'},{from:'data',to:'assoc'},{from:'data',to:'anomaly'},{from:'clustering',to:'eval'},{from:'dimension',to:'eval'},{from:'assoc',to:'eval'},{from:'anomaly',to:'eval'}];
var stepsData=[
{id:'data',label:'Unlabeled Data - raw inputs without answers'},
{id:'clustering',label:'Clustering - group similar data points together'},
{id:'dimension',label:'Dimensionality Reduction - simplify complex data'},
{id:'assoc',label:'Association Rules - discover co-occurring patterns'},
{id:'anomaly',label:'Anomaly Detection - spot unusual outliers'},
{id:'eval',label:'Evaluation - measure clustering quality'}
];
var challenges=[
{q:'What key feature distinguishes unsupervised from supervised learning?',o:['Unsupervised is faster','Unsupervised uses unlabeled data','Unsupervised needs more memory','Unsupervised only works with numbers'],a:1},
{q:'What is clustering used for?',o:['Labeling data','Grouping similar items together','Reducing file size','Training neural networks'],a:1},
{q:'Why would you use dimensionality reduction?',o:['To make data larger','To simplify high-dimensional data for visualization','To add more features','To create labels'],a:1},
{q:'What problem does anomaly detection solve?',o:['Labeling data','Finding unusual patterns that may indicate fraud or failure','Grouping similar items','Reducing dimensions'],a:1},
{q:'What does the silhouette score measure?',o:['How fast clustering runs','How well-separated and cohesive clusters are','How much data was used','How many clusters exist'],a:1},
{q:'Why is evaluating unsupervised learning challenging?',o:['It requires expensive hardware','There are no ground truth labels to compare against','It takes too long','Evaluation is easy'],a:1}
];
function init(){app=document.getElementById('app');container=document.getElementById('diagram-container');skeleton=document.getElementById('loading-skeleton');errorBoundary=document.getElementById('error-boundary');errorMsg=document.getElementById('error-message');svgContainer=document.getElementById('svg-container');infoTitle=document.getElementById('info-title');infoDesc=document.getElementById('info-desc');stepsList=document.getElementById('steps-list');playBtn=document.getElementById('play-btn');resetBtn=document.getElementById('reset-btn');speedSlider=document.getElementById('speed-slider');speedVal=document.getElementById('speed-value');themeBtn=document.getElementById('theme-toggle');challengeOverlay=document.getElementById('challenge-overlay');challengeBody=document.getElementById('challenge-body');challengeClose=document.getElementById('challenge-close');completionOverlay=document.getElementById('completion-overlay');completionScore=document.getElementById('completion-score');completionClose=document.getElementById('completion-close');challengeBtn=document.getElementById('challenge-btn');
try{buildDiagram();setupControls();setupChallenge();showContainer();}catch(e){showError(e.message||'Failed to build diagram');}}
function showContainer(){skeleton.classList.add('hidden');container.classList.remove('hidden');}
function showError(msg){skeleton.classList.add('hidden');errorBoundary.classList.remove('hidden');errorMsg.textContent=msg;}
function buildDiagram(){var W=820,H=440;var svg=svgCreate('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':'Unsupervised learning hub showing data connecting to clustering, dimensionality reduction, association rules, and anomaly detection'});svgContainer.appendChild(svg);
var defs=svgCreate('defs');svg.appendChild(defs);
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="var(--conn-stroke)"/></marker><marker id="arrowLight" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#94a3b8"/></marker>';
var positions={data:{x:410,y:60},clustering:{x:110,y:190},dimension:{x:270,y:190},assoc:{x:430,y:190},anomaly:{x:590,y:190},eval:{x:410,y:330}};
connectionsData.forEach(function(c){var f=positions[c.from],t=positions[c.to];
var line;if(c.from==='data'){var xOff=((t.x-f.x)/2);var d='M'+f.x+','+(f.y+26)+' Q'+((f.x+t.x)/2)+','+(f.y+60)+' '+t.x+','+(t.y-26);line=svgCreate('path',{d:d,class:'connection-line',fill:'none','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}else{var d2='M'+f.x+','+(f.y+26)+' Q'+((f.x+t.x)/2)+','+((f.y+t.y)/2+30)+' '+t.x+','+(t.y-26);line=svgCreate('path',{d:d2,class:'connection-line',fill:'none','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});}svg.appendChild(line);
var fd=svgCreate('circle',{class:'flow-dot',cx:0,cy:0,r:0,fill:'var(--accent)'});svg.appendChild(fd);flowDots.push({el:fd,sx:f.x,sy:f.y+26,ex:t.x,ey:t.y-26});});
components.forEach(function(cp){var p=positions[cp.id];var g=svgCreate('g',{class:'node-g',tabIndex:0,role:'button','aria-label':cp.name+': '+cp.sublabel});g.dataset.id=cp.id;var rx=svgCreate('rect',{x:p.x-70,y:p.y-26,width:140,height:52,rx:10,class:'node-rect'});g.appendChild(rx);var lbl=svgCreate('text',{x:p.x,y:p.y-4,class:'node-label'});lbl.textContent=cp.name;g.appendChild(lbl);var slbl=svgCreate('text',{x:p.x,y:p.y+14,class:'node-sublabel'});slbl.textContent=cp.sublabel;g.appendChild(slbl);g.addEventListener('click',function(){selectNode(cp.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(cp.id);}});svg.appendChild(g);nodes.push({el:g,data:cp,pos:p});});
var selected=false;components.forEach(function(c){if(!selected){selectNode(c.id);selected=true;}});renderSteps();}
function svgCreate(tag,attrs){var el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(var k in attrs)el.setAttribute(k,attrs[k]);return el;}
function selectNode(id){activeNode=id;var cp=getComp(id);if(!cp)return;nodes.forEach(function(n){var r=n.el.querySelector('.node-rect');if(r)r.classList.toggle('active',n.data.id===id);});infoTitle.textContent=cp.name+' - '+cp.sublabel;infoDesc.innerHTML='<strong>Purpose:</strong> '+cp.purpose+'<br><br><strong>How it works:</strong> '+cp.how+'<br><br><strong>Why it matters:</strong> '+cp.why+'<br><br><strong>Analogy:</strong> '+cp.analogy+(cp.funFact?'<br><br><strong>Fun fact:</strong> '+cp.funFact:'')+'<br><br><strong>Key takeaway:</strong> '+cp.takeaway+'<br><br><strong>Common mistake:</strong> '+cp.mistake;var items=stepsList.querySelectorAll('li');items.forEach(function(li){li.classList.toggle('active',li.dataset.id===id);});}
function getComp(id){for(var i=0;i<components.length;i++){if(components[i].id===id)return components[i];}return null;}
function renderSteps(){stepsList.innerHTML='';components.forEach(function(c){var li=document.createElement('li');li.dataset.id=c.id;li.textContent=c.name+' - '+c.sublabel;li.tabIndex=0;li.addEventListener('click',function(){selectNode(c.id);});li.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(c.id);}});stepsList.appendChild(li);});}
function animateDiagram(){var start=performance.now();function frame(now){if(!animating){rafId=null;return;}var dt=(now-start)/1000*speed;t=(t+dt)%1;flowDots.forEach(function(d){d.el.setAttribute('cx',d.sx+(d.ex-d.sx)*t);d.el.setAttribute('cy',d.sy+(d.ey-d.sy)*t);d.el.setAttribute('r',4);});rafId=requestAnimationFrame(frame);}rafId=requestAnimationFrame(frame);}
function setupControls(){themeBtn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem('consica-theme',theme);});playBtn.addEventListener('click',function(){animating=!animating;if(animating){playBtn.innerHTML='&#9646;&#9646;';animateDiagram();}else{playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});resetBtn.addEventListener('click',function(){t=0;flowDots.forEach(function(d){d.el.setAttribute('r',0);});if(animating){animating=false;playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});speedSlider.addEventListener('input',function(){speed=parseFloat(this.value);speedVal.textContent=speed+'x';});document.addEventListener('keydown',function(e){if(e.key==='Escape'){challengeOverlay.classList.add('hidden');completionOverlay.classList.add('hidden');}});}
function setupChallenge(){challengeBtn.addEventListener('click',function(){openChallenge();});challengeClose.addEventListener('click',function(){challengeOverlay.classList.add('hidden');});completionClose.addEventListener('click',function(){completionOverlay.classList.add('hidden');challengeOverlay.classList.add('hidden');});}
function openChallenge(){challengeState.questions=challenges.slice().sort(function(){return Math.random()-0.5;}).slice(0,5);challengeState.current=0;challengeState.answers={};challengeState.submitted=false;challengeOverlay.classList.remove('hidden');renderQuestion();}
function renderQuestion(){var q=challengeState.questions[challengeState.current];if(!q){finishChallenge();return;}var html='<div class="question"><div class="question-text">'+(challengeState.current+1)+'. '+q.q+'</div><div class="options">';q.o.forEach(function(opt,i){var sel=challengeState.answers[challengeState.current]===i?' selected':'';var cls=challengeState.submitted?(i===q.a?' correct':(challengeState.answers[challengeState.current]===i?' wrong':'')):'';html+='<label class="option-label'+sel+cls+'"><input type="radio" name="q'+challengeState.current+'" value="'+i+'"'+(challengeState.submitted?' disabled':'')+(sel?' checked':'')+' onchange="('+selectOption.toString()+')('+challengeState.current+','+i+')">'+opt+'</label>';});html+='</div></div>';html+='<div class="challenge-actions">';if(!challengeState.submitted){html+='<button class="btn-primary" onclick="('+submitChallenge.toString()+')()">Submit Answer</button>';}else{if(challengeState.current<challengeState.questions.length-1){html+='<button class="btn-primary" onclick="('+nextQuestion.toString()+')()">Next Question</button>';}else{html+='<button class="btn-primary" onclick="('+finishChallenge.toString()+')()">See Results</button>';}}html+='</div>';challengeBody.innerHTML=html;}
function selectOption(qIdx,optIdx){if(challengeState.submitted)return;challengeState.answers[qIdx]=optIdx;renderQuestion();}
function submitChallenge(){challengeState.submitted=true;renderQuestion();}
function nextQuestion(){challengeState.current++;challengeState.submitted=false;renderQuestion();}
function finishChallenge(){var correct=0,total=challengeState.questions.length;challengeState.questions.forEach(function(q,i){if(challengeState.answers[i]===q.a)correct++;});completionScore.textContent='You scored '+correct+'/'+total;completionOverlay.classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',init);
if(document.readyState==='complete'||document.readyState==='interactive')init();
})();
