(function(){'use strict';
try{
var components=[
{id:"app",name:"Your App",purpose:"The application that needs data or functionality from external services",desc:"Your app sends requests to APIs to retrieve data, trigger actions, or integrate with external services without knowing their internal implementation.",how:"Your app makes HTTP requests to API endpoints with authentication (API keys, OAuth tokens). Requests include method, headers, and body. The app handles responses (typically JSON) and processes data for the user. Error handling and rate limiting are critical.",why:"APIs let your app leverage existing services instead of building everything from scratch — accelerating development enormously.",analogy:"Like ordering food from a restaurant menu — you get what you want without entering the kitchen",fun:"Google alone provides over 200 different APIs for developers",takeaway:"Your app consumes APIs to access features and data built by others.",mistake:"Your app doesn't need to know how an API works internally — it only needs to follow the API contract."},
{id:"gateway",name:"API Gateway",purpose:"The central entry point that routes requests to the appropriate backend services",desc:"The API gateway sits between apps and services, handling routing, authentication, rate limiting, and request transformation as a single entry point.",how:"The gateway receives all API calls, validates API keys/JWTs, enforces rate limits, routes to appropriate microservices, aggregates responses, handles cross-cutting concerns (logging, caching, CORS), and transforms requests/responses.",why:"A gateway simplifies client code by providing a single endpoint and centralizes security, monitoring, and traffic management.",analogy:"Like a hotel front desk that directs guests to their rooms, restaurants, or services",fun:"Enterprise API gateways can process over 1 million requests per second",takeaway:"API gateways manage, secure, and route all API traffic from a single entry point.",mistake:"An API gateway is not just a reverse proxy — it handles auth, throttling, logging, and transformation."},
{id:"auth",name:"Auth Service",purpose:"Validates identities and authorizes access to protected API resources",desc:"The auth service verifies that requests come from authenticated users and have permission to access the requested resources.",how:"The auth service validates API keys, JWT tokens, or OAuth 2.0 tokens. It checks token signatures, expiration, and scopes. It may call external identity providers (Auth0, Okta) or validate against a local user database.",why:"Auth services protect API resources from unauthorized access and ensure users can only access permitted data.",analogy:"Like a security guard checking IDs before allowing entry to a building",fun:"OAuth 2.0 is used by over 80% of major web APIs for authorization",takeaway:"Auth services validate identity and enforce access control for API resources.",mistake:"Never validate auth tokens on the client — always enforce authentication server-side."},
{id:"data",name:"Data Service",purpose:"Internal service that handles database operations and data management",desc:"Data services encapsulate database access logic, providing a clean API for creating, reading, updating, and deleting data without exposing database details.",how:"Data services use ORMs or query builders to interact with databases. They implement CRUD operations, data validation, pagination, filtering, and caching. They expose REST or GraphQL endpoints for other services to consume.",why:"Data services abstract database complexity and provide consistent, secure data access to the rest of the application.",analogy:"Like a bank teller who handles all the behind-the-counter transactions for customers",fun:"Well-designed data services can be reused across multiple applications in an organization",takeaway:"Data services provide a clean API layer over database operations for other services to use.",mistake:"Data services should not contain business logic — keep them focused on data access only."},
{id:"external",name:"External API",purpose:"Third-party services that provide additional functionality like payments, maps, or email",desc:"External APIs are services built by other companies that your app can integrate with for specialized functionality — Stripe for payments, Google Maps for location, Twilio for SMS.",how:"Your app sends authenticated HTTP requests to external API endpoints. Responses are parsed and integrated into your app's functionality. Webhooks allow external services to push events to your app in real-time when something happens.",why:"External APIs let apps add powerful capabilities without building them from scratch — payment processing, maps, AI, and more.",analogy:"Like plugging into the electrical grid instead of generating your own power",fun:"Stripe processes billions of dollars in transactions every year through its API",takeaway:"External APIs enable apps to integrate specialized third-party services seamlessly.",mistake:"External APIs can change or go down — always implement graceful degradation and monitor for breaking changes."},
{id:"client",name:"Client App",purpose:"The end-user application that ultimately consumes the API output",desc:"The client app — web browser, mobile app, or desktop app — receives API responses and presents the data to users in a meaningful, interactive way.",how:"The client app calls APIs to fetch data, submits user input via POST/PUT requests, handles loading/error states, and renders the UI. Modern apps may use GraphQL to request exactly the data needed, reducing over-fetching.",why:"The client app is where all API data ultimately reaches users — without clients, APIs would have no purpose.",analogy:"Like a store display that presents products (data) to customers in an attractive, organized way",fun:"The average mobile app communicates with 5-10 different APIs",takeaway:"Client apps are the consumers of API data, presenting it to users through intuitive interfaces.",mistake:"Client apps should handle API errors gracefully — show user-friendly messages instead of raw error codes."}
];
var nodes=[{id:"app",x:50,y:45,w:120,h:48,color:"#0959C8",icon:"📱"},{id:"gateway",x:230,y:45,w:130,h:48,color:"#7c3aed",icon:"🚪"},{id:"auth",x:230,y:140,w:130,h:48,color:"#0891b2",icon:"🔑"},{id:"data",x:230,y:235,w:130,h:48,color:"#059669",icon:"💾"},{id:"external",x:410,y:140,w:130,h:48,color:"#d97706",icon:"🔗"},{id:"client",x:410,y:45,w:120,h:48,color:"#c62828",icon:"🖥"}];
var connections=[{from:"app",to:"gateway"},{from:"gateway",to:"auth"},{from:"gateway",to:"data"},{from:"gateway",to:"external"},{from:"data",to:"gateway"},{from:"external",to:"gateway"},{from:"gateway",to:"client"},{from:"client",to:"app"}];
var quiz=[
{q:"What is the primary purpose of an API?",opts:["To render web pages","To let applications communicate and share data or functionality","To store database records","To compile code"],ans:1},
{q:"What does an API gateway do?",opts:["Only load balances traffic","Routes requests, handles auth, rate limiting, and transformation","Replaces the need for a database","Compiles API code"],ans:1},
{q:"Why should auth validation happen server-side?",opts:["It's faster on the server","Client-side validation is insecure and can be bypassed","Server doesn't need auth","Auth is always optional"],ans:1},
{q:"What is the benefit of using external APIs?",opts:["They're always free","They let apps add specialized functionality without building it from scratch","They replace the need for a frontend","They eliminate the need for servers"],ans:1},
{q:"What is a webhook in the context of APIs?",opts:["A type of database","A way for external services to push real-time events to your app","A frontend framework","A CSS styling method"],ans:1},
{q:"How many APIs might a typical mobile app communicate with?",opts:["0-1","10-20","5-10","Over 100"],ans:2}
];
var app=document.getElementById('app'),skeleton=document.getElementById('skeleton'),errorBoundary=document.getElementById('error-boundary'),errorMsg=document.getElementById('error-message'),container=document.getElementById('diagram-container'),infoPanel=document.getElementById('info-panel'),infoContent=document.getElementById('info-content'),speedSlider=document.getElementById('speed-slider'),speedVal=document.getElementById('speed-val'),playBtn=document.getElementById('play-btn'),challengeSection=document.getElementById('challenge-section'),challengeQuestions=document.getElementById('challenge-questions'),challengeResult=document.getElementById('challenge-result'),completionOverlay=document.getElementById('completion-overlay'),completionScore=document.getElementById('completion-score'),completionMsg=document.getElementById('completion-msg'),challengeBtn=document.getElementById('challenge-btn'),themeToggle=document.getElementById('theme-toggle');
var t=0,playing=true,selectedId=null,theme=localStorage.getItem('consica-theme')||'dark',speed=1;
var animId=null,svg=null,flowDots=[];
function setTheme(t){document.documentElement.setAttribute('data-theme',t==='light'?'light':'');localStorage.setItem('consica-theme',t);theme=t}
function toggleTheme(){setTheme(theme==='dark'?'light':'dark')}
setTheme(theme);
function buildSVG(){var W=600,H=330,ns='http://www.w3.org/2000/svg';svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 '+W+' '+H);svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.setAttribute('role','img');svg.setAttribute('aria-label','APIs diagram');
var defs=document.createElementNS(ns,'defs');defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10" fill="var(--accent2, #3b82f6)"/></marker><linearGradient id="bg-grad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="var(--surface, #131b2e)"/><stop offset="100%" stop-color="var(--surface2, #1a2338)"/></linearGradient>';svg.appendChild(defs);
var bg=document.createElementNS(ns,'rect');bg.setAttribute('width',W);bg.setAttribute('height',H);bg.setAttribute('fill','url(#bg-grad)');bg.setAttribute('rx','12');svg.appendChild(bg);
var zones=[{label:"Client Layer",x:25,y:25,w:550,h:82,color:"rgba(9,89,200,.08)"},{label:"API Gateway",x:25,y:115,w:550,h:85,color:"rgba(124,58,237,.06)"},{label:"Backend Services",x:25,y:210,w:550,h:95,color:"rgba(5,150,105,.06)"}];
zones.forEach(function(z){var r=document.createElementNS(ns,'rect');r.setAttribute('x',z.x);r.setAttribute('y',z.y);r.setAttribute('width',z.w);r.setAttribute('height',z.h);r.setAttribute('fill',z.color);r.setAttribute('rx','8');r.setAttribute('stroke','var(--border)');r.setAttribute('stroke-width','1');svg.appendChild(r);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',z.x+10);lbl.setAttribute('y',z.y+18);lbl.setAttribute('fill','var(--text2)');lbl.setAttribute('font-size','10');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.textContent=z.label;svg.appendChild(lbl);});
connections.forEach(function(c){var from=nodes.find(function(n){return n.id===c.from});var to=nodes.find(function(n){return n.id===c.to});if(!from||!to)return;var x1=from.x+from.w/2,y1=from.y+from.h/2,x2=to.x+to.w/2,y2=to.y+to.h/2;var dx=x2-x1,dy=y2-y1,dist=Math.sqrt(dx*dx+dy*dy);var mx=from.w/2+4,my=from.h/2+4,sx=x1+(dx/dist)*mx,sy=y1+(dy/dist)*my,ex=x2-(dx/dist)*mx,ey=y2-(dy/dist)*my;var line=document.createElementNS(ns,'line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',ex);line.setAttribute('y2',ey);line.setAttribute('stroke','var(--accent2)');line.setAttribute('stroke-width','2');line.setAttribute('opacity','0.4');line.setAttribute('marker-end','url(#arrow)');svg.appendChild(line);var dot=document.createElementNS(ns,'circle');dot.setAttribute('r','4');dot.setAttribute('fill','var(--accent2)');dot.setAttribute('opacity','0.8');dot.setAttribute('class','flow-dot');svg.appendChild(dot);flowDots.push({el:dot,sx:sx,sy:sy,ex:ex,ey:ey,progress:Math.random()});});
nodes.forEach(function(n){var g=document.createElementNS(ns,'g');g.setAttribute('class','node-clickable');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',components.find(function(c){return c.id===n.id}).name);g.setAttribute('data-id',n.id);var rect=document.createElementNS(ns,'rect');rect.setAttribute('x',n.x);rect.setAttribute('y',n.y);rect.setAttribute('width',n.w);rect.setAttribute('height',n.h);rect.setAttribute('rx','8');rect.setAttribute('fill',n.color);rect.setAttribute('opacity','0.9');rect.setAttribute('class','node-bg');g.appendChild(rect);var icon=document.createElementNS(ns,'text');icon.setAttribute('x',n.x+16);icon.setAttribute('y',n.y+n.h/2+6);icon.setAttribute('font-size','18');icon.setAttribute('text-anchor','middle');icon.textContent=n.icon;g.appendChild(icon);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',n.x+30);lbl.setAttribute('y',n.y+n.h/2+5);lbl.setAttribute('fill','#fff');lbl.setAttribute('font-size','11');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.setAttribute('class','node-label');lbl.textContent=components.find(function(c){return c.id===n.id}).name;g.appendChild(lbl);g.addEventListener('click',function(){selectNode(n.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(n.id);}});svg.appendChild(g);});
container.innerHTML='';container.appendChild(svg);}
function selectNode(id){selectedId=id;var comp=components.find(function(c){return c.id===id});if(!comp)return;infoPanel.hidden=false;var html='<h3>'+comp.name+'</h3><div class="info-tags"><span class="info-tag">Purpose</span></div><p><strong>🎯 Purpose:</strong> '+comp.purpose+'</p><h4>📝 Description</h4><p>'+comp.desc+'</p><h4>⚙️ How It Works</h4><p>'+comp.how+'</p><h4>💡 Why It Matters</h4><p>'+comp.why+'</p><h4>🔗 Analogy</h4><p>'+comp.analogy+'</p><h4>🎲 Fun Fact</h4><p>'+comp.fun+'</p><h4>✅ Key Takeaway</h4><p>'+comp.takeaway+'</p><h4>⚠️ Common Mistake</h4><p>'+comp.mistake+'</p>';infoContent.innerHTML=html;infoPanel.scrollIntoView({behavior:'smooth',block:'nearest'});container.querySelectorAll('.node-clickable').forEach(function(g){if(g.getAttribute('data-id')===id)g.classList.add('node-active');else g.classList.remove('node-active');});}
function closeInfo(){infoPanel.hidden=true;selectedId=null;container.querySelectorAll('.node-active').forEach(function(g){g.classList.remove('node-active');});}
function togglePlay(){playing=!playing;playBtn.textContent=playing?'⏸ Pause':'▶ Play';playBtn.setAttribute('aria-label',playing?'Pause':'Play');}
speedSlider.addEventListener('input',function(){var v=parseInt(speedSlider.value);speed=0.25+((v/16)*3.75);speedVal.textContent=speed.toFixed(2)+'×';});
function animate(ts){if(!ts)ts=0;if(playing){t+=0.016*speed;flowDots.forEach(function(dot){dot.progress+=0.008*speed;if(dot.progress>1)dot.progress=0;var p=dot.progress;dot.el.setAttribute('cx',dot.sx+(dot.ex-dot.sx)*p);dot.el.setAttribute('cy',dot.sy+(dot.ey-dot.sy)*p);});}animId=requestAnimationFrame(animate);}
function buildChallenge(){challengeQuestions.innerHTML='';quiz.forEach(function(q,idx){var b=document.createElement('div');b.className='question-block';b.innerHTML='<h3>'+(idx+1)+'. '+q.q+'</h3>';q.opts.forEach(function(o,i){b.innerHTML+='<div class="q-option"><input type="radio" name="q'+idx+'" id="q'+idx+'_'+i+'" value="'+i+'"><label for="q'+idx+'_'+i+'">'+o+'</label></div>';});challengeQuestions.appendChild(b);});challengeBtn.hidden=false;}
function submitChallenge(){var score=0,total=quiz.length;quiz.forEach(function(q,idx){var sel=document.querySelector('input[name="q'+idx+'"]:checked');var blocks=document.querySelectorAll('.question-block');var opts=blocks[idx].querySelectorAll('.q-option');opts.forEach(function(o){o.classList.remove('correct','wrong');});var fb=blocks[idx].querySelector('.q-feedback');if(fb)fb.remove();if(sel){var val=parseInt(sel.value);if(val===q.ans){opts[q.ans].classList.add('correct');score++;}else{opts[q.ans].classList.add('correct');opts[val].classList.add('wrong');}}else{opts[q.ans].classList.add('correct');}var fbDiv=document.createElement('div');fbDiv.className='q-feedback '+(sel&&parseInt(sel.value)===q.ans?'correct':'wrong');fbDiv.textContent=sel&&parseInt(sel.value)===q.ans?'✓ Correct!':'✗ The correct answer was option '+(q.ans+1);blocks[idx].appendChild(fbDiv);});challengeResult.hidden=false;var pct=Math.round(score/total*100);challengeResult.innerHTML='<h3>Score: '+score+'/'+total+' ('+pct+'%)</h3><p>'+(pct>=80?'Excellent API knowledge!':pct>=50?'Good start! Review the API components.':'Keep exploring each API component to deepen your understanding.')+'</p>';if(pct>=80){completionOverlay.hidden=false;completionScore.textContent='You scored '+score+'/'+total+' ('+pct+'%)';completionMsg.textContent='You understand how APIs work — from gateways and auth to data services and external integrations!';}}
function closeCompletion(){completionOverlay.hidden=true;}
function showChallenge(){challengeSection.hidden=!challengeSection.hidden;if(!challengeSection.hidden)challengeSection.scrollIntoView({behavior:'smooth'});}
function init(){buildSVG();buildChallenge();animId=requestAnimationFrame(animate);challengeBtn.hidden=false;setTimeout(function(){skeleton.style.opacity='0';skeleton.style.transition='opacity .4s';setTimeout(function(){skeleton.hidden=true;},400);app.hidden=false;},600);}
init();
window.addEventListener('unload',function(){if(animId)cancelAnimationFrame(animId);});
window.selectNode=selectNode;window.closeInfo=closeInfo;window.togglePlay=togglePlay;window.toggleTheme=toggleTheme;window.showChallenge=showChallenge;window.submitChallenge=submitChallenge;window.closeCompletion=closeCompletion;
}catch(e){document.getElementById('skeleton').hidden=true;var eb=document.getElementById('error-boundary');eb.hidden=false;document.getElementById('error-message').textContent=e.message||'Failed to initialize diagram';console.error('Diagram init error:',e);}
})();