(function(){'use strict';
try{
var components=[
{id:"user",name:"User Action",purpose:"The initial trigger — a person clicks, taps, or types to start a request",desc:"Everything starts with a user action — clicking a link, submitting a form, or typing a URL. This initiates the entire request-response cycle of web communication.",how:"User actions generate browser events (click, submit, keypress). JavaScript event listeners capture these events, can prevent default behavior, validate input, and initiate HTTP requests. Each action triggers a cascade of network activity.",why:"User actions are what drive all interactions with web applications — without them, nothing happens.",analogy:"Like pressing the start button on a coffee maker that begins the brewing process",fun:"The average user performs over 200 distinct actions per day across their apps",takeaway:"User actions are the spark that ignites the entire request-response cycle.",mistake:"Not every request comes from a user — APIs, scheduled jobs, and automated processes also generate requests."},
{id:"browser",name:"Browser",purpose:"Sends HTTP requests to the server and renders the response for the user",desc:"The browser constructs and sends HTTP requests, manages the network connection, receives responses, and renders the content for the user to see and interact with.",how:"The browser's networking stack handles URL parsing, DNS resolution, TCP/TLS handshakes, HTTP request construction, and response parsing. It enforces CORS, manages cookies and cache, and handles redirects and errors.",why:"The browser is the critical intermediary between the user and the web server — it makes the web work.",analogy:"Like a telephone that connects your voice to the person you're calling",fun:"Chrome processes over 100,000 lines of code just to handle network requests",takeaway:"The browser manages the entire lifecycle of a web request from user action to visual display.",mistake:"The browser isn't just fetching pages — it manages cookies, cache, security policies, and extensions."},
{id:"dns",name:"DNS Lookup",purpose:"Resolves domain names to IP addresses so the browser can find the server",desc:"DNS (Domain Name System) translates human-readable domain names like google.com into machine-readable IP addresses that computers use to locate servers.",how:"The browser checks its cache first, then queries recursive DNS resolvers (often your ISP). The resolver queries root servers, TLD servers, and authoritative nameservers. The IP address is returned and cached for future requests.",why:"DNS makes the internet usable by letting us remember names instead of numeric IP addresses.",analogy:"Like a phone book that translates a person's name into their phone number",fun:"DNS was invented in 1983 when there were only a few hundred computers on the internet",takeaway:"DNS translates domain names to IP addresses, making websites accessible by memorable names.",mistake:"DNS changes can take hours to propagate globally due to TTL caching — plan ahead for migrations."},
{id:"internet",name:"Internet Backbone",purpose:"The global network infrastructure that carries data between clients and servers",desc:"The internet is a worldwide network of interconnected routers, fiber-optic cables, and servers that carries data packets between any connected devices.",how:"Data is broken into packets, each with source/destination IP addresses. Routers forward packets across the most efficient paths using BGP. Packets may take different routes and are reassembled at the destination. TCP ensures reliable delivery.",why:"The internet backbone is the physical infrastructure that makes global communication possible.",analogy:"Like a global highway system that connects cities and countries for transportation",fun:"Over 95% of global internet traffic travels through undersea fiber-optic cables",takeaway:"The internet backbone provides the physical and logical infrastructure for global data transfer.",mistake:"The internet is not a single network — it's a network of networks operating cooperatively."},
{id:"server",name:"Web Server",purpose:"Processes incoming HTTP requests and generates responses with the requested content",desc:"The web server receives the HTTP request, processes it by running application code, queries databases if needed, and generates an HTTP response to send back.",how:"The server parses the HTTP method, path, headers, and body. It routes to appropriate handler code, which may query databases, call APIs, or render templates. The response includes status code, headers, and body (HTML, JSON, etc.).",why:"Web servers are the destination of every request — they hold and serve the content users want.",analogy:"Like a restaurant kitchen that receives orders and prepares the requested dishes",fun:"A well-configured web server can handle over 100,000 requests per second",takeaway:"Web servers process requests by running application code and returning appropriate responses.",mistake:"Servers need proper error handling — always return appropriate HTTP status codes and error messages."},
{id:"response",name:"Response Flow",purpose:"The data sent back from the server through the network to the browser",desc:"The response travels back through the internet, possibly through the same or different routers, to the browser which processes and renders it.",how:"The response packet follows the same TCP connection established during the request. The browser receives it, checks the status code, parses headers, and processes the body — rendering HTML, parsing JSON, or handling files.",why:"The response completes the request-response cycle and delivers the value to the user.",analogy:"Like receiving your ordered package delivered to your door",fun:"A single web page often requires 50-100 separate HTTP requests to fully load",takeaway:"The response is the delivery of requested content that completes the client-server interaction.",mistake:"Large responses slow down page loads — always optimize images, minify code, and use compression."}
];
var nodes=[{id:"user",x:60,y:50,w:120,h:48,color:"#0891b2",icon:"👤"},{id:"browser",x:230,y:50,w:120,h:48,color:"#0959C8",icon:"🌐"},{id:"dns",x:60,y:140,w:120,h:48,color:"#7c3aed",icon:"📖"},{id:"internet",x:230,y:140,w:120,h:48,color:"#d97706",icon:"🌍"},{id:"server",x:400,y:95,w:120,h:48,color:"#059669",icon:"🖥"},{id:"response",x:400,y:190,w:120,h:48,color:"#c62828",icon:"📨"}];
var connections=[{from:"user",to:"browser"},{from:"browser",to:"dns"},{from:"dns",to:"internet"},{from:"internet",to:"server"},{from:"server",to:"response"},{from:"response",to:"browser"},{from:"browser",to:"user"}];
var quiz=[
{q:"What happens first when a user types a URL in the browser?",opts:["The server processes the request","The browser checks its cache and performs DNS lookup","The response is rendered on screen","The database is queried"],ans:1},
{q:"What does DNS do?",opts:["Encrypts internet traffic","Translates domain names to IP addresses","Renders web pages","Stores website files"],ans:1},
{q:"How does data travel across the internet?",opts:["As a single large file","Broken into packets routed through multiple paths","Through direct satellite connection","As radio waves"],ans:1},
{q:"What is the web server's primary role?",opts:["Display web pages","Process incoming HTTP requests and generate responses","Manage DNS records","Encrypt data"],ans:1},
{q:"How does the response travel back to the browser?",opts:["Through a completely different network","Through the same TCP connection established during the request","Through a separate DNS query","Via email protocol"],ans:1},
{q:"How many separate HTTP requests might a single web page require?",opts:["1-2","Always exactly 1","50-100 or more","None — web pages don't use HTTP"],ans:2}
];
var app=document.getElementById('app'),skeleton=document.getElementById('skeleton'),errorBoundary=document.getElementById('error-boundary'),errorMsg=document.getElementById('error-message'),container=document.getElementById('diagram-container'),infoPanel=document.getElementById('info-panel'),infoContent=document.getElementById('info-content'),speedSlider=document.getElementById('speed-slider'),speedVal=document.getElementById('speed-val'),playBtn=document.getElementById('play-btn'),challengeSection=document.getElementById('challenge-section'),challengeQuestions=document.getElementById('challenge-questions'),challengeResult=document.getElementById('challenge-result'),completionOverlay=document.getElementById('completion-overlay'),completionScore=document.getElementById('completion-score'),completionMsg=document.getElementById('completion-msg'),challengeBtn=document.getElementById('challenge-btn'),themeToggle=document.getElementById('theme-toggle');
var t=0,playing=true,selectedId=null,theme=localStorage.getItem('consica-theme')||'dark',speed=1;
var animId=null,svg=null,flowDots=[];
function setTheme(t){document.documentElement.setAttribute('data-theme',t==='light'?'light':'');localStorage.setItem('consica-theme',t);theme=t}
function toggleTheme(){setTheme(theme==='dark'?'light':'dark')}
setTheme(theme);
function buildSVG(){var W=600,H=300,ns='http://www.w3.org/2000/svg';svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 '+W+' '+H);svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.setAttribute('role','img');svg.setAttribute('aria-label','Client-server communication flow');
var defs=document.createElementNS(ns,'defs');defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10" fill="var(--accent2, #3b82f6)"/></marker><linearGradient id="bg-grad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="var(--surface, #131b2e)"/><stop offset="100%" stop-color="var(--surface2, #1a2338)"/></linearGradient>';svg.appendChild(defs);
var bg=document.createElementNS(ns,'rect');bg.setAttribute('width',W);bg.setAttribute('height',H);bg.setAttribute('fill','url(#bg-grad)');bg.setAttribute('rx','12');svg.appendChild(bg);
var zones=[{label:"Client Side",x:30,y:25,w:340,h:95,color:"rgba(9,89,200,.08)"},{label:"Infrastructure",x:30,y:125,w:240,h:80,color:"rgba(124,58,237,.06)"},{label:"Server Side",x:370,y:60,w:210,h:200,color:"rgba(5,150,105,.06)"}];
zones.forEach(function(z){var r=document.createElementNS(ns,'rect');r.setAttribute('x',z.x);r.setAttribute('y',z.y);r.setAttribute('width',z.w);r.setAttribute('height',z.h);r.setAttribute('fill',z.color);r.setAttribute('rx','8');r.setAttribute('stroke','var(--border)');r.setAttribute('stroke-width','1');svg.appendChild(r);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',z.x+10);lbl.setAttribute('y',z.y+18);lbl.setAttribute('fill','var(--text2)');lbl.setAttribute('font-size','10');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.textContent=z.label;svg.appendChild(lbl);});
connections.forEach(function(c){var from=nodes.find(function(n){return n.id===c.from});var to=nodes.find(function(n){return n.id===c.to});if(!from||!to)return;var x1=from.x+from.w/2,y1=from.y+from.h/2,x2=to.x+to.w/2,y2=to.y+to.h/2;var dx=x2-x1,dy=y2-y1,dist=Math.sqrt(dx*dx+dy*dy);var mx=from.w/2+4,my=from.h/2+4,sx=x1+(dx/dist)*mx,sy=y1+(dy/dist)*my,ex=x2-(dx/dist)*mx,ey=y2-(dy/dist)*my;var line=document.createElementNS(ns,'line');line.setAttribute('x1',sx);line.setAttribute('y1',sy);line.setAttribute('x2',ex);line.setAttribute('y2',ey);line.setAttribute('stroke','var(--accent2)');line.setAttribute('stroke-width','2');line.setAttribute('opacity','0.4');line.setAttribute('marker-end','url(#arrow)');svg.appendChild(line);var dot=document.createElementNS(ns,'circle');dot.setAttribute('r','4');dot.setAttribute('fill','var(--accent2)');dot.setAttribute('opacity','0.8');dot.setAttribute('class','flow-dot');svg.appendChild(dot);flowDots.push({el:dot,sx:sx,sy:sy,ex:ex,ey:ey,progress:Math.random()});});
nodes.forEach(function(n){var g=document.createElementNS(ns,'g');g.setAttribute('class','node-clickable');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',components.find(function(c){return c.id===n.id}).name);g.setAttribute('data-id',n.id);var rect=document.createElementNS(ns,'rect');rect.setAttribute('x',n.x);rect.setAttribute('y',n.y);rect.setAttribute('width',n.w);rect.setAttribute('height',n.h);rect.setAttribute('rx','8');rect.setAttribute('fill',n.color);rect.setAttribute('opacity','0.9');rect.setAttribute('class','node-bg');g.appendChild(rect);var icon=document.createElementNS(ns,'text');icon.setAttribute('x',n.x+16);icon.setAttribute('y',n.y+n.h/2+6);icon.setAttribute('font-size','18');icon.setAttribute('text-anchor','middle');icon.textContent=n.icon;g.appendChild(icon);var lbl=document.createElementNS(ns,'text');lbl.setAttribute('x',n.x+30);lbl.setAttribute('y',n.y+n.h/2+5);lbl.setAttribute('fill','#fff');lbl.setAttribute('font-size','11');lbl.setAttribute('font-weight','600');lbl.setAttribute('font-family',"'Inter',sans-serif");lbl.setAttribute('class','node-label');lbl.textContent=components.find(function(c){return c.id===n.id}).name;g.appendChild(lbl);g.addEventListener('click',function(){selectNode(n.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(n.id);}});svg.appendChild(g);});
container.innerHTML='';container.appendChild(svg);}
function selectNode(id){selectedId=id;var comp=components.find(function(c){return c.id===id});if(!comp)return;infoPanel.hidden=false;var html='<h3>'+comp.name+'</h3><div class="info-tags"><span class="info-tag">Purpose</span></div><p><strong>🎯 Purpose:</strong> '+comp.purpose+'</p><h4>📝 Description</h4><p>'+comp.desc+'</p><h4>⚙️ How It Works</h4><p>'+comp.how+'</p><h4>💡 Why It Matters</h4><p>'+comp.why+'</p><h4>🔗 Analogy</h4><p>'+comp.analogy+'</p><h4>🎲 Fun Fact</h4><p>'+comp.fun+'</p><h4>✅ Key Takeaway</h4><p>'+comp.takeaway+'</p><h4>⚠️ Common Mistake</h4><p>'+comp.mistake+'</p>';infoContent.innerHTML=html;infoPanel.scrollIntoView({behavior:'smooth',block:'nearest'});container.querySelectorAll('.node-clickable').forEach(function(g){if(g.getAttribute('data-id')===id)g.classList.add('node-active');else g.classList.remove('node-active');});}
function closeInfo(){infoPanel.hidden=true;selectedId=null;container.querySelectorAll('.node-active').forEach(function(g){g.classList.remove('node-active');});}
function togglePlay(){playing=!playing;playBtn.textContent=playing?'⏸ Pause':'▶ Play';playBtn.setAttribute('aria-label',playing?'Pause':'Play');}
speedSlider.addEventListener('input',function(){var v=parseInt(speedSlider.value);speed=0.25+((v/16)*3.75);speedVal.textContent=speed.toFixed(2)+'×';});
function animate(ts){if(!ts)ts=0;if(playing){t+=0.016*speed;flowDots.forEach(function(dot){dot.progress+=0.008*speed;if(dot.progress>1)dot.progress=0;var p=dot.progress;dot.el.setAttribute('cx',dot.sx+(dot.ex-dot.sx)*p);dot.el.setAttribute('cy',dot.sy+(dot.ey-dot.sy)*p);});}animId=requestAnimationFrame(animate);}
function buildChallenge(){challengeQuestions.innerHTML='';quiz.forEach(function(q,idx){var b=document.createElement('div');b.className='question-block';b.innerHTML='<h3>'+(idx+1)+'. '+q.q+'</h3>';q.opts.forEach(function(o,i){b.innerHTML+='<div class="q-option"><input type="radio" name="q'+idx+'" id="q'+idx+'_'+i+'" value="'+i+'"><label for="q'+idx+'_'+i+'">'+o+'</label></div>';});challengeQuestions.appendChild(b);});challengeBtn.hidden=false;}
function submitChallenge(){var score=0,total=quiz.length;quiz.forEach(function(q,idx){var sel=document.querySelector('input[name="q'+idx+'"]:checked');var blocks=document.querySelectorAll('.question-block');var opts=blocks[idx].querySelectorAll('.q-option');opts.forEach(function(o){o.classList.remove('correct','wrong');});var fb=blocks[idx].querySelector('.q-feedback');if(fb)fb.remove();if(sel){var val=parseInt(sel.value);if(val===q.ans){opts[q.ans].classList.add('correct');score++;}else{opts[q.ans].classList.add('correct');opts[val].classList.add('wrong');}}else{opts[q.ans].classList.add('correct');}var fbDiv=document.createElement('div');fbDiv.className='q-feedback '+(sel&&parseInt(sel.value)===q.ans?'correct':'wrong');fbDiv.textContent=sel&&parseInt(sel.value)===q.ans?'✓ Correct!':'✗ The correct answer was option '+(q.ans+1);blocks[idx].appendChild(fbDiv);});challengeResult.hidden=false;var pct=Math.round(score/total*100);challengeResult.innerHTML='<h3>Score: '+score+'/'+total+' ('+pct+'%)</h3><p>'+(pct>=80?'Excellent! You understand the request-response cycle.':pct>=50?'Good progress! Review the flow components.':'Keep exploring — click each node to trace the request journey.')+'</p>';if(pct>=80){completionOverlay.hidden=false;completionScore.textContent='You scored '+score+'/'+total+' ('+pct+'%)';completionMsg.textContent='You now understand how a request travels from user action through DNS, internet, and server, and back!';}}
function closeCompletion(){completionOverlay.hidden=true;}
function showChallenge(){challengeSection.hidden=!challengeSection.hidden;if(!challengeSection.hidden)challengeSection.scrollIntoView({behavior:'smooth'});}
function init(){buildSVG();buildChallenge();animId=requestAnimationFrame(animate);challengeBtn.hidden=false;setTimeout(function(){skeleton.style.opacity='0';skeleton.style.transition='opacity .4s';setTimeout(function(){skeleton.hidden=true;},400);app.hidden=false;},600);}
init();
window.addEventListener('unload',function(){if(animId)cancelAnimationFrame(animId);});
window.selectNode=selectNode;window.closeInfo=closeInfo;window.togglePlay=togglePlay;window.toggleTheme=toggleTheme;window.showChallenge=showChallenge;window.submitChallenge=submitChallenge;window.closeCompletion=closeCompletion;
}catch(e){document.getElementById('skeleton').hidden=true;var eb=document.getElementById('error-boundary');eb.hidden=false;document.getElementById('error-message').textContent=e.message||'Failed to initialize diagram';console.error('Diagram init error:',e);}
})();