(function(){'use strict';
var components = [
  {id:"rack",name:"Server Rack",category:"Hardware",icon:"server",shape:"rounded-rect",x:30,y:24,w:110,h:56,purpose:"Holds and organizes servers, networking gear, and cooling in a vertical stack",description:"A standard 42U rack houses multiple servers stacked vertically, with organized cabling and power distribution across all units.",why:"Racks maximize space efficiency in data centers",analogy:"Like a multi-story parking garage for computer servers",funFact:"A fully loaded rack can weigh over 2,000 pounds",takeaway:"Racks standardize the layout and cooling of data center equipment",mistake:"Racks aren\\'t just shelves\u2014they include power distribution and cable management",descriptionDetailed:"Standard 19-inch racks use U units (1U = 1.75 inches) to measure height. Racks have vertical mounting rails and include cable management arms and power distribution units. They often have front and rear doors for security and airflow."},
  {id:"server",name:"Data Center Server",category:"Hardware",icon:"server",shape:"rounded-rect",x:210,y:24,w:110,h:56,purpose:"Processes and stores data for applications and services hosted in the data center",description:"Servers are blade or rack-mount computers designed for continuous operation with redundant power, remote management, and high reliability.",why:"Servers are the workhorses that power all cloud services and websites",analogy:"Like an industrial-grade computer that never sleeps",funFact:"Google\\'s data centers contain millions of servers working together",takeaway:"Data center servers are designed for density, efficiency, and uptime",mistake:"These servers don\\'t have monitors or keyboards\u2014they\\'re managed remotely",descriptionDetailed:"Data center servers have dual power supplies, out-of-band management (iLO, iDRAC), and hot-swappable components. They run virtualization software to maximize utilization. Servers are networked via top-of-rack switches connecting to the data center fabric."},
  {id:"cooling",name:"Cooling System",category:"Hardware",icon:"fan",shape:"cylinder",x:30,y:128,w:110,h:56,purpose:"Removes the massive heat generated by thousands of running servers",description:"Cooling systems use chilled water, computer room air handlers, and precision air conditioning to maintain optimal temperatures.",why:"Without cooling, servers would overheat and fail within minutes",analogy:"Like an air conditioning system for a stadium full of running athletes",funFact:"Data centers consume about 1% of all global electricity, with 40% going to cooling",takeaway:"Cooling is one of the biggest operational costs in a data center",mistake:"Data centers don\\'t just use AC\u2014many use free air cooling or liquid cooling",descriptionDetailed:"Hot aisle/cold aisle containment separates intake and exhaust air to improve efficiency. Some data centers use direct-to-chip liquid cooling or immersion cooling. Modern cooling uses variable-speed fans and AI optimization."},
  {id:"power",name:"Power Infrastructure",category:"Hardware",icon:"power",shape:"rounded-rect",x:210,y:128,w:110,h:56,purpose:"Provides reliable, uninterrupted electricity to all data center equipment",description:"Power systems include utility feeds, backup generators, UPS batteries, and power distribution units that deliver clean power to every rack.",why:"Data centers must stay online even during grid power failures",analogy:"Like a hospital with backup generators that keep life support running during a blackout",funFact:"A large data center can consume as much power as a small city of 50,000 homes",takeaway:"Redundant power systems ensure data centers never go offline",mistake:"UPS batteries don\\'t run the data center for hours\u2014they bridge until generators start",descriptionDetailed:"Power enters at medium voltage and is stepped down through transformers. UPS systems provide battery power for 5-15 minutes until generators start. Power Distribution Units step down to 208V or 120V for rack equipment."},
  {id:"firewall",name:"Data Center Firewall",category:"Security",icon:"shield",shape:"rounded-rect",x:30,y:232,w:110,h:56,purpose:"Protects the data center from cyber threats and unauthorized access",description:"Enterprise firewalls inspect all traffic entering and leaving the data center, applying security policies, detecting intrusions, and blocking attacks.",why:"Data centers are prime targets for cyber attacks and need robust defenses",analogy:"Like the security checkpoint at a military base checking every vehicle entering",funFact:"Enterprise firewalls can inspect traffic at speeds of 100 Gbps or more",takeaway:"Data center firewalls are far more powerful than home or office firewalls",mistake:"A data center doesn\\'t rely on a single firewall\u2014it uses multiple layers of defense",descriptionDetailed:"Next-generation firewalls combine traditional packet filtering with intrusion prevention and application awareness. They are deployed in redundant pairs to avoid single points of failure."},
  {id:"backup",name:"Backup Systems",category:"Storage",icon:"database",shape:"cylinder",x:210,y:232,w:110,h:56,purpose:"Creates redundant copies of data to prevent permanent loss",description:"Backup systems regularly copy data to separate storage\u2014often in different geographic locations\u2014and enable recovery from accidental deletion or disasters.",why:"Backups protect against data loss from hardware failure, human error, or natural disasters",analogy:"Like having a spare key to your house stored at a friend\\'s place across town",funFact:"Many data centers follow the 3-2-1 backup rule: 3 copies, 2 media types, 1 off-site",takeaway:"Regular backups are the insurance policy against catastrophic data loss",mistake:"Backups aren\\'t just copies\u2014they must be tested through actual restoration",descriptionDetailed:"Backup strategies include full, incremental, and differential backups. Data is deduplicated and compressed to reduce storage needs. Replication provides real-time copies to geographically distant data centers."}
];
var connections = [{from:"rack",to:"server"},{from:"server",to:"cooling"},{from:"cooling",to:"power"},{from:"power",to:"firewall"},{from:"firewall",to:"backup"}];
var steps = [{label:"Step 1: Server Rack",status:"Exploring: Server Rack - Holds and organizes servers, networking gear, and cooling in a vertical stack"},{label:"Step 2: Data Center Server",status:"Exploring: Data Center Server - Processes and stores data for applications and services hosted in the data center"},{label:"Step 3: Cooling System",status:"Exploring: Cooling System - Removes the massive heat generated by thousands of running servers"},{label:"Step 4: Power Infrastructure",status:"Exploring: Power Infrastructure - Provides reliable, uninterrupted electricity to all data center equipment"},{label:"Step 5: Data Center Firewall",status:"Exploring: Data Center Firewall - Protects the data center from cyber threats and unauthorized access"},{label:"Step 6: Backup Systems",status:"Exploring: Backup Systems - Creates redundant copies of data to prevent permanent loss"}];
var tour = [{title:"Server Rack",description:"Holds and organizes servers, networking gear, and cooling in a vertical stack",componentId:"rack"},{title:"Data Center Server",description:"Processes and stores data for applications and services hosted in the data center",componentId:"server"},{title:"Cooling System",description:"Removes the massive heat generated by thousands of running servers",componentId:"cooling"},{title:"Power Infrastructure",description:"Provides reliable, uninterrupted electricity to all data center equipment",componentId:"power"},{title:"Data Center Firewall",description:"Protects the data center from cyber threats and unauthorized access",componentId:"firewall"},{title:"Backup Systems",description:"Creates redundant copies of data to prevent permanent loss",componentId:"backup"}];

deferInit(function(){
  new DiagramEngine({
    title: 'Data Center',
    subtitle: 'How Internet Works',
    desc: 'Discover the components inside a modern data center.',
    components: components,
    connections: connections,
    steps: steps,
    tour: tour,
    packetFlow: [
      {label:'Request',color:'#22c55e'},
      {label:'Process',color:'#60a5fa'},
      {label:'Cool',color:'#c084fc'},
      {label:'Power',color:'#f59e0b'},
      {label:'Response',color:'#22c55e'}
    ],

    render: function(container, engine) {
      engine.buildVisual(container);
      engine._setStatus('Click any component to learn more');
    },

    animate: function(engine) {
      var svg = engine.el.visual.querySelector('svg');
      if (!svg || engine.selectedId || !engine.playing) return;
      var comps = svg.querySelectorAll('.component');
      var idx = Math.floor(engine.t * 0.5) % comps.length;
      comps.forEach(function(el, i) {
        var bg = el.querySelector('.component-bg');
        if (!bg) return;
        var shape = bg.querySelector(':scope > :first-child');
        if(!shape)return;
        shape.setAttribute('fill', i === idx ? '#1e2d50' : '#1a2235');
        shape.setAttribute('stroke', i === idx ? '#0959C8' : '#2a3a55');
      });
    },

    onReplay: function(engine) {
      engine.t = 0;
    }
  });
});
})();
