(function(){'use strict';
var theme=localStorage.getItem('consica-theme')||'dark';
document.documentElement.setAttribute('data-theme',theme);
var app,container,skeleton,errorBoundary,errorMsg,svgContainer,infoTitle,infoDesc,stepsList,playBtn,resetBtn,speedSlider,speedVal,themeBtn,challengeOverlay,challengeBody,challengeClose,completionOverlay,completionScore,completionClose,challengeBtn,rafId,animating=false,t=0,activeNode=null,nodes=[],flowDots=[],speed=1,challengeState={questions:[],current:0,answers:{},submitted:false};
var components=[
{id:'fairness',name:'Fairness',sublabel:'Equal treatment',desc:'AI fairness ensures that models do not discriminate against individuals or groups based on protected attributes.',purpose:'Prevent bias and discrimination in AI decisions',how:'Audit training data for bias, use fairness metrics, apply debiasing techniques',why:'Biased AI can harm marginalized communities at scale',analogy:'A judge who treats every defendant the same regardless of background',funFact:'Amazon scrapped an AI hiring tool because it discriminated against women',takeaway:'Fairness must be designed in, not added later',mistake:'Fairness is not the same as equal outcomes - context matters'},
{id:'transparency',name:'Transparency',sublabel:'Explainable AI',desc:'Transparency means AI systems should be understandable and their decisions explainable to users and stakeholders.',purpose:'Make AI decisions understandable to humans',how:'Provide feature importance explanations, decision trees, or LIME/SHAP explanations',why:'Users need to trust and verify AI decisions',analogy:'A doctor explaining why they prescribed a specific treatment',funFact:'The EU AI Act requires explainability for high-risk AI systems',takeaway:'Black-box AI is unacceptable in high-stakes domains',mistake:'Explainability methods can be misleading if not validated'},
{id:'privacy',name:'Privacy',sublabel:'Data protection',desc:'AI privacy involves protecting personal data used for training and inference, preventing unauthorized access or re-identification.',purpose:'Protect individuals personal information',how:'Differential privacy, federated learning, data anonymization, encryption',why:'AI systems often require large amounts of personal data',analogy:'A locked diary that only you can read',funFact:'Differential privacy adds mathematical noise to protect individual records',takeaway:'Privacy is a fundamental right, not an obstacle',mistake:'Anonymization alone is often insufficient'},
{id:'accountability',name:'Accountability',sublabel:'Responsibility',desc:'Accountability means there are clear lines of responsibility for AI system behavior, outcomes, and harms.',purpose:'Ensure someone is responsible for AI outcomes',how:'Document model cards, maintain audit trails, assign human oversight',why:'AI systems can cause real harm - someone must answer',analogy:'A captain responsible for their ship',funFact:'Model cards are like nutrition labels for ML models',takeaway:'Accountability prevents blame-shifting when AI fails',mistake:'The computer did it is never an acceptable excuse'},
{id:'safety',name:'Safety',sublabel:'Robustness',desc:'AI safety ensures systems are robust, reliable, and do not cause unintended harm even in unexpected situations.',purpose:'Prevent AI systems from causing harm',how:'Red teaming, adversarial training, thorough testing, fail-safes, monitoring',why:'Unsafe AI can cause physical, financial, or social damage',analogy:'A car with airbags, seatbelts, and collision avoidance',funFact:'Red teaming involves ethical hackers trying to break AI systems',takeaway:'Safety is especially critical for physical AI (robots, cars)',mistake:'Adversarial examples can fool AI in ways humans cannot see'},
{id:'governance',name:'Governance',sublabel:'Rules & oversight',desc:'AI governance establishes the policies, standards, and oversight mechanisms to ensure responsible AI development and deployment.',purpose:'Create and enforce responsible AI standards',how:'Ethics boards, regulatory compliance, internal guidelines, third-party audits',why:'Self-regulation alone is insufficient for powerful AI',analogy:'Traffic laws that keep roads safe for everyone',funFact:'Over 60 countries have proposed or enacted AI regulations',takeaway:'Governance ensures AI benefits society broadly',mistake:'Regulation must balance innovation with protection'}
];
var connectionsData=[{from:'fairness',to:'transparency'},{from:'transparency',to:'privacy'},{from:'privacy',to:'accountability'},{from:'accountability',to:'safety'},{from:'safety',to:'governance'}];
var stepsData=[
{id:'fairness',label:'Fairness - prevent bias and discrimination'},
{id:'transparency',label:'Transparency - make AI decisions explainable'},
{id:'privacy',label:'Privacy - protect personal data'},
{id:'accountability',label:'Accountability - clear responsibility for outcomes'},
{id:'safety',label:'Safety - ensure robustness and prevent harm'},
{id:'governance',label:'Governance - rules, standards, and oversight'}
];
var challenges=[
{q:'Why did Amazon scrap its AI hiring tool?',o:['It was too expensive','It discriminated against women','It was too slow','No one used it'],a:1},
{q:'What is differential privacy?',o:['Making data public','Adding mathematical noise to protect individual records','Encrypting all data','Deleting personal data'],a:1},
{q:'What does transparency in AI mean?',o:['AI decisions should be explainable','AI should be open source','AI should be fast','AI should use transparent colors'],a:1},
{q:'Why is accountability important in AI?',o:['It makes AI faster','Someone must be responsible for outcomes and harms','It reduces costs','It improves accuracy'],a:1},
{q:'What is red teaming in AI safety?',o:['Designing red-colored interfaces','Ethical hackers trying to break AI systems','Team sports for AI developers','Writing red code'],a:1},
{q:'How many countries have proposed AI regulations?',o:['About 10','Over 60','Exactly 100','None'],a:1}
];
function init(){app=document.getElementById('app');container=document.getElementById('diagram-container');skeleton=document.getElementById('loading-skeleton');errorBoundary=document.getElementById('error-boundary');errorMsg=document.getElementById('error-message');svgContainer=document.getElementById('svg-container');infoTitle=document.getElementById('info-title');infoDesc=document.getElementById('info-desc');stepsList=document.getElementById('steps-list');playBtn=document.getElementById('play-btn');resetBtn=document.getElementById('reset-btn');speedSlider=document.getElementById('speed-slider');speedVal=document.getElementById('speed-value');themeBtn=document.getElementById('theme-toggle');challengeOverlay=document.getElementById('challenge-overlay');challengeBody=document.getElementById('challenge-body');challengeClose=document.getElementById('challenge-close');completionOverlay=document.getElementById('completion-overlay');completionScore=document.getElementById('completion-score');completionClose=document.getElementById('completion-close');challengeBtn=document.getElementById('challenge-btn');
try{buildDiagram();setupControls();setupChallenge();showContainer();}catch(e){showError(e.message||'Failed to build diagram');}}
function showContainer(){skeleton.classList.add('hidden');container.classList.remove('hidden');}
function showError(msg){skeleton.classList.add('hidden');errorBoundary.classList.remove('hidden');errorMsg.textContent=msg;}
function buildDiagram(){var W=860,H=440;var svg=svgCreate('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':'AI ethics pillars: Fairness, Transparency, Privacy, Accountability, Safety, Governance'});svgContainer.appendChild(svg);
var defs=svgCreate('defs');svg.appendChild(defs);
defs.innerHTML='<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="var(--conn-stroke)"/></marker><marker id="arrowLight" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#94a3b8"/></marker>';
var positions={fairness:{x:410,y:50},transparency:{x:200,y:170},privacy:{x:620,y:170},accountability:{x:200,y:310},safety:{x:620,y:310},governance:{x:410,y:410}};
connectionsData.forEach(function(c){var f=positions[c.from],t=positions[c.to];var d='M'+f.x+','+(f.y+26)+' Q'+((f.x+t.x)/2)+','+((f.y+t.y)/2+20)+' '+t.x+','+(t.y-26);var line=svgCreate('path',{d:d,class:'connection-line',fill:'none','marker-end':theme==='light'?'url(#arrowLight)':'url(#arrow)'});svg.appendChild(line);var fd=svgCreate('circle',{class:'flow-dot',cx:0,cy:0,r:0,fill:'var(--accent)'});svg.appendChild(fd);flowDots.push({el:fd,sx:f.x,sy:f.y+26,ex:t.x,ey:t.y-26});});
components.forEach(function(cp){var p=positions[cp.id];var g=svgCreate('g',{class:'node-g',tabIndex:0,role:'button','aria-label':cp.name+': '+cp.sublabel});g.dataset.id=cp.id;var rx=svgCreate('rect',{x:p.x-80,y:p.y-26,width:160,height:52,rx:10,class:'node-rect'});g.appendChild(rx);var lbl=svgCreate('text',{x:p.x,y:p.y-4,class:'node-label'});lbl.textContent=cp.name;g.appendChild(lbl);var slbl=svgCreate('text',{x:p.x,y:p.y+14,class:'node-sublabel'});slbl.textContent=cp.sublabel;g.appendChild(slbl);g.addEventListener('click',function(){selectNode(cp.id);});g.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(cp.id);}});svg.appendChild(g);nodes.push({el:g,data:cp,pos:p});});
var selected=false;components.forEach(function(c){if(!selected){selectNode(c.id);selected=true;}});renderSteps();}
function svgCreate(tag,attrs){var el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(var k in attrs)el.setAttribute(k,attrs[k]);return el;}
function selectNode(id){activeNode=id;var cp=getComp(id);if(!cp)return;nodes.forEach(function(n){var r=n.el.querySelector('.node-rect');if(r)r.classList.toggle('active',n.data.id===id);});infoTitle.textContent=cp.name+' - '+cp.sublabel;infoDesc.innerHTML='<strong>Purpose:</strong> '+cp.purpose+'<br><br><strong>How it works:</strong> '+cp.how+'<br><br><strong>Why it matters:</strong> '+cp.why+'<br><br><strong>Analogy:</strong> '+cp.analogy+(cp.funFact?'<br><br><strong>Fun fact:</strong> '+cp.funFact:'')+'<br><br><strong>Key takeaway:</strong> '+cp.takeaway+'<br><br><strong>Common mistake:</strong> '+cp.mistake;var items=stepsList.querySelectorAll('li');items.forEach(function(li){li.classList.toggle('active',li.dataset.id===id);});}
function getComp(id){for(var i=0;i<components.length;i++){if(components[i].id===id)return components[i];}return null;}
function renderSteps(){stepsList.innerHTML='';components.forEach(function(c){var li=document.createElement('li');li.dataset.id=c.id;li.textContent=c.name+' - '+c.sublabel;li.tabIndex=0;li.addEventListener('click',function(){selectNode(c.id);});li.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();selectNode(c.id);}});stepsList.appendChild(li);});}
function animateDiagram(){var start=performance.now();function frame(now){if(!animating){rafId=null;return;}var dt=(now-start)/1000*speed;t=(t+dt)%1;flowDots.forEach(function(d){d.el.setAttribute('cx',d.sx+(d.ex-d.sx)*t);d.el.setAttribute('cy',d.sy+(d.ey-d.sy)*t);d.el.setAttribute('r',4);});rafId=requestAnimationFrame(frame);}rafId=requestAnimationFrame(frame);}
function setupControls(){themeBtn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem('consica-theme',theme);});playBtn.addEventListener('click',function(){animating=!animating;if(animating){playBtn.innerHTML='&#9646;&#9646;';animateDiagram();}else{playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});resetBtn.addEventListener('click',function(){t=0;flowDots.forEach(function(d){d.el.setAttribute('r',0);});if(animating){animating=false;playBtn.innerHTML='&#9654;';if(rafId){cancelAnimationFrame(rafId);rafId=null;}}});speedSlider.addEventListener('input',function(){speed=parseFloat(this.value);speedVal.textContent=speed+'x';});document.addEventListener('keydown',function(e){if(e.key==='Escape'){challengeOverlay.classList.add('hidden');completionOverlay.classList.add('hidden');}});}
function setupChallenge(){challengeBtn.addEventListener('click',function(){openChallenge();});challengeClose.addEventListener('click',function(){challengeOverlay.classList.add('hidden');});completionClose.addEventListener('click',function(){completionOverlay.classList.add('hidden');challengeOverlay.classList.add('hidden');});}
function openChallenge(){challengeState.questions=challenges.slice().sort(function(){return Math.random()-0.5;}).slice(0,5);challengeState.current=0;challengeState.answers={};challengeState.submitted=false;challengeOverlay.classList.remove('hidden');renderQuestion();}
function renderQuestion(){var q=challengeState.questions[challengeState.current];if(!q){finishChallenge();return;}var html='<div class="question"><div class="question-text">'+(challengeState.current+1)+'. '+q.q+'</div><div class="options">';q.o.forEach(function(opt,i){var sel=challengeState.answers[challengeState.current]===i?' selected':'';var cls=challengeState.submitted?(i===q.a?' correct':(challengeState.answers[challengeState.current]===i?' wrong':'')):'';html+='<label class="option-label'+sel+cls+'"><input type="radio" name="q'+challengeState.current+'" value="'+i+'"'+(challengeState.submitted?' disabled':'')+(sel?' checked':'')+' onchange="('+selectOption.toString()+')('+challengeState.current+','+i+')">'+opt+'</label>';});html+='</div></div>';html+='<div class="challenge-actions">';if(!challengeState.submitted){html+='<button class="btn-primary" onclick="('+submitChallenge.toString()+')()">Submit Answer</button>';}else{if(challengeState.current<challengeState.questions.length-1){html+='<button class="btn-primary" onclick="('+nextQuestion.toString()+')()">Next Question</button>';}else{html+='<button class="btn-primary" onclick="('+finishChallenge.toString()+')()">See Results</button>';}}html+='</div>';challengeBody.innerHTML=html;}
function selectOption(qIdx,optIdx){if(challengeState.submitted)return;challengeState.answers[qIdx]=optIdx;renderQuestion();}
function submitChallenge(){challengeState.submitted=true;renderQuestion();}
function nextQuestion(){challengeState.current++;challengeState.submitted=false;renderQuestion();}
function finishChallenge(){var correct=0,total=challengeState.questions.length;challengeState.questions.forEach(function(q,i){if(challengeState.answers[i]===q.a)correct++;});completionScore.textContent='You scored '+correct+'/'+total;completionOverlay.classList.remove('hidden');}
document.addEventListener('DOMContentLoaded',init);
if(document.readyState==='complete'||document.readyState==='interactive')init();
})();
