(function(){'use strict';
const STORE='consica-theme';
const nodes=[{id:'AS1',name:'Autonomous System 64500',desc:'An AS is a collection of IP networks under a single administrative domain. AS 64500 runs OSPF internally.',details:'ASN: 64500 (Private)\nIGP: OSPF\nRouters: R1, R2, R3\nStatus: Internal BGP ready'},{id:'AS2',name:'Autonomous System 64501',desc:'AS 64501 peers with AS 64500 and 64502 via eBGP. Routes are advertised between autonomous systems.',details:'ASN: 64501 (Private)\nIGP: OSPF\nRouters: R4, R5\nPeers: AS 64500, AS 64502'},{id:'AS3',name:'Autonomous System 64502',desc:'AS 64502 uses EIGRP as its interior gateway protocol. Connects to AS 64501 via eBGP.',details:'ASN: 64502 (Private)\nIGP: EIGRP\nRouters: R6, R7\nPeers: AS 64501'},{id:'BGP',name:'Border Gateway Protocol',desc:'BGP is the routing protocol of the internet. It exchanges routing information between autonomous systems using path vectors.',details:'Type: Path Vector\nPort: TCP 179\nMetric: Path attributes\nBest Path: Shortest AS path\nRFC: 4271'},{id:'OSPF',name:'OSPF Protocol',desc:'Open Shortest Path First is a link-state IGP that uses Dijkstra\'s algorithm to compute the shortest path tree.',details:'Type: Link State\nAlgorithm: Dijkstra\nMetric: Cost (bandwidth)\nArea: 0 (Backbone)\nConvergence: Fast'},{id:'EIGRP',name:'EIGRP Protocol',desc:'Enhanced Interior Gateway Routing Protocol is a Cisco proprietary hybrid protocol combining distance vector and link state features.',details:'Type: Hybrid\nAlgorithm: DUAL\nMetric: Bandwidth + Delay\nConvergence: Very fast\nCisco Proprietary'}];
const questions=[{q:'What does BGP use to exchange routes?',opts:['UDP','TCP port 179','ICMP','IP only'],ans:1},{q:'Which algorithm does OSPF use?',opts:['Bellman-Ford','Dijkstra','DUAL','Floyd'],ans:1},{q:'What type of protocol is BGP?',opts:['Link State','Distance Vector','Path Vector','Hybrid'],ans:2},{q:'Which protocol is Cisco proprietary?',opts:['OSPF','BGP','RIP','EIGRP'],ans:3},{q:'What metric does OSPF primarily use?',opts:['Hop count','Bandwidth cost','Delay','Load'],ans:1},{q:'What separates different autonomous systems?',opts:['Routers','Switches','BGP','Firewalls'],ans:2}];
let speed=1,playing=false,theme='dark',rAF=null,t=0;

function init(){showSkeleton();try{setupTheme();setupSpeed();setupNodes();setupControls();setupChallenge();setupCompletion();hideSkeleton();showApp();startRAF();}catch(e){showError(e.message);}}
function showSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=false;}
function hideSkeleton(){const s=document.getElementById('skeleton');if(s)s.hidden=true;}
function showApp(){const a=document.getElementById('app');if(a)a.hidden=false;}
function showError(msg){const e=document.getElementById('error-boundary');const m=document.getElementById('error-msg');hideSkeleton();if(e)e.hidden=false;if(m)m.textContent=msg;const r=document.getElementById('error-retry');if(r)r.onclick=init;}
function setupTheme(){const stored=localStorage.getItem(STORE);theme=stored||'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('theme-toggle');if(btn)btn.addEventListener('click',function(){theme=theme==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);localStorage.setItem(STORE,theme);});}
function setupSpeed(){const slider=document.getElementById('speed-slider');const val=document.getElementById('speed-value');if(slider){slider.addEventListener('input',function(){speed=parseFloat(this.value);if(val)val.textContent=speed+'×';});}}
function setupNodes(){nodes.forEach(function(n){var sel='[data-as="'+n.id+'"], [data-proto="'+n.id+'"]';var els=document.querySelectorAll(sel);els.forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo(n);});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();showInfo(n);}});});});document.querySelectorAll('.router-node').forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();showInfo({id:this.getAttribute('data-router'),name:'Router '+this.getAttribute('data-router'),desc:'A router that forwards packets between networks using routing tables.',details:'Function: Packet forwarding\nLayer: Network (Layer 3)\nProtocols: BGP, OSPF, EIGRP\nTable: Routing/Forwarding'});});});document.addEventListener('click',function(e){if(!e.target.closest('.as-region')&&!e.target.closest('.proto-card')&&!e.target.closest('.router-node')&&!e.target.closest('.bgp-panel')&&!e.target.closest('.info-panel')){const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;}});}
function showInfo(node){const panel=document.getElementById('info-panel');const title=document.getElementById('info-title');const desc=document.getElementById('info-desc');const details=document.getElementById('info-details');if(!panel)return;title.textContent=node.name;desc.textContent=node.desc;details.innerHTML='<p>'+node.details.split('\n').join('<br>')+'</p>';panel.hidden=false;}
function setupControls(){const play=document.getElementById('play-btn');if(play)play.addEventListener('click',function(){playing=!playing;this.textContent=playing?'Pause':'Play';});const reset=document.getElementById('reset-btn');if(reset)reset.addEventListener('click',resetAll);}
function startRAF(){function frame(){if(playing){t+=0.015*speed;var x=250+200*Math.sin(t);var y=220+80*Math.cos(t*0.7);var p=document.getElementById('bgp-packet');if(p){p.setAttribute('cx',x);p.setAttribute('cy',y);p.setAttribute('visibility','visible');}}rAF=requestAnimationFrame(frame);}rAF=requestAnimationFrame(frame);}
function resetAll(){playing=false;const play=document.getElementById('play-btn');if(play)play.textContent='Play';t=0;const p=document.getElementById('bgp-packet');if(p)p.setAttribute('visibility','hidden');const panel=document.getElementById('info-panel');if(panel)panel.hidden=true;const slider=document.getElementById('speed-slider');if(slider){slider.value='1';speed=1;const val=document.getElementById('speed-value');if(val)val.textContent='1×';}}
function setupChallenge(){const btn=document.getElementById('challenge-btn');const section=document.getElementById('challenge-section');if(btn&&section){btn.addEventListener('click',function(){section.hidden=!section.hidden;if(!section.hidden)renderChallenge();});}}
let challengeAnswered=false;
function renderChallenge(){const container=document.getElementById('challenge-questions');if(!container)return;let html='';questions.forEach(function(q,i){html+='<div class="challenge-q"><p>'+(i+1)+'. '+q.q+'</p>';q.opts.forEach(function(o,j){html+='<label><input type="radio" name="chq'+i+'" value="'+j+'">'+o+'</label>';});html+='</div>';});container.innerHTML=html;const submit=document.getElementById('challenge-submit');const retry=document.getElementById('challenge-retry');const result=document.getElementById('challenge-result');if(submit)submit.onclick=function(){let correct=0;questions.forEach(function(q,i){const sel=document.querySelector('input[name="chq'+i+'"]:checked');if(sel&&parseInt(sel.value)===q.ans)correct++;});const total=questions.length;const pct=Math.round(correct/total*100);if(result){result.hidden=false;result.className='challenge-result '+(pct>=70?'pass':'fail');result.textContent=pct>=70?'Pass! '+correct+'/'+total+' correct ('+pct+'%)':'Needs improvement. '+correct+'/'+total+' correct ('+pct+'%)';}if(pct>=70&&!challengeAnswered){challengeAnswered=true;const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=false;}};if(retry)retry.onclick=function(){renderChallenge();if(result)result.hidden=true;};}
function setupCompletion(){const close=document.getElementById('completion-close');if(close)close.addEventListener('click',function(){const overlay=document.getElementById('completion-overlay');if(overlay)overlay.hidden=true;});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();
